# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityMixinEmpty.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AbilityMixinEmpty(betterproto.Message):
    is_swim: bool = betterproto.bool_field(1)
