# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityApplyLevelModifier.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AbilityApplyLevelModifier(betterproto.Message):
    apply_entity_id: int = betterproto.uint32_field(6)
