# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityFloatValue.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AbilityFloatValue(betterproto.Message):
    value: float = betterproto.float_field(1)
