# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityMixinAvatarSteerByCamera.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class AbilityMixinAvatarSteerByCamera(betterproto.Message):
    target_dir: "Vector" = betterproto.message_field(7)
    target_pos: "Vector" = betterproto.message_field(6)
