# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityMixinWindSeedSpawner.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Vector import *


@dataclass
class AbilityMixinWindSeedSpawner(betterproto.Message):
    add_signal: "AbilityMixinWindSeedSpawnerAddSignal" = betterproto.message_field(
        2, group="cmd"
    )
    refresh_seed: "AbilityMixinWindSeedSpawnerRefreshSeed" = betterproto.message_field(
        15, group="cmd"
    )
    catch_seed: "AbilityMixinWindSeedSpawnerCatchSeed" = betterproto.message_field(
        11, group="cmd"
    )


@dataclass
class AbilityMixinWindSeedSpawnerAddSignal(betterproto.Message):
    pass


@dataclass
class AbilityMixinWindSeedSpawnerRefreshSeed(betterproto.Message):
    pos_list: List["Vector"] = betterproto.message_field(6)


@dataclass
class AbilityMixinWindSeedSpawnerCatchSeed(betterproto.Message):
    entity_id: int = betterproto.uint32_field(8)
