# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityMixinScenePropSync.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MassivePropSyncInfo import *


@dataclass
class AbilityMixinScenePropSync(betterproto.Message):
    delete_id_list: List[int] = betterproto.int64_field(5)
    is_clear_all: bool = betterproto.bool_field(12)
    massive_prop_list: List["MassivePropSyncInfo"] = betterproto.message_field(15)
