# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityActionGenerateElemBall.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class AbilityActionGenerateElemBall(betterproto.Message):
    room_id: int = betterproto.uint32_field(2)
    pos: "Vector" = betterproto.message_field(7)
    rot: "Vector" = betterproto.message_field(13)
