# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityMixinFieldEntityCountChange.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AbilityMixinFieldEntityCountChange(betterproto.Message):
    field_entity_count: int = betterproto.uint32_field(14)
