# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityString.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AbilityString(betterproto.Message):
    str: str = betterproto.string_field(1, group="type")
    hash: int = betterproto.uint32_field(2, group="type")
