# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AbilityMixinGlobalShield.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AbilityMixinGlobalShield(betterproto.Message):
    is_create_effect: bool = betterproto.bool_field(4)
    sub_shield: float = betterproto.float_field(7)
    height_offset: float = betterproto.float_field(5)
    avatar_id: int = betterproto.uint32_field(11)
    max_shield: float = betterproto.float_field(10)
    shield_effect_name: str = betterproto.string_field(2)
