# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ActivityTakeWatcherRewardBatchRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


@dataclass
class ActivityTakeWatcherRewardBatchRsp(betterproto.Message):
    """
    CmdId: 2109 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    watcher_id_list: List[int] = betterproto.uint32_field(6)
    retcode: int = betterproto.int32_field(15)
    activity_id: int = betterproto.uint32_field(7)
    item_list: List["ItemParam"] = betterproto.message_field(1)
