# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ActivityTakeAllScoreRewardReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ActivityTakeAllScoreRewardReq(betterproto.Message):
    """
    CmdId: 8372 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    activity_id: int = betterproto.uint32_field(9)
