# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AISnapshotInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .AISnapshotEntityData import *


@dataclass
class AISnapshotInfo(betterproto.Message):
    ai_snapshots: List["AISnapshotEntityData"] = betterproto.message_field(13)
