# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AiSyncInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AiSyncInfo(betterproto.Message):
    entity_id: int = betterproto.uint32_field(9)
    is_self_killing: bool = betterproto.bool_field(8)
    has_path_to_target: bool = betterproto.bool_field(4)
