# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AllCoopInfoNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MainCoop import *


@dataclass
class AllCoopInfoNotify(betterproto.Message):
    """
    CmdId: 1976 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    main_coop_list: List["MainCoop"] = betterproto.message_field(14)
