# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AnchorPointData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class AnchorPointData(betterproto.Message):
    scene_id: int = betterproto.uint32_field(5)
    anchor_point_id: int = betterproto.uint32_field(9)
    end_time: int = betterproto.uint32_field(8)
    pos: "Vector" = betterproto.message_field(15)
    rot: "Vector" = betterproto.message_field(2)
