# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AskAddFriendNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .FriendBrief import *


@dataclass
class AskAddFriendNotify(betterproto.Message):
    """
    CmdId: 4065 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    target_friend_brief: "FriendBrief" = betterproto.message_field(15)
    target_uid: int = betterproto.uint32_field(9)
