# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AsterLittleStageState.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class AsterLittleStageState(betterproto.Enum):
    ASTER_LITTLE_STAGE_STATE_NONE = 0
    ASTER_LITTLE_STAGE_STATE_UNSTARTED = 1
    ASTER_LITTLE_STAGE_STATE_STARTED = 2
    ASTER_LITTLE_STAGE_STATE_FINISHED = 3
