# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AsterMidDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .AsterMidCampInfo import *


@dataclass
class AsterMidDetailInfo(betterproto.Message):
    begin_time: int = betterproto.uint32_field(10)
    camp_list: List["AsterMidCampInfo"] = betterproto.message_field(7)
    is_open: bool = betterproto.bool_field(4)
    collect_count: int = betterproto.uint32_field(11)
