# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AvatarDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .AvatarInfo import *
from .AvatarTeam import *


@dataclass
class AvatarDataNotify(betterproto.Message):
    """
    CmdId: 1633 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    owned_costume_list: List[int] = betterproto.uint32_field(11)
    choose_avatar_guid: int = betterproto.uint64_field(8)
    avatar_team_map: Dict[int, "AvatarTeam"] = betterproto.map_field(
        7, betterproto.TYPE_UINT32, betterproto.TYPE_MESSAGE
    )
    unk3000__n_i_g_p_i_c_l_b_h_m_a: List[int] = betterproto.uint32_field(9)
    temp_avatar_guid_list: List[int] = betterproto.uint64_field(12)
    owned_flycloak_list: List[int] = betterproto.uint32_field(1)
    avatar_list: List["AvatarInfo"] = betterproto.message_field(6)
    cur_avatar_team_id: int = betterproto.uint32_field(2)
