# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AvatarExpeditionAllDataRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .AvatarExpeditionInfo import *


@dataclass
class AvatarExpeditionAllDataRsp(betterproto.Message):
    """
    CmdId: 1648 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    open_expedition_list: List[int] = betterproto.uint32_field(3)
    retcode: int = betterproto.int32_field(15)
    expedition_count_limit: int = betterproto.uint32_field(12)
    expedition_info_map: Dict[int, "AvatarExpeditionInfo"] = betterproto.map_field(
        4, betterproto.TYPE_UINT64, betterproto.TYPE_MESSAGE
    )
