# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AvatarExpeditionGetRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .AvatarExpeditionInfo import *
from .ItemParam import *


@dataclass
class AvatarExpeditionGetRewardRsp(betterproto.Message):
    """
    CmdId: 1784 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__h_b_k_h_o_b_p_g_c_l_h: List["ItemParam"] = betterproto.message_field(9)
    item_list: List["ItemParam"] = betterproto.message_field(8)
    expedition_info_map: Dict[int, "AvatarExpeditionInfo"] = betterproto.map_field(
        12, betterproto.TYPE_UINT64, betterproto.TYPE_MESSAGE
    )
    retcode: int = betterproto.int32_field(2)
