# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AvatarPromoteGetRewardReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AvatarPromoteGetRewardReq(betterproto.Message):
    """
    CmdId: 1696 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    avatar_guid: int = betterproto.uint64_field(7)
    promote_level: int = betterproto.uint32_field(12)
