# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AvatarFetterLevelRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AvatarFetterLevelRewardRsp(betterproto.Message):
    """
    CmdId: 1606 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    avatar_guid: int = betterproto.uint64_field(4)
    reward_id: int = betterproto.uint32_field(1)
    retcode: int = betterproto.int32_field(13)
    fetter_level: int = betterproto.uint32_field(14)
