# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AvatarSkillMaxChargeCountNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AvatarSkillMaxChargeCountNotify(betterproto.Message):
    """
    CmdId: 1003 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    skill_id: int = betterproto.uint32_field(6)
    max_charge_count: int = betterproto.uint32_field(11)
    avatar_guid: int = betterproto.uint64_field(7)
