# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: AvatarChangeCostumeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .SceneEntityInfo import *


@dataclass
class AvatarChangeCostumeNotify(betterproto.Message):
    """
    CmdId: 1644 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    entity_info: "SceneEntityInfo" = betterproto.message_field(7)
