# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BalloonPlayerInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BalloonPlayerInfo(betterproto.Message):
    uid: int = betterproto.uint32_field(15)
    cur_score: int = betterproto.uint32_field(2)
    combo_disable_time: int = betterproto.uint32_field(14)
    combo: int = betterproto.uint32_field(11)
