# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BalloonSettleInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .OnlinePlayerInfo import *


@dataclass
class BalloonSettleInfo(betterproto.Message):
    uid: int = betterproto.uint32_field(3)
    shoot_count: int = betterproto.uint32_field(12)
    max_combo: int = betterproto.uint32_field(9)
    final_score: int = betterproto.uint32_field(7)
    player_info: "OnlinePlayerInfo" = betterproto.message_field(2)
