# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BargainStartNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .BargainSnapshot import *


@dataclass
class BargainStartNotify(betterproto.Message):
    """
    CmdId: 404 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    bargain_id: int = betterproto.uint32_field(4)
    snapshot: "BargainSnapshot" = betterproto.message_field(2)
