# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BargainSnapshot.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BargainSnapshot(betterproto.Message):
    expected_price: int = betterproto.uint32_field(3)
    cur_mood: int = betterproto.int32_field(14)
    price_low_limit: int = betterproto.uint32_field(2)
    bargain_id: int = betterproto.uint32_field(5)
