# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BartenderActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_KJODHFMHMNC import *
from .Unk2700_LBIDBGLGKCJ import *


@dataclass
class BartenderActivityDetailInfo(betterproto.Message):
    unk2700__b_m_o_a_i_j_m_h_p_g_a: List[int] = betterproto.uint32_field(3)
    unk2700__j_i_c_a_a_e_m_p_n_b_c: bool = betterproto.bool_field(13)
    is_content_closed: bool = betterproto.bool_field(6)
    unk2700__m_e_g_o_p_k_b_e_h_o_h: List[
        "Unk2700_LBIDBGLGKCJ"
    ] = betterproto.message_field(5)
    unk2700__a_i_k_f_m_m_l_f_i_j_i: List[int] = betterproto.uint32_field(14)
    unk2700__d_a_g_g_a_e_c_b_d_e_g: List[
        "Unk2700_KJODHFMHMNC"
    ] = betterproto.message_field(2)
