# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BattlePassMissionUpdateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .BattlePassMission import *


@dataclass
class BattlePassMissionUpdateNotify(betterproto.Message):
    """
    CmdId: 2618 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    mission_list: List["BattlePassMission"] = betterproto.message_field(1)
