# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BattlePassProduct.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BattlePassProduct(betterproto.Message):
    normal_product_id: str = betterproto.string_field(13)
    extra_product_id: str = betterproto.string_field(10)
    upgrade_product_id: str = betterproto.string_field(6)
