# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BattlePassUnlockStatus.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class BattlePassUnlockStatus(betterproto.Enum):
    BATTLE_PASS_UNLOCK_STATUS_INVALID = 0
    BATTLE_PASS_UNLOCK_STATUS_FREE = 1
    BATTLE_PASS_UNLOCK_STATUS_PAID = 2
