# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BattlePassRewardTakeOption.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .BattlePassRewardTag import *


@dataclass
class BattlePassRewardTakeOption(betterproto.Message):
    tag: "BattlePassRewardTag" = betterproto.message_field(10)
    option_idx: int = betterproto.uint32_field(14)
