# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BigTalentPointConvertRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BigTalentPointConvertRsp(betterproto.Message):
    """
    CmdId: 1021 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(1)
    avatar_guid: int = betterproto.uint64_field(8)
