# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BlessingRedeemRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto


@dataclass
class BlessingRedeemRewardRsp(betterproto.Message):
    """
    CmdId: 2098 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pic_num_map: Dict[int, int] = betterproto.map_field(
        12, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    retcode: int = betterproto.int32_field(15)
