# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BlessingAcceptAllGivePicReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BlessingAcceptAllGivePicReq(betterproto.Message):
    """
    CmdId: 2045 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
