# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BlessingGetFriendPicListRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .BlessingFriendPicData import *


@dataclass
class BlessingGetFriendPicListRsp(betterproto.Message):
    """
    CmdId: 2056 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(2)
    friend_pic_data_list: List["BlessingFriendPicData"] = betterproto.message_field(6)
