# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BlessingRedeemRewardReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BlessingRedeemRewardReq(betterproto.Message):
    """
    CmdId: 2137 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
