# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BlessingRecvPicRecord.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ProfilePicture import *


@dataclass
class BlessingRecvPicRecord(betterproto.Message):
    nickname: str = betterproto.string_field(1)
    remark_name: str = betterproto.string_field(2)
    pic_id: int = betterproto.uint32_field(3)
    uid: int = betterproto.uint32_field(5)
    avatar_id: int = betterproto.uint32_field(6)
    signature: str = betterproto.string_field(10)
    index: int = betterproto.uint32_field(14)
    is_recv: bool = betterproto.bool_field(7)
    profile_picture: "ProfilePicture" = betterproto.message_field(9)
