# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BlitzRushActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .BlitzRushStage import *
from .ParkourLevelInfo import *


@dataclass
class BlitzRushActivityDetailInfo(betterproto.Message):
    stage_list: List["BlitzRushStage"] = betterproto.message_field(10)
    content_close_time: int = betterproto.uint32_field(14)
    is_content_closed: bool = betterproto.bool_field(2)
    parkour_level_info_list: List["ParkourLevelInfo"] = betterproto.message_field(6)
