# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BlossomScheduleInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BlossomScheduleInfo(betterproto.Message):
    progress: int = betterproto.uint32_field(13)
    state: int = betterproto.uint32_field(10)
    round: int = betterproto.uint32_field(4)
    circle_camp_id: int = betterproto.uint32_field(15)
    refresh_id: int = betterproto.uint32_field(6)
    finish_progress: int = betterproto.uint32_field(14)
