# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BonusActivityInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BonusActivityInfo(betterproto.Message):
    bonus_activity_id: int = betterproto.uint32_field(6)
    state: int = betterproto.uint32_field(3)
