# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BonusActivityInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BonusActivityInfoReq(betterproto.Message):
    """
    CmdId: 2548 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
