# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BossChestActivateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class BossChestActivateNotify(betterproto.Message):
    """
    CmdId: 803 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    qualify_uid_list: List[int] = betterproto.uint32_field(1)
    entity_id: int = betterproto.uint32_field(12)
