# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BundleInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class BundleInfo(betterproto.Message):
    unk2700__o_g_n_e_a_e_g_h_c_p_m: List[int] = betterproto.uint32_field(13)
