# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BuyBattlePassLevelReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BuyBattlePassLevelReq(betterproto.Message):
    """
    CmdId: 2647 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    buy_level: int = betterproto.uint32_field(8)
