# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BuyGoodsReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ShopGoods import *


@dataclass
class BuyGoodsReq(betterproto.Message):
    """
    CmdId: 712 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    buy_count: int = betterproto.uint32_field(14)
    goods: "ShopGoods" = betterproto.message_field(15)
    shop_type: int = betterproto.uint32_field(7)
