# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: BuyResinReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class BuyResinReq(betterproto.Message):
    """
    CmdId: 602 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
