# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CalcWeaponUpgradeReturnItemsReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


@dataclass
class CalcWeaponUpgradeReturnItemsReq(betterproto.Message):
    """
    CmdId: 633 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    food_weapon_guid_list: List[int] = betterproto.uint64_field(15)
    target_weapon_guid: int = betterproto.uint64_field(12)
    item_param_list: List["ItemParam"] = betterproto.message_field(3)
