# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CalcWeaponUpgradeReturnItemsRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


@dataclass
class CalcWeaponUpgradeReturnItemsRsp(betterproto.Message):
    """
    CmdId: 684 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    item_param_list: List["ItemParam"] = betterproto.message_field(4)
    retcode: int = betterproto.int32_field(15)
    target_weapon_guid: int = betterproto.uint64_field(8)
