# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CancelCoopTaskReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CancelCoopTaskReq(betterproto.Message):
    """
    CmdId: 1997 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    chapter_id: int = betterproto.uint32_field(13)
