# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChannelerSlabEnterLoopDungeonReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ChannelerSlabEnterLoopDungeonReq(betterproto.Message):
    """
    CmdId: 8869 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    point_id: int = betterproto.uint32_field(9)
    dungeon_index: int = betterproto.uint32_field(10)
    condition_id_list: List[int] = betterproto.uint32_field(5)
    difficulty_id: int = betterproto.uint32_field(12)
