# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChannelerSlabOneofDungeon.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ChannelerSlabOneofDungeon(betterproto.Message):
    is_done: bool = betterproto.bool_field(8)
    dungeon_id: int = betterproto.uint32_field(12)
    reward_id: int = betterproto.uint32_field(13)
