# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChannelerSlabWearBuffReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ChannelerSlabWearBuffReq(betterproto.Message):
    """
    CmdId: 8107 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    buff_id: int = betterproto.uint32_field(3)
    is_mp: bool = betterproto.bool_field(5)
    slot_id: int = betterproto.uint32_field(13)
