# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChannelerSlabChallenge.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ChannelerSlabCamp import *


@dataclass
class ChannelerSlabChallenge(betterproto.Message):
    active_camp_index: int = betterproto.uint32_field(5)
    camp_list: List["ChannelerSlabCamp"] = betterproto.message_field(14)
