# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChannelerSlabSaveAssistInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ChannelerSlabAssistInfo import *


@dataclass
class ChannelerSlabSaveAssistInfoReq(betterproto.Message):
    """
    CmdId: 8416 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    assist_info_list: List["ChannelerSlabAssistInfo"] = betterproto.message_field(8)
