# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChangeAvatarReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class ChangeAvatarReq(betterproto.Message):
    """
    CmdId: 1640 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    move_pos: "Vector" = betterproto.message_field(15)
    skill_id: int = betterproto.uint32_field(2)
    guid: int = betterproto.uint64_field(7)
    is_move: bool = betterproto.bool_field(10)
