# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChangeWorldToSingleModeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ChangeWorldToSingleModeNotify(betterproto.Message):
    """
    CmdId: 3006 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
