# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChatHistoryNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ChatInfo import *


@dataclass
class ChatHistoryNotify(betterproto.Message):
    """
    CmdId: 3496 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    chat_info: List["ChatInfo"] = betterproto.message_field(9)
    channel_id: int = betterproto.uint32_field(12)
