# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CheckAddItemExceedLimitNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class CheckAddItemExceedLimitNotifyItemExceedLimitMsgType(betterproto.Enum):
    ITEM_EXCEED_LIMIT_MSG_TYPE_DEFAULT = 0
    ITEM_EXCEED_LIMIT_MSG_TYPE_TEXT = 1
    ITEM_EXCEED_LIMIT_MSG_TYPE_DIALOG = 2
    ITEM_EXCEED_LIMIT_MSG_TYPE_Unk2700_BONLGEEEBBF = 3


@dataclass
class CheckAddItemExceedLimitNotify(betterproto.Message):
    """
    CmdId: 692 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_drop: bool = betterproto.bool_field(5)
    exceeded_item_type_list: List[int] = betterproto.uint32_field(10)
    exceeded_item_list: List[int] = betterproto.uint32_field(12)
    msg_type: "CheckAddItemExceedLimitNotifyItemExceedLimitMsgType" = (
        betterproto.enum_field(4)
    )
