# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChessPickCardReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ChessPickCardReq(betterproto.Message):
    """
    CmdId: 5333 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    card_id: int = betterproto.uint32_field(1)
    card_index: int = betterproto.uint32_field(4)
