# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChessManualRefreshCardsReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ChessManualRefreshCardsReq(betterproto.Message):
    """
    CmdId: 5389 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
