# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChessCardInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ChessCardInfo(betterproto.Message):
    effect_stack: int = betterproto.uint32_field(12)
    card_id: int = betterproto.uint32_field(11)
