# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChessMonsterInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ChessMonsterInfo(betterproto.Message):
    monster_id: int = betterproto.uint32_field(12)
    level: int = betterproto.uint32_field(2)
    affix_list: List[int] = betterproto.uint32_field(13)
