# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChessActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ChessActivityDetailInfo(betterproto.Message):
    level: int = betterproto.uint32_field(4)
    is_teach_dungeon_finished: bool = betterproto.bool_field(9)
    content_close_time: int = betterproto.uint32_field(14)
    obtained_exp: int = betterproto.uint32_field(8)
    is_content_closed: bool = betterproto.bool_field(5)
    available_exp: int = betterproto.uint32_field(2)
    exp: int = betterproto.uint32_field(13)
    finished_map_id_list: List[int] = betterproto.uint32_field(1)
    punish_over_time: int = betterproto.uint32_field(3)
