# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChessMysteryInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .ChessEntranceDetailInfo import *


@dataclass
class ChessMysteryInfo(betterproto.Message):
    entrance_point_map: Dict[int, int] = betterproto.map_field(
        13, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    exit_point_id_list: List[int] = betterproto.uint32_field(3)
    detail_info_map: Dict[int, "ChessEntranceDetailInfo"] = betterproto.map_field(
        5, betterproto.TYPE_UINT32, betterproto.TYPE_MESSAGE
    )
