# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ChildQuest.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ChildQuest(betterproto.Message):
    quest_config_id: int = betterproto.uint32_field(8)
    state: int = betterproto.uint32_field(4)
    quest_id: int = betterproto.uint32_field(15)
