# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CityInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CityInfo(betterproto.Message):
    city_id: int = betterproto.uint32_field(15)
    crystal_num: int = betterproto.uint32_field(3)
    level: int = betterproto.uint32_field(4)
