# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CityReputationInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .CityReputationExploreInfo import *
from .CityReputationHuntInfo import *
from .CityReputationQuestInfo import *
from .CityReputationRequestInfo import *


@dataclass
class CityReputationInfo(betterproto.Message):
    level: int = betterproto.uint32_field(4)
    next_refresh_time: int = betterproto.uint32_field(3)
    hunt_info: "CityReputationHuntInfo" = betterproto.message_field(11)
    taken_level_reward_list: List[int] = betterproto.uint32_field(2)
    total_accept_request_num: int = betterproto.uint32_field(6)
    request_info: "CityReputationRequestInfo" = betterproto.message_field(5)
    quest_info: "CityReputationQuestInfo" = betterproto.message_field(9)
    exp: int = betterproto.uint32_field(13)
    explore_info: "CityReputationExploreInfo" = betterproto.message_field(10)
