# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ClientAbilityChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .AbilityInvokeEntry import *


@dataclass
class ClientAbilityChangeNotify(betterproto.Message):
    """
    CmdId: 1175 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2200__f_n_a_f_d_m_a_p_l_h_p: bool = betterproto.bool_field(9)
    entity_id: int = betterproto.uint32_field(2)
    invokes: List["AbilityInvokeEntry"] = betterproto.message_field(3)
