# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ClientMassiveEntity.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .MassiveBoxInfo import *
from .MassiveGrassInfo import *
from .MassiveWaterInfo import *


@dataclass
class ClientMassiveEntity(betterproto.Message):
    entity_type: int = betterproto.uint32_field(1)
    config_id: int = betterproto.uint32_field(2)
    obj_id: int = betterproto.int64_field(3)
    water_info: "MassiveWaterInfo" = betterproto.message_field(4, group="entity_info")
    grass_info: "MassiveGrassInfo" = betterproto.message_field(5, group="entity_info")
    box_info: "MassiveBoxInfo" = betterproto.message_field(6, group="entity_info")
