# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ClientLogBodyLogin.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ClientLogBodyLogin(betterproto.Message):
    action_type: str = betterproto.string_field(1)
    action_result: str = betterproto.string_field(2)
    action_time: int = betterproto.uint32_field(3)
    xg: str = betterproto.string_field(4)
    signal_level: int = betterproto.uint32_field(5)
    dns: str = betterproto.string_field(6)
