# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ClientTriggerEventNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .EventTriggerType import *


@dataclass
class ClientTriggerEventNotify(betterproto.Message):
    """
    CmdId: 148 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    force_id: int = betterproto.uint32_field(3)
    event_type: "EventTriggerType" = betterproto.enum_field(2)
