# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ClientAbilityInitBeginNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ClientAbilityInitBeginNotify(betterproto.Message):
    """
    CmdId: 1112 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    entity_id: int = betterproto.uint32_field(1)
