# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ClientReportNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ClientReportNotify(betterproto.Message):
    """CmdId: 81 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true"""

    report_type: str = betterproto.string_field(1)
    report_value: str = betterproto.string_field(4)
