# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ClientPauseNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ClientPauseNotify(betterproto.Message):
    """
    CmdId: 260 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_open: bool = betterproto.bool_field(1)
