# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CodexDataUpdateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .CodexType import *


@dataclass
class CodexDataUpdateNotify(betterproto.Message):
    """
    CmdId: 4207 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    id: int = betterproto.uint32_field(8)
    weapon_max_promote_level: int = betterproto.uint32_field(15)
    type: "CodexType" = betterproto.enum_field(11)
