# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CombatInvocationsNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .CombatInvokeEntry import *


@dataclass
class CombatInvocationsNotify(betterproto.Message):
    """
    CmdId: 319 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    invoke_list: List["CombatInvokeEntry"] = betterproto.message_field(14)
