# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CompoundUnlockNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CompoundUnlockNotify(betterproto.Message):
    """
    CmdId: 128 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    compound_id: int = betterproto.uint32_field(3)
