# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CookGradeDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CookGradeDataNotify(betterproto.Message):
    """
    CmdId: 134 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    grade: int = betterproto.uint32_field(12)
