# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CookRecipeDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .CookRecipeData import *


@dataclass
class CookRecipeDataNotify(betterproto.Message):
    """
    CmdId: 106 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    recipe_data: "CookRecipeData" = betterproto.message_field(4)
