# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CookRecipeData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CookRecipeData(betterproto.Message):
    proficiency: int = betterproto.uint32_field(13)
    recipe_id: int = betterproto.uint32_field(9)
