# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CoopProgressUpdateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CoopProgressUpdateNotify(betterproto.Message):
    """
    CmdId: 1998 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    cur_coop_point: int = betterproto.uint32_field(11)
    is_have_progress: bool = betterproto.bool_field(12)
