# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CoopCgShowNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class CoopCgShowNotify(betterproto.Message):
    """
    CmdId: 1983 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    cg_list: List[int] = betterproto.uint32_field(10)
