# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CreateMassiveEntityRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CreateMassiveEntityRsp(betterproto.Message):
    """
    CmdId: 330 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(1)
