# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CreateVehicleReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class CreateVehicleReq(betterproto.Message):
    """
    CmdId: 893 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pos: "Vector" = betterproto.message_field(11)
    vehicle_id: int = betterproto.uint32_field(2)
    scene_point_id: int = betterproto.uint32_field(7)
    rot: "Vector" = betterproto.message_field(5)
