# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CrucibleActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .CrucibleBattleUidInfo import *
from .Vector import *


@dataclass
class CrucibleActivityDetailInfo(betterproto.Message):
    cost_time: int = betterproto.uint32_field(5)
    battle_world_level: int = betterproto.uint32_field(12)
    uid_info_list: List["CrucibleBattleUidInfo"] = betterproto.message_field(3)
    pos: "Vector" = betterproto.message_field(9)
