# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CurVehicleInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CurVehicleInfo(betterproto.Message):
    entity_id: int = betterproto.uint32_field(1)
    pos: int = betterproto.uint32_field(2)
