# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: CustomGadgetTreeInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .CustomCommonNodeInfo import *


@dataclass
class CustomGadgetTreeInfo(betterproto.Message):
    node_list: List["CustomCommonNodeInfo"] = betterproto.message_field(1)
