# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DailyDungeonEntryInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .DungeonEntryInfo import *


@dataclass
class DailyDungeonEntryInfo(betterproto.Message):
    dungeon_entry_config_id: int = betterproto.uint32_field(12)
    dungeon_entry_id: int = betterproto.uint32_field(15)
    recommend_dungeon_entry_info: "DungeonEntryInfo" = betterproto.message_field(1)
    recommend_dungeon_id: int = betterproto.uint32_field(4)
