# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DealAddFriendResultType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class DealAddFriendResultType(betterproto.Enum):
    DEAL_ADD_FRIEND_RESULT_TYPE_REJECT = 0
    DEAL_ADD_FRIEND_RESULT_TYPE_ACCEPT = 1
