# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DeleteFriendReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DeleteFriendReq(betterproto.Message):
    """
    CmdId: 4031 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    target_uid: int = betterproto.uint32_field(13)
