# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DelMailReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class DelMailReq(betterproto.Message):
    """
    CmdId: 1421 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    mail_id_list: List[int] = betterproto.uint32_field(12)
