# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DestroyMaterialRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class DestroyMaterialRsp(betterproto.Message):
    """
    CmdId: 618 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    item_count_list: List[int] = betterproto.uint32_field(12)
    item_id_list: List[int] = betterproto.uint32_field(13)
    retcode: int = betterproto.int32_field(11)
