# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DoGachaRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .GachaItem import *


@dataclass
class DoGachaRsp(betterproto.Message):
    """
    CmdId: 1535 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__l_e_e_p_e_l_h_d_i_n_g: bool = betterproto.bool_field(1435)
    gacha_schedule_id: int = betterproto.uint32_field(5)
    wish_item_id: int = betterproto.uint32_field(8)
    retcode: int = betterproto.int32_field(13)
    cost_item_num: int = betterproto.uint32_field(10)
    gacha_times_limit: int = betterproto.uint32_field(1)
    cost_item_id: int = betterproto.uint32_field(14)
    gacha_type: int = betterproto.uint32_field(12)
    ten_cost_item_id: int = betterproto.uint32_field(7)
    wish_max_progress: int = betterproto.uint32_field(9)
    unk2700__o_j_k_k_h_d_l_e_d_c_i: int = betterproto.uint32_field(1240)
    ten_cost_item_num: int = betterproto.uint32_field(3)
    left_gacha_times: int = betterproto.uint32_field(6)
    wish_progress: int = betterproto.uint32_field(2)
    gacha_times: int = betterproto.uint32_field(4)
    gacha_item_list: List["GachaItem"] = betterproto.message_field(15)
    new_gacha_random: int = betterproto.uint32_field(11)
