# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DoSetPlayerBornDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DoSetPlayerBornDataNotify(betterproto.Message):
    """
    CmdId: 147 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
