# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DraftOwnerInviteNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DraftOwnerInviteNotify(betterproto.Message):
    """
    CmdId: 5407 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    draft_id: int = betterproto.uint32_field(4)
    invite_deadline_time: int = betterproto.uint32_field(15)
