# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DraftGuestReplyInviteReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DraftGuestReplyInviteReq(betterproto.Message):
    """
    CmdId: 5421 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    draft_id: int = betterproto.uint32_field(10)
    is_agree: bool = betterproto.bool_field(3)
