# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DraftGuestReplyInviteNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DraftGuestReplyInviteNotify(betterproto.Message):
    """
    CmdId: 5490 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    draft_id: int = betterproto.uint32_field(5)
    is_agree: bool = betterproto.bool_field(9)
    guest_uid: int = betterproto.uint32_field(10)
