# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DraftGuestReplyTwiceConfirmNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DraftGuestReplyTwiceConfirmNotify(betterproto.Message):
    """
    CmdId: 5497 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_agree: bool = betterproto.bool_field(14)
    draft_id: int = betterproto.uint32_field(15)
    guest_uid: int = betterproto.uint32_field(7)
