# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DragonSpineChapterFinishNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DragonSpineChapterFinishNotify(betterproto.Message):
    """
    CmdId: 2069 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(13)
    chapter_id: int = betterproto.uint32_field(11)
    weapon_enhance_level: int = betterproto.uint32_field(14)
