# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DragonSpineChapterProgressChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DragonSpineChapterProgressChangeNotify(betterproto.Message):
    """
    CmdId: 2065 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(7)
    chapter_id: int = betterproto.uint32_field(11)
    cur_progress: int = betterproto.uint32_field(5)
