# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DropItemRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .StoreType import *


@dataclass
class DropItemRsp(betterproto.Message):
    """
    CmdId: 631 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(9)
    guid: int = betterproto.uint64_field(1)
    store_type: "StoreType" = betterproto.enum_field(15)
