# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DropSubfieldType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class DropSubfieldType(betterproto.Enum):
    DROP_SUBFIELD_TYPE_NONE = 0
    DROP_SUBFIELD_TYPE_ONE = 1
    DROP_SUBFIELD_TYPE_Unk2700_NNGMHCEADHE = 2
    DROP_SUBFIELD_TYPE_Unk2700_MKIJPEHKAJI = 3
    DROP_SUBFIELD_TYPE_Unk2700_DJDNENLGIEB = 4
