# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonCandidateTeamDismissNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .DungeonCandidateTeamDismissReason import *


@dataclass
class DungeonCandidateTeamDismissNotify(betterproto.Message):
    """
    CmdId: 963 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    reason: "DungeonCandidateTeamDismissReason" = betterproto.enum_field(9)
    player_uid: int = betterproto.uint32_field(12)
