# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonRestartResultNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DungeonRestartResultNotify(betterproto.Message):
    """
    CmdId: 940 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_add_accpet: bool = betterproto.bool_field(9)
