# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonCandidateTeamPlayerState.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class DungeonCandidateTeamPlayerState(betterproto.Enum):
    DUNGEON_CANDIDATE_TEAM_PLAYER_STATE_IDLE = 0
    DUNGEON_CANDIDATE_TEAM_PLAYER_STATE_CHANGING_AVATAR = 1
    DUNGEON_CANDIDATE_TEAM_PLAYER_STATE_READY = 2
