# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonCandidateTeamChangeAvatarRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DungeonCandidateTeamChangeAvatarRsp(betterproto.Message):
    """
    CmdId: 942 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(4)
