# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonCandidateTeamInviteNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DungeonCandidateTeamInviteNotify(betterproto.Message):
    """
    CmdId: 994 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    player_uid: int = betterproto.uint32_field(5)
    vaild_deadline_time_sec: int = betterproto.uint32_field(9)
    dungeon_id: int = betterproto.uint32_field(6)
