# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonCandidateTeamInfoNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .DungeonCandidateTeamAvatar import *
from .DungeonCandidateTeamPlayerState import *


@dataclass
class DungeonCandidateTeamInfoNotify(betterproto.Message):
    """
    CmdId: 927 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    player_state_map: Dict[
        int, "DungeonCandidateTeamPlayerState"
    ] = betterproto.map_field(10, betterproto.TYPE_UINT32, betterproto.TYPE_ENUM)
    dungeon_id: int = betterproto.uint32_field(9)
    ready_player_uid: List[int] = betterproto.uint32_field(13)
    match_type: int = betterproto.uint32_field(2)
    avatar_list: List["DungeonCandidateTeamAvatar"] = betterproto.message_field(4)
