# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonChallengeFinishNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto

from .ChannelerSlabLoopDungeonResultInfo import *
from .CustomDungeonResultInfo import *
from .EffigyChallengeDungeonResultInfo import *
from .PotionDungeonResultInfo import *
from .StrengthenPointData import *
from .Unk2700_FHOKHHBGPEG import *


@dataclass
class DungeonChallengeFinishNotify(betterproto.Message):
    """
    CmdId: 939 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    strengthen_point_data_map: Dict[int, "StrengthenPointData"] = betterproto.map_field(
        13, betterproto.TYPE_UINT32, betterproto.TYPE_MESSAGE
    )
    unk2700__o_n_c_d_l_p_d_h_f_a_b: "Unk2700_FHOKHHBGPEG" = betterproto.enum_field(9)
    is_new_record: bool = betterproto.bool_field(10)
    challenge_record_type: int = betterproto.uint32_field(7)
    time_cost: int = betterproto.uint32_field(4)
    current_value: int = betterproto.uint32_field(15)
    is_success: bool = betterproto.bool_field(3)
    challenge_index: int = betterproto.uint32_field(5)
    channeller_slab_loop_dungeon_result_info: "ChannelerSlabLoopDungeonResultInfo" = (
        betterproto.message_field(1521, group="detail")
    )
    effigy_challenge_dungeon_result_info: "EffigyChallengeDungeonResultInfo" = (
        betterproto.message_field(1627, group="detail")
    )
    potion_dungeon_result_info: "PotionDungeonResultInfo" = betterproto.message_field(
        1824, group="detail"
    )
    custom_dungeon_result_info: "CustomDungeonResultInfo" = betterproto.message_field(
        1664, group="detail"
    )
