# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonEntryToBeExploreNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DungeonEntryToBeExploreNotify(betterproto.Message):
    """
    CmdId: 3147 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    dungeon_entry_scene_point_id: int = betterproto.uint32_field(2)
    scene_id: int = betterproto.uint32_field(4)
    dungeon_entry_config_id: int = betterproto.uint32_field(10)
