# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonSettleExhibitionInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ExhibitionDisplayInfo import *
from .OnlinePlayerInfo import *


@dataclass
class DungeonSettleExhibitionInfo(betterproto.Message):
    player_info: "OnlinePlayerInfo" = betterproto.message_field(3)
    card_list: List["ExhibitionDisplayInfo"] = betterproto.message_field(13)
