# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonEntryInfoRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .DungeonEntryInfo import *
from .Unk2800_MHCFAGCKGIB import *


@dataclass
class DungeonEntryInfoRsp(betterproto.Message):
    """
    CmdId: 998 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    dungeon_entry_list: List["DungeonEntryInfo"] = betterproto.message_field(12)
    point_id: int = betterproto.uint32_field(15)
    unk2800__j_j_f_l_d_c_l_m_e_h_d: List[
        "Unk2800_MHCFAGCKGIB"
    ] = betterproto.message_field(4)
    recommend_dungeon_id: int = betterproto.uint32_field(14)
    retcode: int = betterproto.int32_field(11)
