# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonCandidateTeamLeaveReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DungeonCandidateTeamLeaveReq(betterproto.Message):
    """
    CmdId: 976 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
