# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonRestartInviteReplyReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DungeonRestartInviteReplyReq(betterproto.Message):
    """
    CmdId: 1000 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_accept: bool = betterproto.bool_field(11)
