# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: DungeonInterruptChallengeRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class DungeonInterruptChallengeRsp(betterproto.Message):
    """
    CmdId: 902 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(1)
    challenge_index: int = betterproto.uint32_field(2)
    group_id: int = betterproto.uint32_field(15)
    challenge_id: int = betterproto.uint32_field(11)
