# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EchoShellInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EchoShellInfo(betterproto.Message):
    shell_id: int = betterproto.uint32_field(1)
