# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EchoShellTakeRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EchoShellTakeRewardRsp(betterproto.Message):
    """
    CmdId: 8797 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    reward_id: int = betterproto.uint32_field(6)
    retcode: int = betterproto.int32_field(10)
