# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EffigyChallengeResultNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EffigyChallengeResultNotify(betterproto.Message):
    """
    CmdId: 2046 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_success: bool = betterproto.bool_field(5)
    challenge_max_score: int = betterproto.uint32_field(12)
    challenge_score: int = betterproto.uint32_field(3)
    challenge_id: int = betterproto.uint32_field(7)
