# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EndCameraSceneLookNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EndCameraSceneLookNotify(betterproto.Message):
    """
    CmdId: 217 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
