# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EnterChessDungeonReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EnterChessDungeonReq(betterproto.Message):
    """
    CmdId: 8191 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    map_id: int = betterproto.uint32_field(12)
