# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EnterTransPointRegionNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EnterTransPointRegionNotify(betterproto.Message):
    """
    CmdId: 205 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    scene_id: int = betterproto.uint32_field(8)
    point_id: int = betterproto.uint32_field(6)
