# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EnterRoguelikeDungeonNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .RogueCellInfo import *
from .RoguelikeRuneRecord import *


@dataclass
class EnterRoguelikeDungeonNotify(betterproto.Message):
    """
    CmdId: 8652 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_mist_clear: bool = betterproto.bool_field(14)
    dungeon_weight_config_id: int = betterproto.uint32_field(2)
    rune_record_list: List["RoguelikeRuneRecord"] = betterproto.message_field(6)
    onstage_avatar_guid_list: List[int] = betterproto.uint64_field(9)
    is_first_enter: bool = betterproto.bool_field(205)
    explored_cell_list: List[int] = betterproto.uint32_field(3)
    cell_info_map: Dict[int, "RogueCellInfo"] = betterproto.map_field(
        11, betterproto.TYPE_UINT32, betterproto.TYPE_MESSAGE
    )
    dungeon_id: int = betterproto.uint32_field(1)
    refresh_cost_item_count: int = betterproto.uint32_field(1999)
    bonus_resource_prop: float = betterproto.float_field(13)
    revise_monster_level: int = betterproto.uint32_field(1541)
    stage_id: int = betterproto.uint32_field(15)
    backstage_avatar_guid_list: List[int] = betterproto.uint64_field(10)
    cur_cell_id: int = betterproto.uint32_field(12)
    refresh_cost_item_id: int = betterproto.uint32_field(7)
    cur_level: int = betterproto.uint32_field(8)
