# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EnterWorldAreaRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EnterWorldAreaRsp(betterproto.Message):
    """
    CmdId: 243 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    area_type: int = betterproto.uint32_field(1)
    area_id: int = betterproto.uint32_field(7)
    retcode: int = betterproto.int32_field(9)
