# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EnterSceneDoneReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EnterSceneDoneReq(betterproto.Message):
    """
    CmdId: 277 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    enter_scene_token: int = betterproto.uint32_field(11)
