# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EnterSceneWeatherAreaNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EnterSceneWeatherAreaNotify(betterproto.Message):
    """
    CmdId: 256 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    weather_gadget_id: int = betterproto.uint32_field(13)
