# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EnterSceneDoneRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EnterSceneDoneRsp(betterproto.Message):
    """
    CmdId: 237 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    enter_scene_token: int = betterproto.uint32_field(15)
    retcode: int = betterproto.int32_field(7)
