# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EnterMechanicusDungeonRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EnterMechanicusDungeonRsp(betterproto.Message):
    """
    CmdId: 3975 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    wrong_uid: int = betterproto.uint32_field(12)
    difficult_level: int = betterproto.uint32_field(13)
    retcode: int = betterproto.int32_field(6)
    dungeon_id: int = betterproto.uint32_field(11)
