# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EntityJumpNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


class EntityJumpNotifyType(betterproto.Enum):
    TYPE_NULL = 0
    TYPE_ACTIVE = 1
    TYPE_PASSIVE = 2


@dataclass
class EntityJumpNotify(betterproto.Message):
    """
    CmdId: 222 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    jump_type: "EntityJumpNotifyType" = betterproto.enum_field(9)
    rot: "Vector" = betterproto.message_field(8)
    pos: "Vector" = betterproto.message_field(10)
    entity_id: int = betterproto.uint32_field(12)
