# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EntityAuthorityInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .AbilitySyncStateInfo import *
from .AnimatorParameterValueInfoPair import *
from .EntityRendererChangedInfo import *
from .SceneEntityAiInfo import *
from .Unk2700_HFMDKDHCJCM import *
from .Vector import *


@dataclass
class EntityAuthorityInfo(betterproto.Message):
    ability_info: "AbilitySyncStateInfo" = betterproto.message_field(1)
    renderer_changed_info: "EntityRendererChangedInfo" = betterproto.message_field(2)
    ai_info: "SceneEntityAiInfo" = betterproto.message_field(3)
    born_pos: "Vector" = betterproto.message_field(4)
    pose_para_list: List["AnimatorParameterValueInfoPair"] = betterproto.message_field(
        5
    )
    unk2700__k_d_g_m_o_p_e_l_h_n_e: "Unk2700_HFMDKDHCJCM" = betterproto.message_field(6)
