# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EntityFightPropUpdateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto


@dataclass
class EntityFightPropUpdateNotify(betterproto.Message):
    """
    CmdId: 1235 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    fight_prop_map: Dict[int, float] = betterproto.map_field(
        15, betterproto.TYPE_UINT32, betterproto.TYPE_FLOAT
    )
    entity_id: int = betterproto.uint32_field(13)
