# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EntityAiKillSelfNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EntityAiKillSelfNotify(betterproto.Message):
    """
    CmdId: 340 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    entity_id: int = betterproto.uint32_field(12)
