# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtAvatarUpdateFocusNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ForwardType import *
from .Vector import *


@dataclass
class EvtAvatarUpdateFocusNotify(betterproto.Message):
    """
    CmdId: 327 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    forward_type: "ForwardType" = betterproto.enum_field(7)
    focus_forward: "Vector" = betterproto.message_field(11)
    entity_id: int = betterproto.uint32_field(10)
