# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtAvatarLockChairReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class EvtAvatarLockChairReq(betterproto.Message):
    """
    CmdId: 318 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    chair_id: int = betterproto.uint64_field(5)
    position: "Vector" = betterproto.message_field(8)
