# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtAvatarStandUpNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class EvtAvatarStandUpNotify(betterproto.Message):
    """
    CmdId: 356 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    chair_id: int = betterproto.uint64_field(11)
    perform_id: int = betterproto.int32_field(6)
    direction: int = betterproto.int32_field(1)
    entity_id: int = betterproto.uint32_field(9)
