# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtBulletMoveNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ForwardType import *
from .Vector import *


@dataclass
class EvtBulletMoveNotify(betterproto.Message):
    """
    CmdId: 365 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    forward_type: "ForwardType" = betterproto.enum_field(14)
    cur_pos: "Vector" = betterproto.message_field(1)
    entity_id: int = betterproto.uint32_field(11)
