# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtCombatForceSetPosInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class EvtCombatForceSetPosInfo(betterproto.Message):
    ice_id: int = betterproto.uint32_field(9)
    collider_entity_id: int = betterproto.uint32_field(10)
    entity_id: int = betterproto.uint32_field(6)
    target_pos: "Vector" = betterproto.message_field(1)
