# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtCombatSteerMotionInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class EvtCombatSteerMotionInfo(betterproto.Message):
    pos: "Vector" = betterproto.message_field(12)
    velocity: "Vector" = betterproto.message_field(10)
    entity_id: int = betterproto.uint32_field(4)
    face_dir: "Vector" = betterproto.message_field(1)
