# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtEntityStartDieEndNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ForwardType import *


@dataclass
class EvtEntityStartDieEndNotify(betterproto.Message):
    """
    CmdId: 381 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    immediately: bool = betterproto.bool_field(15)
    die_state_flag: int = betterproto.uint32_field(12)
    entity_id: int = betterproto.uint32_field(8)
    forward_type: "ForwardType" = betterproto.enum_field(11)
