# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtFaceToDirNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .EvtFaceToDirInfo import *
from .ForwardType import *


@dataclass
class EvtFaceToDirNotify(betterproto.Message):
    """
    CmdId: 390 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    forward_type: "ForwardType" = betterproto.enum_field(13)
    evt_face_to_dir_info: "EvtFaceToDirInfo" = betterproto.message_field(5)
