# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtFaceToDirInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class EvtFaceToDirInfo(betterproto.Message):
    entity_id: int = betterproto.uint32_field(12)
    face_dir: "Vector" = betterproto.message_field(14)
