# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtMotionInfoDuringSteerAttack.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class EvtMotionInfoDuringSteerAttack(betterproto.Message):
    face_dir: "Vector" = betterproto.message_field(4)
    velocity: "Vector" = betterproto.message_field(3)
    pos: "Vector" = betterproto.message_field(1)
    entity_id: int = betterproto.uint32_field(6)
