# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtMonsterDoBlink.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class EvtMonsterDoBlink(betterproto.Message):
    target_rot: "Vector" = betterproto.message_field(3)
    target_pos: "Vector" = betterproto.message_field(7)
    entity_id: int = betterproto.uint32_field(2)
