# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtRushMoveInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class EvtRushMoveInfo(betterproto.Message):
    state_name_hash: int = betterproto.int32_field(11)
    rush_to_pos: "Vector" = betterproto.message_field(9)
    rush_attack_target_pos: "Vector" = betterproto.message_field(8)
    entity_id: int = betterproto.uint32_field(4)
    time_range: float = betterproto.float_field(15)
    velocity: "Vector" = betterproto.message_field(6)
    pos: "Vector" = betterproto.message_field(2)
    face_angle_compact: int = betterproto.int32_field(10)
