# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: EvtRushMoveNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .EvtRushMoveInfo import *
from .ForwardType import *


@dataclass
class EvtRushMoveNotify(betterproto.Message):
    """
    CmdId: 375 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    forward_type: "ForwardType" = betterproto.enum_field(1)
    evt_rush_move_info: "EvtRushMoveInfo" = betterproto.message_field(15)
