# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ExecuteGroupTriggerRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ExecuteGroupTriggerRsp(betterproto.Message):
    """
    CmdId: 300 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(13)
