# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ExitSceneWeatherAreaNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ExitSceneWeatherAreaNotify(betterproto.Message):
    """
    CmdId: 242 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    weather_gadget_id: int = betterproto.uint32_field(2)
