# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ExpeditionStartRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ExpeditionStartRsp(betterproto.Message):
    """
    CmdId: 2135 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    assist_uid: int = betterproto.uint32_field(1)
    path_id: int = betterproto.uint32_field(7)
    avatar_id_list: List[int] = betterproto.uint32_field(4)
    retcode: int = betterproto.int32_field(12)
    assist_avatar_id: int = betterproto.uint32_field(2)
