# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ExpeditionChallengeEnterRegionNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ExpeditionChallengeEnterRegionNotify(betterproto.Message):
    """
    CmdId: 2154 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    id: int = betterproto.uint32_field(5)
    is_puzzle_finished: bool = betterproto.bool_field(10)
