# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ExpeditionRecallReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ExpeditionRecallReq(betterproto.Message):
    """
    CmdId: 2131 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    path_id: int = betterproto.uint32_field(13)
