# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ExpeditionPathInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ExpeditionState import *


@dataclass
class ExpeditionPathInfo(betterproto.Message):
    mark_id: int = betterproto.uint32_field(12)
    start_time: int = betterproto.uint32_field(9)
    assist_avatar_id: int = betterproto.uint32_field(7)
    bonus_probability: float = betterproto.float_field(4)
    state: "ExpeditionState" = betterproto.enum_field(15)
    avatar_id_list: List[int] = betterproto.uint32_field(2)
    assist_costume_id: int = betterproto.uint32_field(5)
    path_id: int = betterproto.uint32_field(8)
    challenge_id: int = betterproto.uint32_field(11)
    assist_uid: int = betterproto.uint32_field(10)
