# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FeatureBlockInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FeatureBlockInfo(betterproto.Message):
    feature_type: int = betterproto.uint32_field(1)
    end_time: int = betterproto.uint32_field(2)
