# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FindHilichurlAcceptQuestNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FindHilichurlAcceptQuestNotify(betterproto.Message):
    """
    CmdId: 8659 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
