# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FinishedParentQuestUpdateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ParentQuest import *


@dataclass
class FinishedParentQuestUpdateNotify(betterproto.Message):
    """
    CmdId: 407 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    parent_quest_list: List["ParentQuest"] = betterproto.message_field(9)
