# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FinishMainCoopRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FinishMainCoopRsp(betterproto.Message):
    """
    CmdId: 1981 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    id: int = betterproto.uint32_field(2)
    ending_save_point_id: int = betterproto.uint32_field(6)
    retcode: int = betterproto.int32_field(4)
