# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FishEscapeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .FishEscapeReason import *
from .Vector import *


@dataclass
class FishEscapeNotify(betterproto.Message):
    """
    CmdId: 5822 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    reason: "FishEscapeReason" = betterproto.enum_field(4)
    pos: "Vector" = betterproto.message_field(7)
    uid: int = betterproto.uint32_field(14)
    fish_id_list: List[int] = betterproto.uint32_field(6)
