# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FishCastRodRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FishCastRodRsp(betterproto.Message):
    """
    CmdId: 5831 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(12)
