# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FishPoolDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FishPoolDataNotify(betterproto.Message):
    """
    CmdId: 5848 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    entity_id: int = betterproto.uint32_field(6)
    today_fish_num: int = betterproto.uint32_field(2)
