# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FishBattleEndReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .FishBattleResult import *


@dataclass
class FishBattleEndReq(betterproto.Message):
    """
    CmdId: 5841 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    max_bonus_time: int = betterproto.uint32_field(3)
    battle_result: "FishBattleResult" = betterproto.enum_field(10)
    is_always_bonus: bool = betterproto.bool_field(11)
