# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FishBattleBeginReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FishBattleBeginReq(betterproto.Message):
    """
    CmdId: 5820 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
