# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FishInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FishInfo(betterproto.Message):
    free_count: int = betterproto.uint32_field(11)
    into_bag_count: int = betterproto.uint32_field(12)
