# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FishingGallerySettleNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .FishingGallerySettleInfo import *


@dataclass
class FishingGallerySettleNotify(betterproto.Message):
    """
    CmdId: 8780 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    gallery_id: int = betterproto.uint32_field(6)
    level_id: int = betterproto.uint32_field(15)
    settle_info: "FishingGallerySettleInfo" = betterproto.message_field(13)
