# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FishBiteReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FishBiteReq(betterproto.Message):
    """
    CmdId: 5844 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
