# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FishAttractNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Vector import *


@dataclass
class FishAttractNotify(betterproto.Message):
    """
    CmdId: 5837 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    fish_id_list: List[int] = betterproto.uint32_field(3)
    pos: "Vector" = betterproto.message_field(9)
    uid: int = betterproto.uint32_field(2)
