# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FleurFairPlayerStatInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ProfilePicture import *


@dataclass
class FleurFairPlayerStatInfo(betterproto.Message):
    online_id: str = betterproto.string_field(11)
    uid: int = betterproto.uint32_field(8)
    profile_picture: "ProfilePicture" = betterproto.message_field(1)
    stat_id: int = betterproto.uint32_field(3)
    head_image: int = betterproto.uint32_field(6)
    nick_name: str = betterproto.string_field(15)
    param: int = betterproto.int32_field(5)
