# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FleurFairMusicGameStartReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FleurFairMusicGameStartReq(betterproto.Message):
    """
    CmdId: 2167 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    music_basic_id: int = betterproto.uint32_field(2)
