# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FleurFairBalloonInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FleurFairBalloonInfo(betterproto.Message):
    best_score: int = betterproto.uint32_field(4)
