# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FleurFairDungeonSectionInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FleurFairDungeonSectionInfo(betterproto.Message):
    section_id: int = betterproto.uint32_field(10)
    open_time: int = betterproto.uint32_field(13)
    is_open: bool = betterproto.bool_field(1)
