# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FleurFairReplayMiniGameReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FleurFairReplayMiniGameReq(betterproto.Message):
    """
    CmdId: 2181 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    minigame_id: int = betterproto.uint32_field(5)
