# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FleurFairBuffEnergyNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FleurFairBuffEnergyNotify(betterproto.Message):
    """
    CmdId: 5324 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    energy: int = betterproto.uint32_field(4)
