# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ForceAddPlayerFriendRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .FriendBrief import *


@dataclass
class ForceAddPlayerFriendRsp(betterproto.Message):
    """
    CmdId: 4100 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(5)
    target_friend_brief: "FriendBrief" = betterproto.message_field(2)
    target_uid: int = betterproto.uint32_field(9)
