# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ForgeQueueData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ForgeQueueData(betterproto.Message):
    finish_count: int = betterproto.uint32_field(13)
    total_finish_timestamp: int = betterproto.uint32_field(14)
    avatar_id: int = betterproto.uint32_field(7)
    queue_id: int = betterproto.uint32_field(1)
    unfinish_count: int = betterproto.uint32_field(10)
    next_finish_timestamp: int = betterproto.uint32_field(11)
    forge_id: int = betterproto.uint32_field(15)
