# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ForgeQueueManipulateReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ForgeQueueManipulateType import *


@dataclass
class ForgeQueueManipulateReq(betterproto.Message):
    """
    CmdId: 624 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    forge_queue_id: int = betterproto.uint32_field(5)
    manipulate_type: "ForgeQueueManipulateType" = betterproto.enum_field(13)
