# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ForgeQueueDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .ForgeQueueData import *


@dataclass
class ForgeQueueDataNotify(betterproto.Message):
    """
    CmdId: 676 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    forge_queue_map: Dict[int, "ForgeQueueData"] = betterproto.map_field(
        7, betterproto.TYPE_UINT32, betterproto.TYPE_MESSAGE
    )
    removed_forge_queue_list: List[int] = betterproto.uint32_field(6)
