# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ForgeStartRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ForgeStartRsp(betterproto.Message):
    """
    CmdId: 691 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(8)
