# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ForwardType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class ForwardType(betterproto.Enum):
    FORWARD_TYPE_LOCAL = 0
    FORWARD_TYPE_TO_ALL = 1
    FORWARD_TYPE_TO_ALL_EXCEPT_CUR = 2
    FORWARD_TYPE_TO_HOST = 3
    FORWARD_TYPE_TO_ALL_GUEST = 4
    FORWARD_TYPE_TO_PEER = 5
    FORWARD_TYPE_TO_PEERS = 6
    FORWARD_TYPE_ONLY_SERVER = 7
    FORWARD_TYPE_TO_ALL_EXIST_EXCEPT_CUR = 8
