# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FoundationRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .FoundationOpType import *


@dataclass
class FoundationRsp(betterproto.Message):
    """
    CmdId: 882 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    op_type: "FoundationOpType" = betterproto.enum_field(13)
    gadget_entity_id: int = betterproto.uint32_field(10)
    building_id: int = betterproto.uint32_field(11)
    point_config_id: int = betterproto.uint32_field(12)
    retcode: int = betterproto.int32_field(7)
