# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FoundationStatus.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class FoundationStatus(betterproto.Enum):
    FOUNDATION_STATUS_NONE = 0
    FOUNDATION_STATUS_INIT = 1
    FOUNDATION_STATUS_BUILDING = 2
    FOUNDATION_STATUS_BUILT = 3
