# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FoundationNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .FoundationInfo import *


@dataclass
class FoundationNotify(betterproto.Message):
    """
    CmdId: 847 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    info: "FoundationInfo" = betterproto.message_field(7)
    gadget_entity_id: int = betterproto.uint32_field(9)
