# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FriendInfoChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FriendInfoChangeNotify(betterproto.Message):
    """
    CmdId: 4032 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    uid: int = betterproto.uint32_field(1)
    online_id: str = betterproto.string_field(9)
