# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FurnitureMakeBeHelpedNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .FurnitureMakeBeHelpedData import *
from .FurnitureMakeSlot import *


@dataclass
class FurnitureMakeBeHelpedNotify(betterproto.Message):
    """
    CmdId: 4578 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    furniture_make_slot: "FurnitureMakeSlot" = betterproto.message_field(7)
    furniture_make_helped_data: "FurnitureMakeBeHelpedData" = betterproto.message_field(
        2
    )
