# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FurnitureMakeBeHelpedData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ProfilePicture import *


@dataclass
class FurnitureMakeBeHelpedData(betterproto.Message):
    time: float = betterproto.fixed32_field(12)
    icon: int = betterproto.uint32_field(11)
    uid: int = betterproto.uint32_field(7)
    player_name: str = betterproto.string_field(10)
    profile_picture: "ProfilePicture" = betterproto.message_field(1)
