# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FurnitureMakeStartRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .FurnitureMakeSlot import *


@dataclass
class FurnitureMakeStartRsp(betterproto.Message):
    """
    CmdId: 4729 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    furniture_make_slot: "FurnitureMakeSlot" = betterproto.message_field(5)
    retcode: int = betterproto.int32_field(8)
