# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: FurnitureMakeHelpData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class FurnitureMakeHelpData(betterproto.Message):
    times: int = betterproto.uint32_field(2)
    uid: int = betterproto.uint32_field(13)
