# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Furniture.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Furniture(betterproto.Message):
    count: int = betterproto.uint32_field(1)
