# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GachaItem.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .GachaTransferItem import *
from .ItemParam import *


@dataclass
class GachaItem(betterproto.Message):
    gacha_item_: "ItemParam" = betterproto.message_field(7)
    is_gacha_item_new: bool = betterproto.bool_field(6)
    is_flash_card: bool = betterproto.bool_field(8)
    token_item_list: List["ItemParam"] = betterproto.message_field(9)
    transfer_items: List["GachaTransferItem"] = betterproto.message_field(12)
