# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GachaSimpleInfoNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GachaSimpleInfoNotify(betterproto.Message):
    """
    CmdId: 1590 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_new: bool = betterproto.bool_field(5)
