# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GachaWishRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GachaWishRsp(betterproto.Message):
    """
    CmdId: 1521 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    gacha_type: int = betterproto.uint32_field(8)
    gacha_schedule_id: int = betterproto.uint32_field(7)
    wish_max_progress: int = betterproto.uint32_field(2)
    wish_progress: int = betterproto.uint32_field(5)
    wish_item_id: int = betterproto.uint32_field(3)
    retcode: int = betterproto.int32_field(14)
