# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GachaWishReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GachaWishReq(betterproto.Message):
    """
    CmdId: 1507 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    gacha_schedule_id: int = betterproto.uint32_field(14)
    gacha_type: int = betterproto.uint32_field(13)
    item_id: int = betterproto.uint32_field(4)
