# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GadgetInteractRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .InterOpType import *
from .InteractType import *


@dataclass
class GadgetInteractRsp(betterproto.Message):
    """
    CmdId: 898 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    gadget_entity_id: int = betterproto.uint32_field(10)
    interact_type: "InteractType" = betterproto.enum_field(2)
    op_type: "InterOpType" = betterproto.enum_field(3)
    retcode: int = betterproto.int32_field(7)
    gadget_id: int = betterproto.uint32_field(15)
