# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GadgetGeneralRewardInfoNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .GadgetGeneralRewardInfo import *


@dataclass
class GadgetGeneralRewardInfoNotify(betterproto.Message):
    """
    CmdId: 848 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    entity_id: int = betterproto.uint32_field(13)
    general_reward_info: "GadgetGeneralRewardInfo" = betterproto.message_field(9)
