# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GadgetStateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GadgetStateNotify(betterproto.Message):
    """
    CmdId: 812 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    gadget_entity_id: int = betterproto.uint32_field(5)
    gadget_state: int = betterproto.uint32_field(3)
    is_enable_interact: bool = betterproto.bool_field(11)
