# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GadgetPlayDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GadgetPlayDataNotify(betterproto.Message):
    """
    CmdId: 831 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    play_type: int = betterproto.uint32_field(12)
    progress: int = betterproto.uint32_field(9)
    entity_id: int = betterproto.uint32_field(6)
