# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GadgetCustomTreeInfoNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .CustomGadgetTreeInfo import *


@dataclass
class GadgetCustomTreeInfoNotify(betterproto.Message):
    """
    CmdId: 850 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    custom_gadget_tree_info: "CustomGadgetTreeInfo" = betterproto.message_field(5)
    gadget_entity_id: int = betterproto.uint32_field(12)
