# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GearActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2800_BPOJIIDEADD import *
from .Unk2800_JIPMJPAKIKE import *


@dataclass
class GearActivityDetailInfo(betterproto.Message):
    unk2800__g_b_a_p_c_b_p_m_h_n_j: List[
        "Unk2800_BPOJIIDEADD"
    ] = betterproto.message_field(14)
    unk2800__i_h_e_h_g_o_b_c_i_n_c: "Unk2800_JIPMJPAKIKE" = betterproto.message_field(8)
