# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetAllUnlockNameCardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class GetAllUnlockNameCardRsp(betterproto.Message):
    """
    CmdId: 4094 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(4)
    name_card_list: List[int] = betterproto.uint32_field(14)
