# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetActivityShopSheetInfoRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ActivityShopSheetInfo import *


@dataclass
class GetActivityShopSheetInfoRsp(betterproto.Message):
    """
    CmdId: 790 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    sheet_info_list: List["ActivityShopSheetInfo"] = betterproto.message_field(6)
    shop_type: int = betterproto.uint32_field(8)
    retcode: int = betterproto.int32_field(13)
