# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetAllSceneGalleryInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetAllSceneGalleryInfoReq(betterproto.Message):
    """
    CmdId: 5503 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
