# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetBargainDataReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetBargainDataReq(betterproto.Message):
    """
    CmdId: 488 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    bargain_id: int = betterproto.uint32_field(12)
