# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetCityReputationMapInfoRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class GetCityReputationMapInfoRsp(betterproto.Message):
    """
    CmdId: 2848 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(11)
    is_new_hunting: bool = betterproto.bool_field(10)
    is_new_request: bool = betterproto.bool_field(2)
    unlock_hunting_city_list: List[int] = betterproto.uint32_field(9)
    reward_city_list: List[int] = betterproto.uint32_field(3)
