# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetCityReputationMapInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetCityReputationMapInfoReq(betterproto.Message):
    """
    CmdId: 2875 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
