# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetCompoundDataReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetCompoundDataReq(betterproto.Message):
    """
    CmdId: 141 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
