# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetCompoundDataRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .CompoundQueueData import *


@dataclass
class GetCompoundDataRsp(betterproto.Message):
    """
    CmdId: 149 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(3)
    unlock_compound_list: List[int] = betterproto.uint32_field(11)
    compound_que_data_list: List["CompoundQueueData"] = betterproto.message_field(7)
