# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetDungeonEntryExploreConditionRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .DungeonEntryCond import *


@dataclass
class GetDungeonEntryExploreConditionRsp(betterproto.Message):
    """
    CmdId: 3269 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    dungeon_entry_cond: "DungeonEntryCond" = betterproto.message_field(5)
    retcode: int = betterproto.int32_field(3)
