# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetDungeonEntryExploreConditionReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetDungeonEntryExploreConditionReq(betterproto.Message):
    """
    CmdId: 3165 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    scene_id: int = betterproto.uint32_field(6)
    dungeon_entry_config_id: int = betterproto.uint32_field(2)
    dungeon_entry_scene_point_id: int = betterproto.uint32_field(4)
