# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetExpeditionAssistInfoListReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetExpeditionAssistInfoListReq(betterproto.Message):
    """
    CmdId: 2150 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
