# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetFurnitureCurModuleArrangeCountReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetFurnitureCurModuleArrangeCountReq(betterproto.Message):
    """
    CmdId: 4711 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
