# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetFriendShowNameCardInfoRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class GetFriendShowNameCardInfoRsp(betterproto.Message):
    """
    CmdId: 4029 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(15)
    uid: int = betterproto.uint32_field(7)
    show_name_card_id_list: List[int] = betterproto.uint32_field(10)
