# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetFriendShowNameCardInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetFriendShowNameCardInfoReq(betterproto.Message):
    """
    CmdId: 4061 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    uid: int = betterproto.uint32_field(3)
