# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetHuntingOfferRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HuntingPair import *


@dataclass
class GetHuntingOfferRewardRsp(betterproto.Message):
    """
    CmdId: 4331 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    hunting_pair: "HuntingPair" = betterproto.message_field(14)
    city_id: int = betterproto.uint32_field(3)
    retcode: int = betterproto.int32_field(12)
