# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetHuntingOfferRewardReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HuntingPair import *


@dataclass
class GetHuntingOfferRewardReq(betterproto.Message):
    """
    CmdId: 4302 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    city_id: int = betterproto.uint32_field(6)
    hunting_pair: "HuntingPair" = betterproto.message_field(4)
