# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetInvestigationMonsterRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .InvestigationMonster import *


@dataclass
class GetInvestigationMonsterRsp(betterproto.Message):
    """
    CmdId: 1910 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    monster_list: List["InvestigationMonster"] = betterproto.message_field(10)
    retcode: int = betterproto.int32_field(1)
    unk2700__d_e_m_f_d_h_n_f_b_b_j: bool = betterproto.bool_field(2)
