# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetMapMarkTipsRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MapMarkTipsInfo import *


@dataclass
class GetMapMarkTipsRsp(betterproto.Message):
    """
    CmdId: 3327 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(7)
    mark_tips_list: List["MapMarkTipsInfo"] = betterproto.message_field(11)
