# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetMapMarkTipsReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetMapMarkTipsReq(betterproto.Message):
    """
    CmdId: 3463 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
