# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetMapAreaRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MapAreaInfo import *


@dataclass
class GetMapAreaRsp(betterproto.Message):
    """
    CmdId: 3328 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(14)
    map_area_info_list: List["MapAreaInfo"] = betterproto.message_field(9)
