# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetNextResourceInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetNextResourceInfoReq(betterproto.Message):
    """
    CmdId: 192 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
