# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetNextResourceInfoRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ResVersionConfig import *


@dataclass
class GetNextResourceInfoRsp(betterproto.Message):
    """
    CmdId: 120 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    next_resource_url: str = betterproto.string_field(14)
    next_res_version_config: "ResVersionConfig" = betterproto.message_field(2)
    retcode: int = betterproto.int32_field(12)
