# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetOnlinePlayerInfoRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .OnlinePlayerInfo import *


@dataclass
class GetOnlinePlayerInfoRsp(betterproto.Message):
    """CmdId: 47 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true"""

    retcode: int = betterproto.int32_field(11)
    target_uid: int = betterproto.uint32_field(7)
    param: int = betterproto.uint32_field(4)
    target_player_info: "OnlinePlayerInfo" = betterproto.message_field(14)
