# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetOpActivityInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetOpActivityInfoReq(betterproto.Message):
    """
    CmdId: 5172 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
