# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetOnlinePlayerListRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .OnlinePlayerInfo import *


@dataclass
class GetOnlinePlayerListRsp(betterproto.Message):
    """CmdId: 73 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true"""

    retcode: int = betterproto.int32_field(7)
    param: int = betterproto.uint32_field(11)
    player_info_list: List["OnlinePlayerInfo"] = betterproto.message_field(5)
