# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetPlayerSocialDetailReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetPlayerSocialDetailReq(betterproto.Message):
    """
    CmdId: 4073 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    uid: int = betterproto.uint32_field(9)
