# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetPlayerFriendListRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .FriendBrief import *


@dataclass
class GetPlayerFriendListRsp(betterproto.Message):
    """
    CmdId: 4098 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(9)
    ask_friend_list: List["FriendBrief"] = betterproto.message_field(8)
    friend_list: List["FriendBrief"] = betterproto.message_field(14)
