# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetPlayerTokenRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class GetPlayerTokenRsp(betterproto.Message):
    """
    CmdId: 198 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    birthday: str = betterproto.string_field(937)
    retcode: int = betterproto.int32_field(2)
    security_cmd_buffer: bytes = betterproto.bytes_field(6)
    secret_key_seed: int = betterproto.uint64_field(13)
    country_code: str = betterproto.string_field(2013)
    extra_bin_data: bytes = betterproto.bytes_field(3)
    secret_key: str = betterproto.string_field(15)
    unk2700__n_o_j_p_e_h_i_b_d_j_h: int = betterproto.uint32_field(1561)
    black_uid_end_time: int = betterproto.uint32_field(14)
    tag: int = betterproto.uint32_field(1635)
    token: str = betterproto.string_field(11)
    gm_uid: int = betterproto.uint32_field(10)
    channel_id: int = betterproto.uint32_field(896)
    psn_id: str = betterproto.string_field(1811)
    client_ip_str: str = betterproto.string_field(860)
    msg: str = betterproto.string_field(7)
    account_type: int = betterproto.uint32_field(5)
    sub_channel_id: int = betterproto.uint32_field(1802)
    unk2700__f_l_b_k_p_c_p_g_p_d_h: bool = betterproto.bool_field(2028)
    encrypted_seed: str = betterproto.string_field(1493)
    is_proficient_player: bool = betterproto.bool_field(9)
    unk2800__b_p_j_o_b_l_n_c_b_e_i: int = betterproto.uint32_field(1172)
    uid: int = betterproto.uint32_field(1)
    account_uid: str = betterproto.string_field(12)
    is_guest: bool = betterproto.bool_field(4)
    client_version_random_key: str = betterproto.string_field(1529)
    unk2800__n_n_b_f_c_e_a_o_e_p_b: List[int] = betterproto.uint32_field(1640)
    platform_type: int = betterproto.uint32_field(8)
    reg_platform: int = betterproto.uint32_field(1112)
    is_login_white_list: bool = betterproto.bool_field(573)
    seed_signature: str = betterproto.string_field(1140)
