# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetPlayerSocialDetailRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .SocialDetail import *


@dataclass
class GetPlayerSocialDetailRsp(betterproto.Message):
    """
    CmdId: 4099 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    detail_data: "SocialDetail" = betterproto.message_field(12)
    retcode: int = betterproto.int32_field(1)
