# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetReunionPrivilegeInfoRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ReunionPrivilegeInfo import *


@dataclass
class GetReunionPrivilegeInfoRsp(betterproto.Message):
    """
    CmdId: 5087 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(3)
    privilege_info: "ReunionPrivilegeInfo" = betterproto.message_field(1)
