# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetReunionMissionInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetReunionMissionInfoReq(betterproto.Message):
    """
    CmdId: 5094 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    mission_id: int = betterproto.uint32_field(14)
