# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetShopmallDataReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetShopmallDataReq(betterproto.Message):
    """
    CmdId: 707 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
