# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetSceneAreaRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .CityInfo import *


@dataclass
class GetSceneAreaRsp(betterproto.Message):
    """
    CmdId: 204 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(7)
    city_info_list: List["CityInfo"] = betterproto.message_field(13)
    scene_id: int = betterproto.uint32_field(15)
    area_id_list: List[int] = betterproto.uint32_field(9)
