# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetScenePerformanceReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GetScenePerformanceReq(betterproto.Message):
    """
    CmdId: 3419 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
