# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetShopRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Shop import *


@dataclass
class GetShopRsp(betterproto.Message):
    """
    CmdId: 798 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    shop: "Shop" = betterproto.message_field(11)
    retcode: int = betterproto.int32_field(2)
