# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GetScenePointRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class GetScenePointRsp(betterproto.Message):
    """
    CmdId: 281 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    not_explored_dungeon_entry_list: List[int] = betterproto.uint32_field(11)
    to_be_explore_dungeon_entry_list: List[int] = betterproto.uint32_field(15)
    locked_point_list: List[int] = betterproto.uint32_field(2)
    unhide_point_list: List[int] = betterproto.uint32_field(5)
    retcode: int = betterproto.int32_field(9)
    belong_uid: int = betterproto.uint32_field(12)
    unlocked_point_list: List[int] = betterproto.uint32_field(13)
    unlock_area_list: List[int] = betterproto.uint32_field(1)
    hide_point_list: List[int] = betterproto.uint32_field(4)
    scene_id: int = betterproto.uint32_field(14)
    not_interact_dungeon_entry_list: List[int] = betterproto.uint32_field(6)
    group_unlimit_point_list: List[int] = betterproto.uint32_field(10)
