# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GivingRecordNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .GivingRecord import *


@dataclass
class GivingRecordNotify(betterproto.Message):
    """
    CmdId: 116 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    giving_record_list: List["GivingRecord"] = betterproto.message_field(14)
