# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GMShowObstacleReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GMShowObstacleReq(betterproto.Message):
    """
    CmdId: 2361 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
