# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GMShowNavMeshRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .PBNavMeshTile import *


@dataclass
class GMShowNavMeshRsp(betterproto.Message):
    """
    CmdId: 2400 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    tiles: List["PBNavMeshTile"] = betterproto.message_field(11)
    retcode: int = betterproto.int32_field(5)
