# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GroupLinkDeleteNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GroupLinkDeleteNotify(betterproto.Message):
    """
    CmdId: 5775 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    bundle_id: int = betterproto.uint32_field(12)
