# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: GroupUnloadNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class GroupUnloadNotify(betterproto.Message):
    """
    CmdId: 3344 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    group_list: List[int] = betterproto.uint32_field(10)
