# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HashedString.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HashedString(betterproto.Message):
    hash: int = betterproto.uint32_field(1)
