# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HideAndSeekSelectAvatarRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HideAndSeekSelectAvatarRsp(betterproto.Message):
    """
    CmdId: 5367 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(2)
    avatar_id: int = betterproto.uint32_field(3)
