# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HideAndSeekSelectSkillRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class HideAndSeekSelectSkillRsp(betterproto.Message):
    """
    CmdId: 8088 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(4)
    skill_list: List[int] = betterproto.uint32_field(12)
