# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HitTreeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class HitTreeNotify(betterproto.Message):
    """
    CmdId: 3019 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    tree_type: int = betterproto.uint32_field(11)
    tree_pos: "Vector" = betterproto.message_field(2)
    drop_pos: "Vector" = betterproto.message_field(8)
