# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeUpdateFishFarmingInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HomeFishFarmingInfo import *


@dataclass
class HomeUpdateFishFarmingInfoReq(betterproto.Message):
    """
    CmdId: 4544 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    fish_farming_info: "HomeFishFarmingInfo" = betterproto.message_field(5)
