# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeVerifyBlockData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeVerifyBlockData(betterproto.Message):
    block_id: int = betterproto.uint32_field(10)
    furnitures: int = betterproto.uint32_field(9)
