# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeAvatarSummonEventRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeAvatarSummonEventRsp(betterproto.Message):
    """
    CmdId: 4817 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    event_id: int = betterproto.uint32_field(11)
    retcode: int = betterproto.int32_field(14)
