# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeResourceTakeHomeCoinRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HomeResource import *


@dataclass
class HomeResourceTakeHomeCoinRsp(betterproto.Message):
    """
    CmdId: 4541 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    home_coin: "HomeResource" = betterproto.message_field(7)
    retcode: int = betterproto.int32_field(10)
