# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeChangeModuleRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeChangeModuleRsp(betterproto.Message):
    """
    CmdId: 4596 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(3)
    target_module_id: int = betterproto.uint32_field(2)
