# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeMarkPointNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .HomeMarkPointSceneData import *


@dataclass
class HomeMarkPointNotify(betterproto.Message):
    """
    CmdId: 4474 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    mark_point_data_list: List["HomeMarkPointSceneData"] = betterproto.message_field(12)
