# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeLimitedShopInfoRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HomeLimitedShopInfo import *


@dataclass
class HomeLimitedShopInfoRsp(betterproto.Message):
    """
    CmdId: 4796 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    shop_info: "HomeLimitedShopInfo" = betterproto.message_field(10)
    retcode: int = betterproto.int32_field(7)
