# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeResourceTakeHomeCoinReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeResourceTakeHomeCoinReq(betterproto.Message):
    """
    CmdId: 4479 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
