# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeSceneJumpReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeSceneJumpReq(betterproto.Message):
    """
    CmdId: 4528 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_enter_room_scene: bool = betterproto.bool_field(9)
