# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeAvatarRewardEventInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeAvatarRewardEventInfo(betterproto.Message):
    avatar_id: int = betterproto.uint32_field(1)
    guid: int = betterproto.uint32_field(12)
    event_id: int = betterproto.uint32_field(2)
    suite_id: int = betterproto.uint32_field(14)
    random_position: int = betterproto.uint32_field(9)
