# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeLimitedShopInfoChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .HomeLimitedShopGoods import *


@dataclass
class HomeLimitedShopInfoChangeNotify(betterproto.Message):
    """
    CmdId: 4790 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    goods_list: List["HomeLimitedShopGoods"] = betterproto.message_field(5)
