# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeAvatarCostumeChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeAvatarCostumeChangeNotify(betterproto.Message):
    """
    CmdId: 4748 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    costume_id: int = betterproto.uint32_field(4)
    avatar_id: int = betterproto.uint32_field(10)
