# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeLimitedShopInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class HomeLimitedShopInfo(betterproto.Message):
    next_close_time: float = betterproto.fixed32_field(9)
    next_guest_open_time: float = betterproto.fixed32_field(11)
    djinn_rot: "Vector" = betterproto.message_field(7)
    uid: int = betterproto.uint32_field(4)
    next_open_time: float = betterproto.fixed32_field(6)
    djinn_pos: "Vector" = betterproto.message_field(2)
