# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeAvatarRewardEventGetReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeAvatarRewardEventGetReq(betterproto.Message):
    """
    CmdId: 4551 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    event_id: int = betterproto.uint32_field(9)
    avatar_id: int = betterproto.uint32_field(7)
