# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeLimitedShopInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeLimitedShopInfoReq(betterproto.Message):
    """
    CmdId: 4825 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
