# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeNpcData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class HomeNpcData(betterproto.Message):
    avatar_id: int = betterproto.uint32_field(14)
    spawn_pos: "Vector" = betterproto.message_field(15)
    costume_id: int = betterproto.uint32_field(3)
    spawn_rot: "Vector" = betterproto.message_field(13)
