# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeLimitedShop.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .HomeLimitedShopGoods import *


@dataclass
class HomeLimitedShop(betterproto.Message):
    goods_list: List["HomeLimitedShopGoods"] = betterproto.message_field(8)
