# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeGetBasicInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeGetBasicInfoReq(betterproto.Message):
    """
    CmdId: 4655 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
