# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeAvatarSummonAllEventNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .HomeAvatarSummonEventInfo import *


@dataclass
class HomeAvatarSummonAllEventNotify(betterproto.Message):
    """
    CmdId: 4808 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    summon_event_list: List["HomeAvatarSummonEventInfo"] = betterproto.message_field(1)
