# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeSceneArrangementMuipData.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .HomeBlockArrangementMuipData import *


@dataclass
class HomeSceneArrangementMuipData(betterproto.Message):
    module_id: int = betterproto.uint32_field(1)
    scene_id: int = betterproto.uint32_field(2)
    is_room: bool = betterproto.bool_field(3)
    block_data_list: List["HomeBlockArrangementMuipData"] = betterproto.message_field(4)
