# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeBlockFieldData.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .HomeBlockSubFieldData import *
from .Vector import *


@dataclass
class HomeBlockFieldData(betterproto.Message):
    rot: "Vector" = betterproto.message_field(15)
    pos: "Vector" = betterproto.message_field(4)
    guid: int = betterproto.uint32_field(9)
    furniture_id: int = betterproto.uint32_field(1)
    sub_field_list: List["HomeBlockSubFieldData"] = betterproto.message_field(7)
