# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeFishFarmingInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class HomeFishFarmingInfo(betterproto.Message):
    fish_id_list: List[int] = betterproto.uint32_field(11)
    fishpond_guid: int = betterproto.uint32_field(14)
