# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeBasicInfoNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HomeBasicInfo import *


@dataclass
class HomeBasicInfoNotify(betterproto.Message):
    """
    CmdId: 4885 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    basic_info: "HomeBasicInfo" = betterproto.message_field(15)
