# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HomeModuleUnlockNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HomeModuleUnlockNotify(betterproto.Message):
    """
    CmdId: 4560 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    module_id: int = betterproto.uint32_field(8)
