# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HuntingRevealClueNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HuntingPair import *
from .Vector import *


@dataclass
class HuntingRevealClueNotify(betterproto.Message):
    """
    CmdId: 4322 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    finish_clue_count: int = betterproto.uint32_field(5)
    clue_position: "Vector" = betterproto.message_field(4)
    hunting_pair: "HuntingPair" = betterproto.message_field(12)
    finished_group_id: int = betterproto.uint32_field(7)
