# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HuntingPair.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HuntingPair(betterproto.Message):
    refresh_id: int = betterproto.uint32_field(9)
    monster_config_id: int = betterproto.uint32_field(4)
