# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HuntingRevealFinalNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HuntingPair import *
from .Vector import *


@dataclass
class HuntingRevealFinalNotify(betterproto.Message):
    """
    CmdId: 4344 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    finished_group_id: int = betterproto.uint32_field(5)
    hunting_pair: "HuntingPair" = betterproto.message_field(11)
    final_position: "Vector" = betterproto.message_field(2)
