# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HuntingSuccessNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HuntingPair import *


@dataclass
class HuntingSuccessNotify(betterproto.Message):
    """
    CmdId: 4349 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    hunting_pair: "HuntingPair" = betterproto.message_field(4)
