# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: HuntingOngoingNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HuntingPair import *
from .Vector import *


@dataclass
class HuntingOngoingNotify(betterproto.Message):
    """
    CmdId: 4345 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    hunting_pair: "HuntingPair" = betterproto.message_field(15)
    is_started: bool = betterproto.bool_field(8)
    next_position: "Vector" = betterproto.message_field(3)
    finish_clue_count: int = betterproto.uint32_field(10)
    is_final: bool = betterproto.bool_field(14)
    fail_time: int = betterproto.uint32_field(7)
