# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InBattleMechanicusCardChallengeState.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class InBattleMechanicusCardChallengeState(betterproto.Enum):
    IN_BATTLE_MECHANICUS_CARD_CHALLENGE_STATE_NONE = 0
    IN_BATTLE_MECHANICUS_CARD_CHALLENGE_STATE_ON_GOING = 1
    IN_BATTLE_MECHANICUS_CARD_CHALLENGE_STATE_FAIL = 2
    IN_BATTLE_MECHANICUS_CARD_CHALLENGE_STATE_SUCCESS = 3
