# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InBattleMechanicusSettleNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MultistageSettleWatcherInfo import *


@dataclass
class InBattleMechanicusSettleNotify(betterproto.Message):
    """
    CmdId: 5305 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    group_id: int = betterproto.uint32_field(15)
    scene_time_ms: int = betterproto.uint64_field(11)
    difficulty_percentage: int = betterproto.uint32_field(6)
    total_token: int = betterproto.uint32_field(7)
    watcher_list: List["MultistageSettleWatcherInfo"] = betterproto.message_field(3)
    real_token: int = betterproto.uint32_field(13)
    is_success: bool = betterproto.bool_field(2)
    play_index: int = betterproto.uint32_field(14)
