# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InBattleMechanicusStageType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class InBattleMechanicusStageType(betterproto.Enum):
    IN_BATTLE_MECHANICUS_STAGE_TYPE_NONE = 0
    IN_BATTLE_MECHANICUS_STAGE_TYPE_BUILD = 1
    IN_BATTLE_MECHANICUS_STAGE_TYPE_CARD_FLIP = 2
    IN_BATTLE_MECHANICUS_STAGE_TYPE_KILL = 3
