# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InBattleMechanicusPlayerInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .InBattleMechanicusBuildingInfo import *


@dataclass
class InBattleMechanicusPlayerInfo(betterproto.Message):
    pick_card_id: int = betterproto.uint32_field(5)
    uid: int = betterproto.uint32_field(14)
    building_list: List["InBattleMechanicusBuildingInfo"] = betterproto.message_field(4)
    is_card_confirmed: bool = betterproto.bool_field(13)
    building_points: int = betterproto.uint32_field(3)
