# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InBattleMechanicusPickCardReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class InBattleMechanicusPickCardReq(betterproto.Message):
    """
    CmdId: 5390 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    group_id: int = betterproto.uint32_field(11)
    play_index: int = betterproto.uint32_field(7)
    card_id: int = betterproto.uint32_field(1)
