# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InBattleMechanicusPickCardNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class InBattleMechanicusPickCardNotify(betterproto.Message):
    """
    CmdId: 5399 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    player_uid: int = betterproto.uint32_field(6)
    group_id: int = betterproto.uint32_field(7)
    play_index: int = betterproto.uint32_field(8)
    card_id: int = betterproto.uint32_field(10)
