# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InBattleMechanicusCardResultNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .InBattleMechanicusCardInfo import *


@dataclass
class InBattleMechanicusCardResultNotify(betterproto.Message):
    """
    CmdId: 5397 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    wait_seconds: int = betterproto.uint32_field(6)
    group_id: int = betterproto.uint32_field(2)
    card_list: List["InBattleMechanicusCardInfo"] = betterproto.message_field(9)
    wait_begin_time_us: int = betterproto.uint64_field(7)
    player_confirmed_card_map: Dict[int, int] = betterproto.map_field(
        12, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    play_index: int = betterproto.uint32_field(8)
