# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InBattleChessInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .ChessCardInfo import *
from .ChessMysteryInfo import *
from .ChessPlayerInfo import *


@dataclass
class InBattleChessInfo(betterproto.Message):
    ban_card_tag_list: List[int] = betterproto.uint32_field(2)
    round: int = betterproto.uint32_field(4)
    selected_card_info_list: List["ChessCardInfo"] = betterproto.message_field(9)
    mystery_info: "ChessMysteryInfo" = betterproto.message_field(1)
    player_info_map: Dict[int, "ChessPlayerInfo"] = betterproto.map_field(
        8, betterproto.TYPE_UINT32, betterproto.TYPE_MESSAGE
    )
    max_escapable_monsters: int = betterproto.uint32_field(6)
    escaped_monsters: int = betterproto.uint32_field(12)
    total_round: int = betterproto.uint32_field(14)
    left_monsters: int = betterproto.uint32_field(15)
