# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InterruptGalleryRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class InterruptGalleryRsp(betterproto.Message):
    """
    CmdId: 5597 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(12)
    gallery_id: int = betterproto.uint32_field(9)
