# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InteractDailyDungeonInfoNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class InteractDailyDungeonInfoNotify(betterproto.Message):
    """
    CmdId: 919 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
