# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: InvestigationTarget.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class InvestigationTargetState(betterproto.Enum):
    STATE_INVALID = 0
    STATE_IN_PROGRESS = 1
    STATE_COMPLETE = 2
    STATE_REWARD_TAKEN = 3


@dataclass
class InvestigationTarget(betterproto.Message):
    quest_id: int = betterproto.uint32_field(15)
    state: "InvestigationTargetState" = betterproto.enum_field(2)
    progress: int = betterproto.uint32_field(8)
    total_progress: int = betterproto.uint32_field(7)
    investigation_id: int = betterproto.uint32_field(3)
