# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ItemParam.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ItemParam(betterproto.Message):
    item_id: int = betterproto.uint32_field(1)
    count: int = betterproto.uint32_field(2)
