# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ItemGivingReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .ItemParam import *


class ItemGivingReqUnk2800_LENCDFJACFN(betterproto.Enum):
    Unk2800_LENCDFJACFN_QUEST = 0
    Unk2800_LENCDFJACFN_Unk2800_HHHOPEHIPFG = 1


@dataclass
class ItemGivingReq(betterproto.Message):
    """
    CmdId: 140 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    item_guid_count_map: Dict[int, int] = betterproto.map_field(
        15, betterproto.TYPE_UINT64, betterproto.TYPE_UINT32
    )
    giving_id: int = betterproto.uint32_field(13)
    item_param_list: List["ItemParam"] = betterproto.message_field(4)
    unk2800__p_h_n_i_j_j_m_e_c_g_n: "ItemGivingReqUnk2800_LENCDFJACFN" = (
        betterproto.enum_field(2)
    )
