# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Item.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Equip import *
from .Furniture import *
from .Material import *


@dataclass
class Item(betterproto.Message):
    item_id: int = betterproto.uint32_field(1)
    guid: int = betterproto.uint64_field(2)
    material: "Material" = betterproto.message_field(5, group="detail")
    equip: "Equip" = betterproto.message_field(6, group="detail")
    furniture: "Furniture" = betterproto.message_field(7, group="detail")
