# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ItemGivingRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ItemGivingRsp(betterproto.Message):
    """
    CmdId: 118 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__m_h_i_p_h_d_f_e_o_o_n: int = betterproto.uint32_field(1)
    giving_id: int = betterproto.uint32_field(13)
    retcode: int = betterproto.int32_field(3)
