# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: KeepAliveNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class KeepAliveNotify(betterproto.Message):
    """CmdId: 72 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true"""

    pass
