# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: LanternRiteActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_JCNIPOJMFMH import *
from .Unk2700_LLGDCAKMCKL import *
from .Unk2700_MJGFEHOMKJE import *


@dataclass
class LanternRiteActivityDetailInfo(betterproto.Message):
    unk2700__o_n_o_h_o_d_j_p_i_g_k: "Unk2700_JCNIPOJMFMH" = betterproto.message_field(
        13
    )
    unk2700__p_h_k_h_i_p_l_d_o_o_a: List[
        "Unk2700_LLGDCAKMCKL"
    ] = betterproto.message_field(5)
    unk2700__m_p_o_c_l_g_b_f_n_a_k: "Unk2700_MJGFEHOMKJE" = betterproto.message_field(8)
    unk2700__k_g_g_c_k_h_b_i_o_e_d: bool = betterproto.bool_field(2)
    is_content_closed: bool = betterproto.bool_field(14)
    unk2700__e_o_g_e_a_i_h_j_p_f_d: bool = betterproto.bool_field(6)
