# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: LeaveSceneReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class LeaveSceneReq(betterproto.Message):
    """
    CmdId: 298 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
