# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: LifeStateChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .PlayerDieType import *
from .ServerBuff import *


@dataclass
class LifeStateChangeNotify(betterproto.Message):
    """
    CmdId: 1298 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    entity_id: int = betterproto.uint32_field(4)
    server_buff_list: List["ServerBuff"] = betterproto.message_field(6)
    attack_tag: str = betterproto.string_field(7)
    move_reliable_seq: int = betterproto.uint32_field(15)
    die_type: "PlayerDieType" = betterproto.enum_field(14)
    life_state: int = betterproto.uint32_field(5)
    source_entity_id: int = betterproto.uint32_field(1)
