# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: LiveStartNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class LiveStartNotify(betterproto.Message):
    """
    CmdId: 826 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    live_id: int = betterproto.uint32_field(2)
