# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: LunaRiteHintPointType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class LunaRiteHintPointType(betterproto.Enum):
    LUNA_RITE_HINT_POINT_TYPE_NONE = 0
    LUNA_RITE_HINT_POINT_TYPE_RUNE = 1
    LUNA_RITE_HINT_POINT_TYPE_CHEST = 2
