# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: LunaRiteTakeSacrificeRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class LunaRiteTakeSacrificeRewardRsp(betterproto.Message):
    """
    CmdId: 8397 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    index: int = betterproto.uint32_field(11)
    sacrifice_reward_list: List[int] = betterproto.uint32_field(2)
    sacrifice_reward_index: int = betterproto.uint32_field(14)
    area_id: int = betterproto.uint32_field(6)
    retcode: int = betterproto.int32_field(12)
