# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MarkMapReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .MapMarkPoint import *


class MarkMapReqOperation(betterproto.Enum):
    OPERATION_ADD = 0
    OPERATION_MOD = 1
    OPERATION_DEL = 2
    OPERATION_GET = 3


@dataclass
class MarkMapReq(betterproto.Message):
    """
    CmdId: 3466 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    mark: "MapMarkPoint" = betterproto.message_field(8)
    old: "MapMarkPoint" = betterproto.message_field(6)
    op: "MarkMapReqOperation" = betterproto.enum_field(9)
