# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MarkTargetInvestigationMonsterNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MarkTargetInvestigationMonsterNotify(betterproto.Message):
    """
    CmdId: 1915 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    scene_id: int = betterproto.uint32_field(11)
    monster_id: int = betterproto.uint32_field(4)
    group_id: int = betterproto.uint32_field(5)
    investigation_monster_id: int = betterproto.uint32_field(12)
