# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MassiveEntityStateChangedNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MassiveEntityState import *


@dataclass
class MassiveEntityStateChangedNotify(betterproto.Message):
    """
    CmdId: 370 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    massive_entity_state_list: List["MassiveEntityState"] = betterproto.message_field(4)
