# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MatchPlayerInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .OnlinePlayerInfo import *


@dataclass
class MatchPlayerInfo(betterproto.Message):
    is_agreed: bool = betterproto.bool_field(9)
    player_info: "OnlinePlayerInfo" = betterproto.message_field(2)
