# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MaterialInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MaterialInfo(betterproto.Message):
    count: int = betterproto.uint32_field(11)
    guid: int = betterproto.uint64_field(5)
