# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MaterialDeleteReturnType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class MaterialDeleteReturnType(betterproto.Enum):
    MATERIAL_DELETE_RETURN_TYPE_BAG = 0
    MATERIAL_DELETE_RETURN_TYPE_SEED = 1
