# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: McoinExchangeHcoinReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class McoinExchangeHcoinReq(betterproto.Message):
    """
    CmdId: 616 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    hcoin: int = betterproto.uint32_field(5)
    mcoin_cost: int = betterproto.uint32_field(1)
