# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MechanicusSequenceOpenNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MechanicusSequenceOpenNotify(betterproto.Message):
    """
    CmdId: 3912 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    mechanicus_id: int = betterproto.uint32_field(8)
    sequence_id: int = betterproto.uint32_field(7)
