# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MeetNpcReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MeetNpcReq(betterproto.Message):
    """
    CmdId: 503 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    npc_id: int = betterproto.uint32_field(4)
