# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MichiaeMatsuriActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MichiaeMatsuriStage import *
from .Unk2700_HGFFGMCODNC import *
from .Unk2700_NAFAIMHFEFG import *


@dataclass
class MichiaeMatsuriActivityDetailInfo(betterproto.Message):
    unk2700__m_p_n_n_m_c_p_o_l_a_m: List[
        "Unk2700_HGFFGMCODNC"
    ] = betterproto.message_field(6)
    unk2700__m_a_o_a_h_h_b_c_k_i_a: int = betterproto.uint32_field(13)
    unk2700__b_e_h_a_a_h_h_g_c_l_k: List[int] = betterproto.uint32_field(2)
    unk2700__l_e_k_h_k_n_k_h_i_p_o: List[
        "Unk2700_NAFAIMHFEFG"
    ] = betterproto.message_field(10)
    stage_list: List["MichiaeMatsuriStage"] = betterproto.message_field(14)
