# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MistTrialSelectAvatarAndEnterDungeonReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class MistTrialSelectAvatarAndEnterDungeonReq(betterproto.Message):
    """
    CmdId: 8666 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    trial_id: int = betterproto.uint32_field(4)
    select_trial_avatar_id_list: List[int] = betterproto.uint32_field(10)
    enter_point_id: int = betterproto.uint32_field(7)
