# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ModifierDurability.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ModifierDurability(betterproto.Message):
    reduce_ratio: float = betterproto.float_field(1)
    remaining_durability: float = betterproto.float_field(2)
