# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ModifierAction.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class ModifierAction(betterproto.Enum):
    MODIFIER_ACTION_ADDED = 0
    MODIFIER_ACTION_REMOVED = 1
