# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MonsterRoute.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .RoutePoint import *


@dataclass
class MonsterRoute(betterproto.Message):
    route_points: List["RoutePoint"] = betterproto.message_field(1)
    speed_level: int = betterproto.uint32_field(2)
    route_type: int = betterproto.uint32_field(3)
    arrive_range: float = betterproto.float_field(4)
