# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MovingPlatformType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class MovingPlatformType(betterproto.Enum):
    MOVING_PLATFORM_TYPE_NONE = 0
    MOVING_PLATFORM_TYPE_USE_CONFIG = 1
    MOVING_PLATFORM_TYPE_ABILITY = 2
    MOVING_PLATFORM_TYPE_ROUTE = 3
