# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MpBlockNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MpBlockNotify(betterproto.Message):
    """
    CmdId: 1801 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    end_time: int = betterproto.uint32_field(13)
