# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MpPlayOwnerCheckRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MpPlayOwnerCheckRsp(betterproto.Message):
    """
    CmdId: 1847 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    wrong_uid: int = betterproto.uint32_field(4)
    is_skip_match: bool = betterproto.bool_field(15)
    mp_play_id: int = betterproto.uint32_field(10)
    retcode: int = betterproto.int32_field(12)
