# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MpPlayOwnerInviteNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MpPlayOwnerInviteNotify(betterproto.Message):
    """
    CmdId: 1835 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    cd: int = betterproto.uint32_field(12)
    mp_play_id: int = betterproto.uint32_field(13)
    is_remain_reward: bool = betterproto.bool_field(10)
