# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MpPlayGuestReplyInviteRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MpPlayGuestReplyInviteRsp(betterproto.Message):
    """
    CmdId: 1850 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(4)
    mp_play_id: int = betterproto.uint32_field(10)
