# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MpPlayPrepareInterruptNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MpPlayPrepareInterruptNotify(betterproto.Message):
    """
    CmdId: 1813 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    mp_play_id: int = betterproto.uint32_field(12)
