# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MpPlayGuestReplyInviteReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MpPlayGuestReplyInviteReq(betterproto.Message):
    """
    CmdId: 1848 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    mp_play_id: int = betterproto.uint32_field(3)
    is_agree: bool = betterproto.bool_field(15)
