# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MultistagePlayInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .HideAndSeekStageInfo import *
from .InBattleChessInfo import *
from .InBattleFleurFairInfo import *
from .InBattleMechanicusInfo import *
from .IrodoriChessInfo import *


@dataclass
class MultistagePlayInfo(betterproto.Message):
    play_index: int = betterproto.uint32_field(13)
    play_type: int = betterproto.uint32_field(11)
    stage_type: int = betterproto.uint32_field(10)
    duration: int = betterproto.uint32_field(8)
    group_id: int = betterproto.uint32_field(12)
    begin_time: int = betterproto.uint32_field(9)
    stage_index: int = betterproto.uint32_field(1)
    mechanicus_info: "InBattleMechanicusInfo" = betterproto.message_field(
        1334, group="detail"
    )
    fleur_fair_info: "InBattleFleurFairInfo" = betterproto.message_field(
        1064, group="detail"
    )
    hide_and_seek_info: "HideAndSeekStageInfo" = betterproto.message_field(
        108, group="detail"
    )
    chess_info: "InBattleChessInfo" = betterproto.message_field(1758, group="detail")
    irodori_chess_info: "IrodoriChessInfo" = betterproto.message_field(
        531, group="detail"
    )
