# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MultistagePlayEndNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MultistagePlayEndNotify(betterproto.Message):
    """
    CmdId: 5355 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    group_id: int = betterproto.uint32_field(5)
    play_index: int = betterproto.uint32_field(13)
