# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MusicBriefInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class MusicBriefInfo(betterproto.Message):
    unk2700__j_n_e_n_c_b_c_g_p_g_o: int = betterproto.uint64_field(5)
    unk2700__o_j_b_p_h_c_i_d_a_e_b: bool = betterproto.bool_field(8)
    unk2700__f_g_c_j_e_g_h_o_k_p_g: bool = betterproto.bool_field(1)
    unk2700__d_f_i_b_a_i_i_l_j_h_n: int = betterproto.uint32_field(2)
    unk2700__m_k_b_n_l_e_k_m_i_m_d: int = betterproto.uint32_field(1182)
    unk2700__p_i_n_g_i_i_a_a_n_m_o: int = betterproto.uint32_field(12)
    unk2700__m_o_n_n_i_d_c_n_d_f_i: str = betterproto.string_field(10)
    version: int = betterproto.uint32_field(15)
    unk2700__g_g_h_n_l_p_m_a_g_m_e: int = betterproto.uint32_field(3)
    unk2700__g_d_c_g_o_m_n_b_m_e_o: List[int] = betterproto.uint32_field(1002)
    unk2700__j_a_e_o_n_b_m_b_f_j_j: List[int] = betterproto.uint32_field(982)
    unk2700__g_b_c_g_g_d_o_n_m_c_d: bool = betterproto.bool_field(9)
    unk2700__l_p_e_k_f_j_b_n_e_j_m: int = betterproto.uint32_field(1822)
    unk2700__d_n_l_e_g_a_d_d_h_k_m: bool = betterproto.bool_field(11)
    unk2700__b_f_m_n_m_p_p_n_b_h_h: int = betterproto.uint32_field(13)
    max_score: int = betterproto.uint32_field(14)
    unk2700__k_a_m_o_c_h_a_k_p_g_p: int = betterproto.uint32_field(576)
    unk2700__k_l_p_h_b_l_c_i_o_e_c: int = betterproto.uint32_field(7)
    unk2700__c_e_p_g_m_k_a_h_h_c_d: int = betterproto.uint64_field(4)
    unk2700__p_m_c_p_l_p_m_j_c_e_c: int = betterproto.uint32_field(6)
