# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: MusicGameSettleRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class MusicGameSettleRsp(betterproto.Message):
    """
    CmdId: 8673 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(11)
    music_basic_id: int = betterproto.uint32_field(5)
    is_new_record: bool = betterproto.bool_field(6)
    is_unlock_next_level: bool = betterproto.bool_field(2)
    unk2700__c_e_p_g_m_k_a_h_h_c_d: int = betterproto.uint64_field(10)
