# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: NormalUidOpNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class NormalUidOpNotify(betterproto.Message):
    """
    CmdId: 5726 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    duration: int = betterproto.uint32_field(6)
    param_list: List[int] = betterproto.uint32_field(4)
    param_uid_list: List[int] = betterproto.uint32_field(5)
    param_index: int = betterproto.uint32_field(8)
