# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: OpActivityTagBriefInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class OpActivityTagBriefInfo(betterproto.Message):
    config_id: int = betterproto.uint32_field(2)
    has_reward: bool = betterproto.bool_field(3)
    op_activity_type: int = betterproto.uint32_field(11)
