# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: OpActivityStateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .OpActivityTagBriefInfo import *


@dataclass
class OpActivityStateNotify(betterproto.Message):
    """
    CmdId: 2572 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    finished_bonus_activity_id_list: List[int] = betterproto.uint32_field(14)
    opened_op_activity_info_list: List[
        "OpActivityTagBriefInfo"
    ] = betterproto.message_field(13)
