# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: OrderFinishNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


@dataclass
class OrderFinishNotify(betterproto.Message):
    """
    CmdId: 4125 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    order_id: int = betterproto.uint32_field(3)
    card_product_remain_days: int = betterproto.uint32_field(15)
    item_list: List["ItemParam"] = betterproto.message_field(9)
    add_mcoin: int = betterproto.uint32_field(7)
    product_id: str = betterproto.string_field(6)
