# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ParentQuestRandomInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ParentQuestRandomInfo(betterproto.Message):
    factor_list: List[int] = betterproto.uint32_field(1)
    template_id: int = betterproto.uint32_field(8)
    entrance_id: int = betterproto.uint32_field(2)
