# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PathfindingEnterSceneReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ObstacleInfo import *


@dataclass
class PathfindingEnterSceneReq(betterproto.Message):
    """
    CmdId: 2307 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    scene_id: int = betterproto.uint32_field(12)
    activity_id: List[int] = betterproto.uint32_field(14)
    unk2800__n_c_d_f_a_f_m_g_m_i_g: int = betterproto.uint32_field(15)
    version: int = betterproto.uint32_field(6)
    is_editor: bool = betterproto.bool_field(11)
    obstacles: List["ObstacleInfo"] = betterproto.message_field(13)
    unk2800__m_b_d_f_g_o_d_m_p_f_n: int = betterproto.uint32_field(4)
