# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PathfindingEnterSceneRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PathfindingEnterSceneRsp(betterproto.Message):
    """
    CmdId: 2321 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(9)
