# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PersonalLineNewUnlockNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class PersonalLineNewUnlockNotify(betterproto.Message):
    """
    CmdId: 442 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    personal_line_id_list: List[int] = betterproto.uint32_field(9)
