# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PhotoActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .PhotoStage import *


@dataclass
class PhotoActivityDetailInfo(betterproto.Message):
    is_content_closed: bool = betterproto.bool_field(4)
    photo_stage_list: List["PhotoStage"] = betterproto.message_field(12)
