# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PingReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PingReq(betterproto.Message):
    """CmdId: 7 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true"""

    client_time: int = betterproto.uint32_field(12)
    ue_time: float = betterproto.float_field(14)
    total_tick_time: float = betterproto.double_field(6)
    sc_data: bytes = betterproto.bytes_field(10)
    seq: int = betterproto.uint32_field(3)
