# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlantFlowerGetFriendFlowerWishListRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .PlantFlowerFriendFlowerWishData import *


@dataclass
class PlantFlowerGetFriendFlowerWishListRsp(betterproto.Message):
    """
    CmdId: 8511 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(6)
    schedule_id: int = betterproto.uint32_field(2)
    friend_flower_wish_list: List[
        "PlantFlowerFriendFlowerWishData"
    ] = betterproto.message_field(9)
