# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlantFlowerGetCanGiveFriendFlowerReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlantFlowerGetCanGiveFriendFlowerReq(betterproto.Message):
    """
    CmdId: 8716 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(15)
