# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlantFlowerGetRecvFlowerListReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlantFlowerGetRecvFlowerListReq(betterproto.Message):
    """
    CmdId: 8270 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(1)
