# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlantFlowerAcceptGiveFlowerRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .PlantFlowerAcceptFlowerResultInfo import *


@dataclass
class PlantFlowerAcceptGiveFlowerRsp(betterproto.Message):
    """
    CmdId: 8567 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(1)
    accept_flower_result_info: "PlantFlowerAcceptFlowerResultInfo" = (
        betterproto.message_field(15)
    )
    retcode: int = betterproto.int32_field(12)
