# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlantFlowerGiveFriendFlowerRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class PlantFlowerGiveFriendFlowerRsp(betterproto.Message):
    """
    CmdId: 8386 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    limit_flower_list: List[int] = betterproto.uint32_field(5)
    retcode: int = betterproto.int32_field(3)
    schedule_id: int = betterproto.uint32_field(14)
