# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlantFlowerSetFlowerWishRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlantFlowerSetFlowerWishRsp(betterproto.Message):
    """
    CmdId: 8910 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(7)
    retcode: int = betterproto.int32_field(8)
