# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlantFlowerGetSeedInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlantFlowerGetSeedInfoReq(betterproto.Message):
    """
    CmdId: 8560 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(6)
