# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerPreEnterMpNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class PlayerPreEnterMpNotifyState(betterproto.Enum):
    STATE_INVALID = 0
    STATE_START = 1
    STATE_TIMEOUT = 2


@dataclass
class PlayerPreEnterMpNotify(betterproto.Message):
    """
    CmdId: 1822 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    state: "PlayerPreEnterMpNotifyState" = betterproto.enum_field(2)
    uid: int = betterproto.uint32_field(14)
    nickname: str = betterproto.string_field(6)
