# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerWorldSceneInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class PlayerWorldSceneInfo(betterproto.Message):
    scene_id: int = betterproto.uint32_field(11)
    scene_tag_id_list: List[int] = betterproto.uint32_field(8)
    is_locked: bool = betterproto.bool_field(12)
