# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerRTTInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerRTTInfo(betterproto.Message):
    rtt: int = betterproto.uint32_field(2)
    uid: int = betterproto.uint32_field(1)
