# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerSetLanguageRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerSetLanguageRsp(betterproto.Message):
    """
    CmdId: 130 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(11)
