# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerStartMatchRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .MatchType import *


@dataclass
class PlayerStartMatchRsp(betterproto.Message):
    """
    CmdId: 4168 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(1)
    punish_end_time: int = betterproto.uint32_field(5)
    param: int = betterproto.uint32_field(4)
    mp_play_id: int = betterproto.uint32_field(13)
    mechanicus_difficult_level: int = betterproto.uint32_field(2)
    dungeon_id: int = betterproto.uint32_field(3)
    match_id: int = betterproto.uint32_field(8)
    match_type: "MatchType" = betterproto.enum_field(7)
