# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerSetLanguageReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerSetLanguageReq(betterproto.Message):
    """
    CmdId: 142 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    language_type: int = betterproto.uint32_field(5)
