# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerApplyEnterMpReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerApplyEnterMpReq(betterproto.Message):
    """
    CmdId: 1818 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    target_uid: int = betterproto.uint32_field(4)
