# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayProduct.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayProduct(betterproto.Message):
    product_id: str = betterproto.string_field(1)
    price_tier: str = betterproto.string_field(2)
    schedule_id: int = betterproto.uint32_field(3)
