# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerApplyEnterMpResultReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerApplyEnterMpResultReq(betterproto.Message):
    """
    CmdId: 1802 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    apply_uid: int = betterproto.uint32_field(2)
    is_agreed: bool = betterproto.bool_field(12)
