# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerGetForceQuitBanInfoRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerGetForceQuitBanInfoRsp(betterproto.Message):
    """
    CmdId: 4197 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(4)
    match_id: int = betterproto.uint32_field(8)
    expire_time: int = betterproto.uint32_field(13)
