# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerGetForceQuitBanInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerGetForceQuitBanInfoReq(betterproto.Message):
    """
    CmdId: 4164 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
