# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerHomeCompInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .FriendEnterHomeOption import *


@dataclass
class PlayerHomeCompInfo(betterproto.Message):
    unlocked_module_id_list: List[int] = betterproto.uint32_field(4)
    seen_module_id_list: List[int] = betterproto.uint32_field(2)
    levelup_reward_got_level_list: List[int] = betterproto.uint32_field(7)
    friend_enter_home_option: "FriendEnterHomeOption" = betterproto.enum_field(8)
