# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerCookArgsReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerCookArgsReq(betterproto.Message):
    """
    CmdId: 166 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    assist_avatar: int = betterproto.uint32_field(10)
    recipe_id: int = betterproto.uint32_field(11)
