# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerEnterSceneNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .EnterType import *
from .Vector import *


@dataclass
class PlayerEnterSceneNotify(betterproto.Message):
    """
    CmdId: 272 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    prev_scene_id: int = betterproto.uint32_field(6)
    dungeon_id: int = betterproto.uint32_field(12)
    is_skip_ui: bool = betterproto.bool_field(1732)
    scene_id: int = betterproto.uint32_field(15)
    type: "EnterType" = betterproto.enum_field(13)
    scene_begin_time: int = betterproto.uint64_field(14)
    world_level: int = betterproto.uint32_field(11)
    world_type: int = betterproto.uint32_field(1490)
    target_uid: int = betterproto.uint32_field(4)
    is_first_login_enter_scene: bool = betterproto.bool_field(3)
    scene_tag_id_list: List[int] = betterproto.uint32_field(5)
    scene_transaction: str = betterproto.string_field(1842)
    prev_pos: "Vector" = betterproto.message_field(8)
    enter_reason: int = betterproto.uint32_field(1828)
    pos: "Vector" = betterproto.message_field(7)
    enter_scene_token: int = betterproto.uint32_field(2)
