# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerLevelRewardUpdateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class PlayerLevelRewardUpdateNotify(betterproto.Message):
    """
    CmdId: 200 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    level_list: List[int] = betterproto.uint32_field(9)
