# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerWorldSceneInfoListNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .PlayerWorldSceneInfo import *


@dataclass
class PlayerWorldSceneInfoListNotify(betterproto.Message):
    """
    CmdId: 3129 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    info_list: List["PlayerWorldSceneInfo"] = betterproto.message_field(5)
