# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerChatReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ChatInfo import *


@dataclass
class PlayerChatReq(betterproto.Message):
    """
    CmdId: 3185 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    channel_id: int = betterproto.uint32_field(13)
    chat_info: "ChatInfo" = betterproto.message_field(15)
