# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerQuitFromHomeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class PlayerQuitFromHomeNotifyQuitReason(betterproto.Enum):
    QUIT_REASON_INVALID = 0
    QUIT_REASON_KICK_BY_HOST = 1
    QUIT_REASON_BACK_TO_MY_WORLD = 2
    QUIT_REASON_HOME_BLOCKED = 3
    QUIT_REASON_HOME_IN_EDIT_MODE = 4
    QUIT_REASON_BY_MUIP = 5
    QUIT_REASON_CUR_MODULE_CLOSED = 6


@dataclass
class PlayerQuitFromHomeNotify(betterproto.Message):
    """
    CmdId: 4656 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    reason: "PlayerQuitFromHomeNotifyQuitReason" = betterproto.enum_field(6)
