# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerCompoundMaterialReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerCompoundMaterialReq(betterproto.Message):
    """
    CmdId: 150 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    count: int = betterproto.uint32_field(11)
    compound_id: int = betterproto.uint32_field(3)
