# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto

from .PropValue import *


@dataclass
class PlayerDataNotify(betterproto.Message):
    """
    CmdId: 190 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    server_time: int = betterproto.uint64_field(7)
    nick_name: str = betterproto.string_field(8)
    is_first_login_today: bool = betterproto.bool_field(12)
    region_id: int = betterproto.uint32_field(6)
    prop_map: Dict[int, "PropValue"] = betterproto.map_field(
        15, betterproto.TYPE_UINT32, betterproto.TYPE_MESSAGE
    )
