# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerStartMatchReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MatchType import *


@dataclass
class PlayerStartMatchReq(betterproto.Message):
    """
    CmdId: 4176 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    match_type: "MatchType" = betterproto.enum_field(3)
    mechanicus_difficult_level: int = betterproto.uint32_field(12)
    match_param_list: List[int] = betterproto.uint32_field(11)
    dungeon_id: int = betterproto.uint32_field(1)
    mp_play_id: int = betterproto.uint32_field(15)
    match_id: int = betterproto.uint32_field(6)
