# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerLuaShellNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_JOEPIGNPDGH import *


@dataclass
class PlayerLuaShellNotify(betterproto.Message):
    """
    CmdId: 133 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__j_j_m_h_f_f_h_n_j_j_o: "Unk2700_JOEPIGNPDGH" = betterproto.enum_field(7)
    id: int = betterproto.uint32_field(5)
    lua_shell: bytes = betterproto.bytes_field(12)
    use_type: int = betterproto.uint32_field(10)
