# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerApplyEnterHomeResultReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerApplyEnterHomeResultReq(betterproto.Message):
    """
    CmdId: 4693 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    apply_uid: int = betterproto.uint32_field(14)
    is_agreed: bool = betterproto.bool_field(10)
