# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerLocationInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class PlayerLocationInfo(betterproto.Message):
    uid: int = betterproto.uint32_field(15)
    pos: "Vector" = betterproto.message_field(3)
    rot: "Vector" = betterproto.message_field(13)
