# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerLogoutNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PlayerLogoutNotify(betterproto.Message):
    """CmdId: 103 EnetChannelId: 0 EnetIsReliable: false"""

    retcode: int = betterproto.int32_field(13)
