# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerDieOption.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class PlayerDieOption(betterproto.Enum):
    PLAYER_DIE_OPTION_OPT_NONE = 0
    PLAYER_DIE_OPTION_OPT_REPLAY = 1
    PLAYER_DIE_OPTION_OPT_CANCEL = 2
    PLAYER_DIE_OPTION_OPT_REVIVE = 3
