# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerCancelMatchRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .MatchType import *


@dataclass
class PlayerCancelMatchRsp(betterproto.Message):
    """
    CmdId: 4152 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(6)
    match_type: "MatchType" = betterproto.enum_field(7)
