# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayTeamEntityInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .AbilitySyncStateInfo import *


@dataclass
class PlayTeamEntityInfo(betterproto.Message):
    entity_id: int = betterproto.uint32_field(1)
    player_uid: int = betterproto.uint32_field(2)
    authority_peer_id: int = betterproto.uint32_field(3)
    gadget_config_id: int = betterproto.uint32_field(5)
    ability_info: "AbilitySyncStateInfo" = betterproto.message_field(6)
