# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PlayerGeneralMatchDismissNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MatchReason import *


@dataclass
class PlayerGeneralMatchDismissNotify(betterproto.Message):
    """
    CmdId: 4191 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    uid_list: List[int] = betterproto.uint32_field(3)
    reason: "MatchReason" = betterproto.enum_field(13)
    match_id: int = betterproto.uint32_field(1)
