# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PostEnterSceneRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PostEnterSceneRsp(betterproto.Message):
    """
    CmdId: 3184 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(4)
    enter_scene_token: int = betterproto.uint32_field(12)
