# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PotionStage.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_JLHKOLGFAMI import *


@dataclass
class PotionStage(betterproto.Message):
    stage_id: int = betterproto.uint32_field(11)
    unk2700__h_f_h_c_c_j_f_d_o_k_a: List[int] = betterproto.uint32_field(2)
    is_open: bool = betterproto.bool_field(15)
    level_list: List["Unk2700_JLHKOLGFAMI"] = betterproto.message_field(14)
    unk2700__l_o_n_i_j_g_b_d_p_i_g: List[int] = betterproto.uint32_field(13)
