# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PrivateChatNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ChatInfo import *


@dataclass
class PrivateChatNotify(betterproto.Message):
    """
    CmdId: 4962 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    chat_info: "ChatInfo" = betterproto.message_field(7)
