# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ProfilePicture.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ProfilePicture(betterproto.Message):
    avatar_id: int = betterproto.uint32_field(1)
    costume_id: int = betterproto.uint32_field(2)
