# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PropPair.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .PropValue import *


@dataclass
class PropPair(betterproto.Message):
    type: int = betterproto.uint32_field(1)
    prop_value: "PropValue" = betterproto.message_field(2)
