# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ProudSkillExtraLevelNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ProudSkillExtraLevelNotify(betterproto.Message):
    """
    CmdId: 1081 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    talent_type: int = betterproto.uint32_field(11)
    talent_index: int = betterproto.uint32_field(8)
    avatar_guid: int = betterproto.uint64_field(15)
    extra_level: int = betterproto.uint32_field(3)
