# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PSPlayerApplyEnterMpReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PSPlayerApplyEnterMpReq(betterproto.Message):
    """
    CmdId: 1841 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    target_psn_id: str = betterproto.string_field(5)
