# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PushTipsReadFinishReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PushTipsReadFinishReq(betterproto.Message):
    """
    CmdId: 2204 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    push_tips_id: int = betterproto.uint32_field(11)
