# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PushTipsData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class PushTipsData(betterproto.Message):
    push_tips_id: int = betterproto.uint32_field(13)
    state: int = betterproto.uint32_field(4)
