# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: QuestDestroyEntityRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class QuestDestroyEntityRsp(betterproto.Message):
    """
    CmdId: 448 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    quest_id: int = betterproto.uint32_field(14)
    scene_id: int = betterproto.uint32_field(9)
    entity_id: int = betterproto.uint32_field(12)
    retcode: int = betterproto.int32_field(1)
