# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: QuestVarOp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class QuestVarOp(betterproto.Message):
    index: int = betterproto.uint32_field(9)
    value: int = betterproto.int32_field(5)
    is_add: bool = betterproto.bool_field(6)
