# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: QuestUpdateQuestTimeVarNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto


@dataclass
class QuestUpdateQuestTimeVarNotify(betterproto.Message):
    """
    CmdId: 456 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    time_var_map: Dict[int, int] = betterproto.map_field(
        1, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    parent_quest_id: int = betterproto.uint32_field(3)
