# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: QuestDestroyNpcReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class QuestDestroyNpcReq(betterproto.Message):
    """
    CmdId: 422 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    npc_id: int = betterproto.uint32_field(1)
    parent_quest_id: int = betterproto.uint32_field(12)
