# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: QuickUseWidgetRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ClientCollectorData import *
from .OneofGatherPointDetectorData import *
from .SkyCrystalDetectorQuickUseResult import *


@dataclass
class QuickUseWidgetRsp(betterproto.Message):
    """
    CmdId: 4270 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    material_id: int = betterproto.uint32_field(6)
    retcode: int = betterproto.int32_field(5)
    detector_data: "OneofGatherPointDetectorData" = betterproto.message_field(
        3, group="param"
    )
    client_collector_data: "ClientCollectorData" = betterproto.message_field(
        15, group="param"
    )
    sky_crystal_detector_quick_use_result: "SkyCrystalDetectorQuickUseResult" = (
        betterproto.message_field(168922, group="param")
    )
