# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RacingGalleryInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_OJJNGIHDJEH import *


@dataclass
class RacingGalleryInfo(betterproto.Message):
    record_list: List["Unk2700_OJJNGIHDJEH"] = betterproto.message_field(7)
