# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RefreshBackgroundAvatarReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class RefreshBackgroundAvatarReq(betterproto.Message):
    """
    CmdId: 1743 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
