# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RefreshRoguelikeDungeonCardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class RefreshRoguelikeDungeonCardRsp(betterproto.Message):
    """
    CmdId: 8349 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(3)
    res_card_list: List[int] = betterproto.uint32_field(9)
