# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RegionSearch.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .RegionSearchState import *


@dataclass
class RegionSearch(betterproto.Message):
    is_entered: bool = betterproto.bool_field(13)
    progress: int = betterproto.uint32_field(5)
    state: "RegionSearchState" = betterproto.enum_field(2)
    region_search_id: int = betterproto.uint32_field(8)
