# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ReliquaryResponse.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_GBBDJMDIDEI import *


@dataclass
class ReliquaryResponse(betterproto.Message):
    unk2700__d_m_d_h_d_i_h_g_p_f_a: List[
        "Unk2700_GBBDJMDIDEI"
    ] = betterproto.message_field(8)
    equip_type: int = betterproto.uint32_field(3)
