# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ReliquaryPromoteRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ReliquaryPromoteRsp(betterproto.Message):
    """
    CmdId: 694 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    old_promote_level: int = betterproto.uint32_field(10)
    target_reliquary_guid: int = betterproto.uint64_field(6)
    cur_append_prop_list: List[int] = betterproto.uint32_field(9)
    retcode: int = betterproto.int32_field(12)
    cur_promote_level: int = betterproto.uint32_field(2)
    old_append_prop_list: List[int] = betterproto.uint32_field(8)
