# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RemoveBlacklistRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class RemoveBlacklistRsp(betterproto.Message):
    """
    CmdId: 4095 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(12)
    target_uid: int = betterproto.uint32_field(7)
