# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ReportTrackingIOInfoNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ReportTrackingIOInfoNotify(betterproto.Message):
    """
    CmdId: 4129 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    rydevicetype: str = betterproto.string_field(12)
    deviceid: str = betterproto.string_field(1)
    client_tz: str = betterproto.string_field(13)
    appid: str = betterproto.string_field(14)
    mac: str = betterproto.string_field(15)
