# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RequestLiveInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class RequestLiveInfoReq(betterproto.Message):
    """
    CmdId: 894 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    live_id: int = betterproto.uint32_field(6)
