# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ResinCardData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ResinCardData(betterproto.Message):
    remain_reward_days: int = betterproto.uint32_field(3)
    expire_time: int = betterproto.uint32_field(12)
    last_daily_reward_time: int = betterproto.uint32_field(2)
    config_id: int = betterproto.uint32_field(7)
