# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ResinCardDataUpdateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ResinCardData import *


@dataclass
class ResinCardDataUpdateNotify(betterproto.Message):
    """
    CmdId: 4149 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    today_start_time: int = betterproto.uint32_field(6)
    card_data_list: List["ResinCardData"] = betterproto.message_field(2)
