# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ReunionBriefInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ReunionBriefInfoReq(betterproto.Message):
    """
    CmdId: 5076 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
