# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ReunionSettleNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ReunionSettleNotify(betterproto.Message):
    """
    CmdId: 5073 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
