# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ReunionPrivilegeChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ReunionPrivilegeInfo import *


@dataclass
class ReunionPrivilegeChangeNotify(betterproto.Message):
    """
    CmdId: 5098 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    privilege_info: "ReunionPrivilegeInfo" = betterproto.message_field(13)
