# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RoguelikeResourceBonusPropUpdateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class RoguelikeResourceBonusPropUpdateNotify(betterproto.Message):
    """
    CmdId: 8555 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    bonus_resource_prop: float = betterproto.float_field(12)
