# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RogueEliteCellDifficultyType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class RogueEliteCellDifficultyType(betterproto.Enum):
    ROGUE_ELITE_CELL_DIFFICULTY_TYPE_NORMAL = 0
    ROGUE_ELITE_CELL_DIFFICULTY_TYPE_HARD = 1
