# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RoguelikeShikigamiRecord.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class RoguelikeShikigamiRecord(betterproto.Message):
    id: int = betterproto.uint32_field(6)
    level: int = betterproto.uint32_field(3)
