# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RogueHealAvatarsRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class RogueHealAvatarsRsp(betterproto.Message):
    """
    CmdId: 8949 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    dungeon_id: int = betterproto.uint32_field(10)
    retcode: int = betterproto.int32_field(9)
    cell_id: int = betterproto.uint32_field(14)
