# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RoguelikeEffectViewRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class RoguelikeEffectViewRsp(betterproto.Message):
    """
    CmdId: 8639 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(2)
