# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: RogueDiaryActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .RogueDiaryStage import *
from .Unk2700_PILILDPMNNA import *


@dataclass
class RogueDiaryActivityDetailInfo(betterproto.Message):
    stage_list: List["RogueDiaryStage"] = betterproto.message_field(11)
    is_have_progress: bool = betterproto.bool_field(10)
    is_content_closed: bool = betterproto.bool_field(2)
    cur_progress: "Unk2700_PILILDPMNNA" = betterproto.message_field(7)
