# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SalesmanTakeSpecialRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SalesmanTakeSpecialRewardRsp(betterproto.Message):
    """
    CmdId: 2124 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(12)
    schedule_id: int = betterproto.uint32_field(5)
