# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SalesmanStatusType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class SalesmanStatusType(betterproto.Enum):
    SALESMAN_STATUS_TYPE_NONE = 0
    SALESMAN_STATUS_TYPE_UNSTARTED = 1
    SALESMAN_STATUS_TYPE_STARTED = 2
    SALESMAN_STATUS_TYPE_DELIVERED = 3
