# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SalesmanTakeRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SalesmanTakeRewardRsp(betterproto.Message):
    """
    CmdId: 2110 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    position: int = betterproto.uint32_field(13)
    schedule_id: int = betterproto.uint32_field(7)
    reward_id: int = betterproto.uint32_field(9)
    retcode: int = betterproto.int32_field(11)
