# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SalesmanDeliverItemRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SalesmanDeliverItemRsp(betterproto.Message):
    """
    CmdId: 2104 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(9)
    retcode: int = betterproto.int32_field(15)
