# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SaveMainCoopRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class SaveMainCoopRsp(betterproto.Message):
    """
    CmdId: 1957 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(2)
    save_point_id_list: List[int] = betterproto.uint32_field(15)
    id: int = betterproto.uint32_field(14)
