# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneWeatherForcastReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SceneWeatherForcastReq(betterproto.Message):
    """
    CmdId: 3110 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    weather_area_id: int = betterproto.uint32_field(15)
