# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ScenePlayOwnerCheckRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ScenePlayOwnerCheckRsp(betterproto.Message):
    """
    CmdId: 4362 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    param_list: List[int] = betterproto.uint32_field(8)
    is_skip_match: bool = betterproto.bool_field(1)
    play_id: int = betterproto.uint32_field(9)
    wrong_uid: int = betterproto.uint32_field(5)
    retcode: int = betterproto.int32_field(3)
