# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneKickPlayerNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SceneKickPlayerNotify(betterproto.Message):
    """
    CmdId: 211 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    target_uid: int = betterproto.uint32_field(8)
    kicker_uid: int = betterproto.uint32_field(9)
