# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneEntityMoveReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .MotionInfo import *


@dataclass
class SceneEntityMoveReq(betterproto.Message):
    """CmdId: 290 EnetChannelId: 0 EnetIsReliable: true"""

    motion_info: "MotionInfo" = betterproto.message_field(7)
    scene_time: int = betterproto.uint32_field(4)
    entity_id: int = betterproto.uint32_field(8)
    reliable_seq: int = betterproto.uint32_field(15)
