# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneGalleryBounceConjuringInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SceneGalleryBounceConjuringInfo(betterproto.Message):
    total_destroyed_machine_count: int = betterproto.uint32_field(4)
    total_score: int = betterproto.uint32_field(6)
