# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneGalleryHomeSeekFurnitureInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto


@dataclass
class SceneGalleryHomeSeekFurnitureInfo(betterproto.Message):
    unk2700__k_d_b_e_n_b_b_o_d_g_p: int = betterproto.uint32_field(6)
    unk2700__d_d_h_o_j_h_o_i_c_b_l: Dict[int, int] = betterproto.map_field(
        8, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    unk2700__l_o_d_f_f_c_p_f_j_l_c: int = betterproto.uint32_field(12)
    unk2700__h_l_c_i_h_c_c_g_f_f_c: int = betterproto.uint32_field(9)
