# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneGalleryHomeBalloonInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SceneGalleryHomeBalloonInfo(betterproto.Message):
    score: int = betterproto.uint32_field(7)
