# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneDestroyEntityReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SceneDestroyEntityReq(betterproto.Message):
    """
    CmdId: 263 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    entity_id: int = betterproto.uint32_field(7)
