# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ScenePlayOwnerStartInviteReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ScenePlayOwnerStartInviteReq(betterproto.Message):
    """
    CmdId: 4385 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_skip_match: bool = betterproto.bool_field(8)
    play_id: int = betterproto.uint32_field(13)
