# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneGallerySalvageEscortInfoInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SceneGallerySalvageEscortInfoInfo(betterproto.Message):
    unk2700__n_e_c_h_e_c_i_d_c_e_g: int = betterproto.uint32_field(14)
    unk2700__a_m_j_e_k_e_j_l_o_g_j: int = betterproto.uint32_field(3)
    unk2700__m_c_f_m_m_i_d_n_l_i_f: int = betterproto.uint32_field(7)
    unk2700__f_f_c_c_l_g_i_f_g_i_p: int = betterproto.uint32_field(11)
