# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneEntityMoveNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .MotionInfo import *


@dataclass
class SceneEntityMoveNotify(betterproto.Message):
    """CmdId: 275 EnetChannelId: 0 EnetIsReliable: true IsAllowClient: true"""

    motion_info: "MotionInfo" = betterproto.message_field(6)
    entity_id: int = betterproto.uint32_field(8)
    scene_time: int = betterproto.uint32_field(15)
    reliable_seq: int = betterproto.uint32_field(2)
