# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneEntityDrownRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SceneEntityDrownRsp(betterproto.Message):
    """
    CmdId: 294 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(8)
    entity_id: int = betterproto.uint32_field(11)
