# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneGalleryFallInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto

from .FallPlayerInfo import *


@dataclass
class SceneGalleryFallInfo(betterproto.Message):
    scene_player_fall_info_map: Dict[int, "FallPlayerInfo"] = betterproto.map_field(
        12, betterproto.TYPE_UINT32, betterproto.TYPE_MESSAGE
    )
    end_time: int = betterproto.uint32_field(2)
