# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ScenePlayBattleInterruptNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ScenePlayBattleInterruptNotify(betterproto.Message):
    """
    CmdId: 4425 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    interrupt_state: int = betterproto.uint32_field(6)
    play_id: int = betterproto.uint32_field(5)
    play_type: int = betterproto.uint32_field(1)
