# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneGalleryBuoyantCombatInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SceneGalleryBuoyantCombatInfo(betterproto.Message):
    score: int = betterproto.uint32_field(6)
    kill_special_monster_count: int = betterproto.uint32_field(1)
    kill_monster_count: int = betterproto.uint32_field(14)
