# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneGallerySalvagePreventInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SceneGallerySalvagePreventInfo(betterproto.Message):
    unk2700__f_f_c_c_l_g_i_f_g_i_p: int = betterproto.uint32_field(7)
