# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ScenePlayInfoListNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ScenePlayInfo import *


@dataclass
class ScenePlayInfoListNotify(betterproto.Message):
    """
    CmdId: 4381 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    play_info_list: List["ScenePlayInfo"] = betterproto.message_field(6)
