# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ScenePlayOwnerInviteNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ScenePlayOwnerInviteNotify(betterproto.Message):
    """
    CmdId: 4371 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    invite_cd: int = betterproto.uint32_field(14)
    play_id: int = betterproto.uint32_field(5)
    is_remain_reward: bool = betterproto.bool_field(15)
