# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SceneMonsterInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .MonsterBornType import *
from .MonsterRoute import *
from .SceneFishInfo import *
from .SceneWeaponInfo import *
from .Unk3000_GNOPDGELABH import *


@dataclass
class SceneMonsterInfo(betterproto.Message):
    monster_id: int = betterproto.uint32_field(1)
    group_id: int = betterproto.uint32_field(2)
    config_id: int = betterproto.uint32_field(3)
    weapon_list: List["SceneWeaponInfo"] = betterproto.message_field(4)
    authority_peer_id: int = betterproto.uint32_field(5)
    affix_list: List[int] = betterproto.uint32_field(6)
    is_elite: bool = betterproto.bool_field(7)
    owner_entity_id: int = betterproto.uint32_field(8)
    summoned_tag: int = betterproto.uint32_field(9)
    summon_tag_map: Dict[int, int] = betterproto.map_field(
        10, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    pose_id: int = betterproto.uint32_field(11)
    born_type: "MonsterBornType" = betterproto.enum_field(12)
    block_id: int = betterproto.uint32_field(13)
    mark_flag: int = betterproto.uint32_field(14)
    title_id: int = betterproto.uint32_field(15)
    special_name_id: int = betterproto.uint32_field(16)
    attack_target_id: int = betterproto.uint32_field(17)
    monster_route: "MonsterRoute" = betterproto.message_field(18)
    ai_config_id: int = betterproto.uint32_field(19)
    level_route_id: int = betterproto.uint32_field(20)
    init_pose_id: int = betterproto.uint32_field(21)
    unk2800__j_e_g_l_e_n_p_d_p_n_i: bool = betterproto.bool_field(22)
    unk3000__c_c_k_j_d_c_b_d_e_k_d: int = betterproto.uint32_field(23)
    fish_info: "SceneFishInfo" = betterproto.message_field(50, group="content")
    fishtank_fish_info: "Unk3000_GNOPDGELABH" = betterproto.message_field(
        51, group="content"
    )
