# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SealBattleBeginNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .SealBattleType import *


@dataclass
class SealBattleBeginNotify(betterproto.Message):
    """
    CmdId: 289 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    seal_max_progress: int = betterproto.uint32_field(9)
    seal_entity_id: int = betterproto.uint32_field(1)
    seal_radius: int = betterproto.uint32_field(12)
    battle_type: "SealBattleType" = betterproto.enum_field(14)
