# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SeaLampCoinNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SeaLampCoinNotify(betterproto.Message):
    """
    CmdId: 2114 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    sea_lamp_coin: int = betterproto.uint32_field(8)
