# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SegmentInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SegmentInfo(betterproto.Message):
    offset: int = betterproto.uint32_field(3)
    module: int = betterproto.uint32_field(7)
    size: int = betterproto.uint32_field(8)
