# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SelectAsterMidDifficultyRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SelectAsterMidDifficultyRsp(betterproto.Message):
    """
    CmdId: 2180 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(15)
    schedule_id: int = betterproto.uint32_field(2)
    gadget_entity_id: int = betterproto.uint32_field(5)
    difficulty_id: int = betterproto.uint32_field(14)
