# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SelectAsterMidDifficultyReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SelectAsterMidDifficultyReq(betterproto.Message):
    """
    CmdId: 2134 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    gadget_entity_id: int = betterproto.uint32_field(13)
    schedule_id: int = betterproto.uint32_field(1)
    difficulty_id: int = betterproto.uint32_field(5)
