# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ServerCondMeetQuestListUpdateNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ServerCondMeetQuestListUpdateNotify(betterproto.Message):
    """
    CmdId: 406 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    del_quest_id_list: List[int] = betterproto.uint32_field(1)
    add_quest_id_list: List[int] = betterproto.uint32_field(12)
