# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ServerTimeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ServerTimeNotify(betterproto.Message):
    """CmdId: 99 EnetChannelId: 0 EnetIsReliable: true IsAllowClient: true"""

    server_time: int = betterproto.uint64_field(5)
