# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ServerAnnounceNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .AnnounceData import *


@dataclass
class ServerAnnounceNotify(betterproto.Message):
    """
    CmdId: 2197 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    announce_data_list: List["AnnounceData"] = betterproto.message_field(11)
