# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ServerAnnounceRevokeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class ServerAnnounceRevokeNotify(betterproto.Message):
    """
    CmdId: 2092 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    config_id_list: List[int] = betterproto.uint32_field(15)
