# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SetBattlePassViewedRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SetBattlePassViewedRsp(betterproto.Message):
    """
    CmdId: 2642 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(2)
    retcode: int = betterproto.int32_field(3)
