# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SetFriendEnterHomeOptionRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SetFriendEnterHomeOptionRsp(betterproto.Message):
    """
    CmdId: 4743 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(1)
