# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SetFriendRemarkNameReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SetFriendRemarkNameReq(betterproto.Message):
    """
    CmdId: 4042 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    uid: int = betterproto.uint32_field(10)
    remark_name: str = betterproto.string_field(8)
