# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SetOpenStateReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SetOpenStateReq(betterproto.Message):
    """
    CmdId: 165 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    key: int = betterproto.uint32_field(12)
    value: int = betterproto.uint32_field(5)
