# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SetPlayerNameRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SetPlayerNameRsp(betterproto.Message):
    """
    CmdId: 122 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(9)
    nick_name: str = betterproto.string_field(14)
