# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SetPlayerHeadImageRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ProfilePicture import *


@dataclass
class SetPlayerHeadImageRsp(betterproto.Message):
    """
    CmdId: 4047 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    profile_picture: "ProfilePicture" = betterproto.message_field(6)
    avatar_id: int = betterproto.uint32_field(5)
    retcode: int = betterproto.int32_field(1)
