# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SetPlayerHeadImageReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SetPlayerHeadImageReq(betterproto.Message):
    """
    CmdId: 4082 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    avatar_id: int = betterproto.uint32_field(7)
