# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SetPlayerBirthdayReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Birthday import *


@dataclass
class SetPlayerBirthdayReq(betterproto.Message):
    """
    CmdId: 4048 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    birthday: "Birthday" = betterproto.message_field(9)
