# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SignInInfoReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SignInInfoReq(betterproto.Message):
    """
    CmdId: 2512 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
