# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SkillResponse.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class SkillResponse(betterproto.Message):
    skill_depot_id: int = betterproto.uint32_field(13)
    skill_id_list: List[int] = betterproto.uint32_field(9)
