# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SocialDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SocialDataNotify(betterproto.Message):
    """
    CmdId: 4043 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_have_first_share: bool = betterproto.bool_field(11)
