# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SpiceActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .SpiceStage import *


@dataclass
class SpiceActivityDetailInfo(betterproto.Message):
    unk2700__i_g_m_h_n_d_n_g_n_p_g: int = betterproto.uint32_field(15)
    spice_stage_list: List["SpiceStage"] = betterproto.message_field(7)
    unk2700__k_i_a_h_j_k_g_o_l_g_o: int = betterproto.uint32_field(13)
