# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SpringUseRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SpringUseRsp(betterproto.Message):
    """
    CmdId: 1642 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    guid: int = betterproto.uint64_field(3)
    retcode: int = betterproto.int32_field(7)
