# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: StartBuoyantCombatGalleryRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class StartBuoyantCombatGalleryRsp(betterproto.Message):
    """
    CmdId: 8680 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    gallery_level: int = betterproto.uint32_field(12)
    retcode: int = betterproto.int32_field(5)
    gallery_id: int = betterproto.uint32_field(8)
