# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: StartRogueNormalCellChallengeReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class StartRogueNormalCellChallengeReq(betterproto.Message):
    """
    CmdId: 8205 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    dungeon_id: int = betterproto.uint32_field(3)
    cell_id: int = betterproto.uint32_field(8)
