# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: StartFishingRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class StartFishingRsp(betterproto.Message):
    """
    CmdId: 5807 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(1)
    fish_pool_id: int = betterproto.uint32_field(14)
