# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: StartRogueEliteCellChallengeReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .RogueEliteCellDifficultyType import *


@dataclass
class StartRogueEliteCellChallengeReq(betterproto.Message):
    """
    CmdId: 8242 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    difficulty: "RogueEliteCellDifficultyType" = betterproto.enum_field(1)
    dungeon_id: int = betterproto.uint32_field(11)
    cell_id: int = betterproto.uint32_field(4)
