# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: StoreItemDelNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .StoreType import *


@dataclass
class StoreItemDelNotify(betterproto.Message):
    """
    CmdId: 635 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    guid_list: List[int] = betterproto.uint64_field(12)
    store_type: "StoreType" = betterproto.enum_field(15)
