# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: StoreType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class StoreType(betterproto.Enum):
    STORE_TYPE_NONE = 0
    STORE_TYPE_PACK = 1
    STORE_TYPE_DEPOT = 2
