# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SummerTimeDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto

from .SummerTimeSprintBoatInfo import *
from .SummerTimeStageInfo import *


@dataclass
class SummerTimeDetailInfo(betterproto.Message):
    stage_map: Dict[int, "SummerTimeStageInfo"] = betterproto.map_field(
        3, betterproto.TYPE_UINT32, betterproto.TYPE_MESSAGE
    )
    content_close_time: int = betterproto.uint32_field(11)
    is_content_closed: bool = betterproto.bool_field(13)
    sprint_boat_info: "SummerTimeSprintBoatInfo" = betterproto.message_field(4)
