# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SummerTimeSprintBoatInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .SummerTimeSprintBoatRecord import *


@dataclass
class SummerTimeSprintBoatInfo(betterproto.Message):
    record_list: List["SummerTimeSprintBoatRecord"] = betterproto.message_field(7)
