# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SummerTimeSprintBoatRestartReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SummerTimeSprintBoatRestartReq(betterproto.Message):
    """
    CmdId: 8410 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    group_id: int = betterproto.uint32_field(10)
    schedule_id: int = betterproto.uint32_field(14)
