# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SummerTimeStageInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SummerTimeStageInfo(betterproto.Message):
    is_open: bool = betterproto.bool_field(13)
    open_time: int = betterproto.uint32_field(10)
    stage_id: int = betterproto.uint32_field(1)
