# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SumoAvatarInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SumoAvatarInfo(betterproto.Message):
    is_trial: bool = betterproto.bool_field(2)
    avatar_id: int = betterproto.uint64_field(1)
