# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SumoStageData.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .SumoTeamData import *


@dataclass
class SumoStageData(betterproto.Message):
    max_score: int = betterproto.uint32_field(1)
    open_time: int = betterproto.uint32_field(5)
    stage_id: int = betterproto.uint32_field(3)
    team_list: List["SumoTeamData"] = betterproto.message_field(7)
    is_open: bool = betterproto.bool_field(11)
