# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SumoDungeonSettleNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SumoDungeonSettleNotify(betterproto.Message):
    """
    CmdId: 8291 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    final_score: int = betterproto.uint32_field(7)
    difficulty_id: int = betterproto.uint32_field(14)
    kill_elite_monster_num: int = betterproto.uint32_field(15)
    stage_id: int = betterproto.uint32_field(12)
    kill_monster_num: int = betterproto.uint32_field(4)
    is_new_record: bool = betterproto.bool_field(5)
