# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SumoLeaveDungeonNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SumoLeaveDungeonNotify(betterproto.Message):
    """
    CmdId: 8640 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
