# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SumoSelectTeamAndEnterDungeonRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .SumoTeamData import *


@dataclass
class SumoSelectTeamAndEnterDungeonRsp(betterproto.Message):
    """
    CmdId: 8193 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(1)
    activity_id: int = betterproto.uint32_field(14)
    difficulty_id: int = betterproto.uint32_field(12)
    stage_id: int = betterproto.uint32_field(9)
    team_list: List["SumoTeamData"] = betterproto.message_field(2)
