# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: SumoSetNoSwitchPunishTimeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .SumoDungeonTeam import *


@dataclass
class SumoSetNoSwitchPunishTimeNotify(betterproto.Message):
    """
    CmdId: 8935 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    cur_team_index: int = betterproto.uint32_field(15)
    stage_id: int = betterproto.uint32_field(13)
    dungeon_team_list: List["SumoDungeonTeam"] = betterproto.message_field(11)
    no_switch_punish_time: int = betterproto.uint32_field(2)
    next_valid_switch_time: int = betterproto.uint32_field(14)
    activity_id: int = betterproto.uint32_field(9)
