# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeCoopRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TakeCoopRewardRsp(betterproto.Message):
    """
    CmdId: 1985 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(9)
    reward_config_id: int = betterproto.uint32_field(1)
