# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeBattlePassRewardReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .BattlePassRewardTakeOption import *


@dataclass
class TakeBattlePassRewardReq(betterproto.Message):
    """
    CmdId: 2602 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    take_option_list: List["BattlePassRewardTakeOption"] = betterproto.message_field(12)
