# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeInvestigationRewardReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TakeInvestigationRewardReq(betterproto.Message):
    """
    CmdId: 1912 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    id: int = betterproto.uint32_field(5)
