# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeCompoundOutputReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TakeCompoundOutputReq(betterproto.Message):
    """
    CmdId: 174 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    compound_group_id: int = betterproto.uint32_field(3)
    compound_id: int = betterproto.uint32_field(10)
