# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeOfferingLevelRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


@dataclass
class TakeOfferingLevelRewardRsp(betterproto.Message):
    """
    CmdId: 2911 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    offering_id: int = betterproto.uint32_field(3)
    take_level: int = betterproto.uint32_field(4)
    retcode: int = betterproto.int32_field(8)
    item_list: List["ItemParam"] = betterproto.message_field(2)
