# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeReunionFirstGiftRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TakeReunionFirstGiftRewardRsp(betterproto.Message):
    """
    CmdId: 5057 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    reward_id: int = betterproto.int32_field(9)
    retcode: int = betterproto.int32_field(15)
