# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeEffigyRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TakeEffigyRewardRsp(betterproto.Message):
    """
    CmdId: 2007 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(15)
    reward_index: int = betterproto.uint32_field(7)
