# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeInvestigationRewardRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TakeInvestigationRewardRsp(betterproto.Message):
    """
    CmdId: 1922 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(4)
    id: int = betterproto.uint32_field(12)
