# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeResinCardDailyRewardReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TakeResinCardDailyRewardReq(betterproto.Message):
    """
    CmdId: 4122 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    product_config_id: int = betterproto.uint32_field(14)
