# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TakeCityReputationParentQuestReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class TakeCityReputationParentQuestReq(betterproto.Message):
    """
    CmdId: 2821 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    city_id: int = betterproto.uint32_field(1)
    parent_quest_list: List[int] = betterproto.uint32_field(6)
