# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TowerEnterLevelReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TowerEnterLevelReq(betterproto.Message):
    """
    CmdId: 2431 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    enter_point_id: int = betterproto.uint32_field(3)
