# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TowerTeamSelectReq.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .TowerTeam import *


@dataclass
class TowerTeamSelectReq(betterproto.Message):
    """
    CmdId: 2421 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    tower_team_list: List["TowerTeam"] = betterproto.message_field(11)
    floor_id: int = betterproto.uint32_field(10)
