# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TowerDailyRewardProgressChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TowerDailyRewardProgressChangeNotify(betterproto.Message):
    """
    CmdId: 2435 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    daily_floor_id: int = betterproto.uint32_field(15)
    daily_level_index: int = betterproto.uint32_field(9)
