# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TowerTeam.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class TowerTeam(betterproto.Message):
    tower_team_id: int = betterproto.uint32_field(3)
    avatar_guid_list: List[int] = betterproto.uint64_field(14)
