# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TowerFloorRecord.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .TowerLevelRecord import *


@dataclass
class TowerFloorRecord(betterproto.Message):
    floor_star_reward_progress: int = betterproto.uint32_field(15)
    passed_level_map: Dict[int, int] = betterproto.map_field(
        8, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    floor_id: int = betterproto.uint32_field(12)
    passed_level_record_list: List["TowerLevelRecord"] = betterproto.message_field(2)
