# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TowerAllDataRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto

from .TowerCurLevelRecord import *
from .TowerFloorRecord import *
from .TowerMonthlyBrief import *


@dataclass
class TowerAllDataRsp(betterproto.Message):
    """
    CmdId: 2473 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    tower_schedule_id: int = betterproto.uint32_field(10)
    daily_level_index: int = betterproto.uint32_field(9)
    skip_floor_granted_reward_item_map: Dict[int, int] = betterproto.map_field(
        12, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    is_first_interact: bool = betterproto.bool_field(3)
    is_finished_entrance_floor: bool = betterproto.bool_field(1)
    tower_floor_record_list: List["TowerFloorRecord"] = betterproto.message_field(5)
    daily_floor_id: int = betterproto.uint32_field(11)
    commemorative_reward_id: int = betterproto.uint32_field(13)
    last_schedule_monthly_brief: "TowerMonthlyBrief" = betterproto.message_field(1222)
    next_schedule_change_time: int = betterproto.uint32_field(6)
    valid_tower_record_num: int = betterproto.uint32_field(7)
    skip_to_floor_index: int = betterproto.uint32_field(2)
    floor_open_time_map: Dict[int, int] = betterproto.map_field(
        4, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    cur_level_record: "TowerCurLevelRecord" = betterproto.message_field(15)
    retcode: int = betterproto.int32_field(8)
    schedule_start_time: int = betterproto.uint32_field(914)
    monthly_brief: "TowerMonthlyBrief" = betterproto.message_field(14)
