# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TowerLevelStarCondData.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TowerLevelStarCondData(betterproto.Message):
    unk2700__h_i_f_m_j_m_a_h_e_m_b: bool = betterproto.bool_field(15)
    cond_value: int = betterproto.uint32_field(9)
    is_pause: bool = betterproto.bool_field(13)
    star_cond_index: int = betterproto.uint32_field(6)
