# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TowerCurLevelRecord.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .TowerTeam import *


@dataclass
class TowerCurLevelRecord(betterproto.Message):
    tower_team_list: List["TowerTeam"] = betterproto.message_field(8)
    is_empty: bool = betterproto.bool_field(6)
    buff_id_list: List[int] = betterproto.uint32_field(4)
    unk2700__c_b_p_n_p_e_b_m_p_o_h: bool = betterproto.bool_field(2)
    cur_level_index: int = betterproto.uint32_field(1)
    cur_floor_id: int = betterproto.uint32_field(15)
