# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TowerLevelEndNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


class TowerLevelEndNotifyContinueStateType(betterproto.Enum):
    CONTINUE_STATE_TYPE_CAN_NOT_CONTINUE = 0
    CONTINUE_STATE_TYPE_CAN_ENTER_NEXT_LEVEL = 1
    CONTINUE_STATE_TYPE_CAN_ENTER_NEXT_FLOOR = 2


@dataclass
class TowerLevelEndNotify(betterproto.Message):
    """
    CmdId: 2495 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    next_floor_id: int = betterproto.uint32_field(4)
    reward_item_list: List["ItemParam"] = betterproto.message_field(12)
    continue_state: int = betterproto.uint32_field(15)
    is_success: bool = betterproto.bool_field(5)
    finished_star_cond_list: List[int] = betterproto.uint32_field(6)
