# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TrialAvatarInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Item import *
from .TrialAvatarGrantRecord import *


@dataclass
class TrialAvatarInfo(betterproto.Message):
    trial_avatar_id: int = betterproto.uint32_field(1)
    trial_equip_list: List["Item"] = betterproto.message_field(2)
    grant_record: "TrialAvatarGrantRecord" = betterproto.message_field(3)
