# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TrialAvatarInDungeonIndexNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class TrialAvatarInDungeonIndexNotify(betterproto.Message):
    """
    CmdId: 2186 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    trial_avatar_index_id: int = betterproto.uint32_field(14)
