# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TrialAvatarActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .TrialAvatarActivityRewardDetailInfo import *


@dataclass
class TrialAvatarActivityDetailInfo(betterproto.Message):
    reward_info_list: List[
        "TrialAvatarActivityRewardDetailInfo"
    ] = betterproto.message_field(13)
