# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UgcActivityDetailInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_MMJJMKMHANL import *


@dataclass
class UgcActivityDetailInfo(betterproto.Message):
    unk2700__g_m_i_c_f_a_d_l_a_m_c: bool = betterproto.bool_field(10)
    unk2700__f_d_d_c_m_g_k_d_o_c_c: int = betterproto.uint32_field(12)
    unk2700__i_l_c_a_p_j_b_a_f_o_i: List[
        "Unk2700_MMJJMKMHANL"
    ] = betterproto.message_field(5)
    unk2700__p_n_o_c_e_l_c_o_f_n_k: bool = betterproto.bool_field(11)
