# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UnionCmd.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class UnionCmd(betterproto.Message):
    body: bytes = betterproto.bytes_field(14)
    message_id: int = betterproto.uint32_field(8)
