# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UnionCmdNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .UnionCmd import *


@dataclass
class UnionCmdNotify(betterproto.Message):
    """CmdId: 5 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true"""

    cmd_list: List["UnionCmd"] = betterproto.message_field(1)
