# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_AIMMLILLOKB.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto


@dataclass
class Unk2700_AIMMLILLOKB(betterproto.Message):
    unk2700__d_l_k_p_h_f_d_e_d_n_f: Dict[int, int] = betterproto.map_field(
        3, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    uid: int = betterproto.uint32_field(6)
    unk2700__h_d_j_p_j_b_i_f_m_c_o: Dict[int, int] = betterproto.map_field(
        13, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
