# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_JPGAAHJBLKB.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_JPGAAHJBLKB(betterproto.Message):
    avatar_id: int = betterproto.uint64_field(3)
    is_trial: bool = betterproto.bool_field(13)
