# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_ONCHFHBBCBN.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_OCDMIOKNHHH import *


@dataclass
class Unk2700_ONCHFHBBCBN(betterproto.Message):
    hit_count: int = betterproto.uint32_field(12)
    score: int = betterproto.uint32_field(11)
    player_info: "Unk2700_OCDMIOKNHHH" = betterproto.message_field(5)
    timestamp: int = betterproto.uint32_field(2)
