# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_KMIDCPLAGMN.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto


@dataclass
class Unk2700_KMIDCPLAGMN(betterproto.Message):
    """
    CmdId: 8848 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(7)
    retcode: int = betterproto.int32_field(3)
    unk2700__i_f_c_n_g_i_p_p_o_a_e: Dict[int, int] = betterproto.map_field(
        14, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
