# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_FGJBPNIKNDE.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_FGJBPNIKNDE(betterproto.Message):
    """
    CmdId: 8398 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
