# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IGAFEBCFJEJ.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_IGAFEBCFJEJ(betterproto.Message):
    unk2700__e_p_e_f_c_c_m_p_l_c_p: int = betterproto.uint64_field(13)
    unk2700__g_c_g_d_a_b_p_l_c_f_k: int = betterproto.uint32_field(3)
