# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_KNGDOIDOFFB.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_MOFABPNGIKP import *


@dataclass
class Unk2700_KNGDOIDOFFB(betterproto.Message):
    unk2700__h_l_e_m_p_i_k_m_b_m_p: int = betterproto.uint32_field(6)
    reason: "Unk2700_MOFABPNGIKP" = betterproto.enum_field(4)
    unk2700__o_m_c_c_f_b_b_d_j_m_i: int = betterproto.uint32_field(1)
