# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BKGPMAHMHIG.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_BKGPMAHMHIG(betterproto.Message):
    """
    CmdId: 8561 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__p_h_g_m_k_g_e_m_c_f_f: bool = betterproto.bool_field(2)
    level_id: int = betterproto.uint32_field(12)
    card_id: int = betterproto.uint32_field(9)
