# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_MIBBHAEMAGI.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_BMBAIACNLDF import *
from .Unk2700_ELMEOJFCOFH import *
from .Unk2700_OHBMICGFIIK import *
from .Unk2700_PHGGAEDHLBN import *


@dataclass
class Unk2700_MIBBHAEMAGI(betterproto.Message):
    unk2700__j_g_f_d_o_d_p_b_g_f_l: "Unk2700_PHGGAEDHLBN" = betterproto.message_field(2)
    unk2700__g_b_c_g_g_d_o_n_m_c_d: bool = betterproto.bool_field(13)
    unk2700__i_k_g_o_m_k_l_a_j_l_h: "Unk2700_OHBMICGFIIK" = betterproto.message_field(7)
    unk2700__o_n_o_o_j_b_e_a_b_o_e: int = betterproto.uint64_field(10)
    unk2700__b_p_m_l_p_h_i_m_j_a_f: int = betterproto.uint32_field(14)
    tag_list: List[int] = betterproto.uint32_field(15)
    dungeon_id: int = betterproto.uint32_field(5)
    unk2700__d_p_p_i_l_i_m_g_o_k_h: int = betterproto.uint32_field(12)
    state: "Unk2700_BMBAIACNLDF" = betterproto.enum_field(1)
    unk2700__p_c_f_i_k_j_e_d_e_g_n: "Unk2700_ELMEOJFCOFH" = betterproto.message_field(4)
