# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BBMKJGPMIOE.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_KIGGOKAEFHM import *


@dataclass
class Unk2700_BBMKJGPMIOE(betterproto.Message):
    """
    CmdId: 8580 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__c_n_j_p_c_c_e_c_b_p_d: "Unk2700_KIGGOKAEFHM" = betterproto.message_field(
        14
    )
