# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_HKADKMFMBPG.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto


@dataclass
class Unk2700_HKADKMFMBPG(betterproto.Message):
    """
    CmdId: 8017 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__i_f_c_n_g_i_p_p_o_a_e: Dict[int, int] = betterproto.map_field(
        2, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
    schedule_id: int = betterproto.uint32_field(14)
