# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IPGJEAEFJMM_ServerRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .DropSubfieldType import *
from .MusicBriefInfo import *
from .MusicRecord import *
from .Unk2700_OPEBMJPOOBL import *


@dataclass
class Unk2700_IPGJEAEFJMM_ServerRsp(betterproto.Message):
    """
    CmdId: 6318 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__c_e_p_g_m_k_a_h_h_c_d: int = betterproto.uint64_field(15)
    unk2700__k_h_b_d_a_p_g_d_o_j_a: "Unk2700_OPEBMJPOOBL" = betterproto.enum_field(10)
    retcode: int = betterproto.int32_field(2)
    unk2700__m_j_n_i_h_f_c_k_j_m_n: "DropSubfieldType" = betterproto.enum_field(14)
    music_record: "MusicRecord" = betterproto.message_field(
        4, group="Unk2700_MIPPJKBFLOO"
    )
    music_brief_info: "MusicBriefInfo" = betterproto.message_field(
        1819, group="Unk2700_ILHNBMNOMHO"
    )
