# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_FEAENJPINFJ.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_FEAENJPINFJ(betterproto.Message):
    skill_id: int = betterproto.uint32_field(2)
    is_unlock: bool = betterproto.bool_field(11)
    unk2700__l_a_p_i_b_e_c_m_g_o_b: int = betterproto.uint32_field(1)
    unk2700__l_k_n_c_b_o_o_j_c_g_i: int = betterproto.uint32_field(14)
