# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BLCHNMCGJCJ.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_BLCHNMCGJCJ(betterproto.Message):
    """
    CmdId: 8948 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(11)
