# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_EAGIANJBNGK_ClientReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ReliquaryRequest import *
from .SkillRequest import *
from .Unk2800_JBEDBFJFEIH import *


@dataclass
class Unk2700_EAGIANJBNGK_ClientReq(betterproto.Message):
    """
    CmdId: 151 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    avatar_id: int = betterproto.uint32_field(9)
    skill_request: "SkillRequest" = betterproto.message_field(553, group="detail")
    reliquary_request: "ReliquaryRequest" = betterproto.message_field(
        1993, group="detail"
    )
    element_reliquary_request: "Unk2800_JBEDBFJFEIH" = betterproto.message_field(
        1489, group="detail"
    )
