# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BLNOMGJJLOI.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_BLNOMGJJLOI(betterproto.Message):
    """
    CmdId: 8854 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(1)
    unk2700__c_k_g_j_e_o_o_k_f_i_f: int = betterproto.uint32_field(8)
