# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_FLGMLEFJHBB_ClientReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_FLGMLEFJHBB_ClientReq(betterproto.Message):
    """
    CmdId: 6210 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__f_g_h_p_h_c_p_a_f_k_j: bool = betterproto.bool_field(5)
    unk2700__o_n_o_o_j_b_e_a_b_o_e: int = betterproto.uint64_field(10)
