# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_FKCDCGCBIEA_ServerNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_NAPLFKNOECD import *


@dataclass
class Unk2700_FKCDCGCBIEA_ServerNotify(betterproto.Message):
    """
    CmdId: 6276 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    var_list: List["Unk2700_NAPLFKNOECD"] = betterproto.message_field(5)
    unk2700__j_e_m_d_o_a_h_d_m_b_p: str = betterproto.string_field(9)
    unk2700__a_n_b_e_g_p_c_l_a_a_o: bool = betterproto.bool_field(15)
    play_type: int = betterproto.uint32_field(7)
    unk3000__j_h_a_m_n_n_j_m_o_c_i: bool = betterproto.bool_field(4)
