# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_EEPNCOAEKBM.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk2700_EEPNCOAEKBM(betterproto.Enum):
    Unk2700_EEPNCOAEKBM_Unk2700_EAFEANPNJLO = 0
    Unk2700_EEPNCOAEKBM_Unk2700_PAPMIPKGFJK = 1
    Unk2700_EEPNCOAEKBM_Unk2700_CONEKODEFHL = 2
    Unk2700_EEPNCOAEKBM_Unk2700_KABLOGENHFI = 3
