# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_NCPLKHGCOAH.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_NCPLKHGCOAH(betterproto.Message):
    """
    CmdId: 8767 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    entity_id: int = betterproto.uint32_field(11)
