# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_EHFBIEDHILL.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_EHFBIEDHILL(betterproto.Message):
    """
    CmdId: 8882 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(2)
    activity_id: int = betterproto.uint32_field(4)
