# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_KHLJJPGOELG_ClientReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_KLPINMKOEPE import *
from .Unk2700_PHGGAEDHLBN import *


@dataclass
class Unk2700_KHLJJPGOELG_ClientReq(betterproto.Message):
    """
    CmdId: 6225 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__m_d_i_j_o_h_e_f_f_h_i: "Unk2700_KLPINMKOEPE" = betterproto.message_field(5)
    unk2700__f_h_h_l_m_j_a_l_l_m_n: bool = betterproto.bool_field(7)
    unk2700__j_g_f_d_o_d_p_b_g_f_l: "Unk2700_PHGGAEDHLBN" = betterproto.message_field(
        13
    )
