# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IHOOCHJACEL.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_BGKMAAINPCO import *


@dataclass
class Unk2700_IHOOCHJACEL(betterproto.Message):
    """
    CmdId: 8325 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    level_id: int = betterproto.uint32_field(7)
    unk2700__g_m_a_e_h_k_m_d_i_g_g: List[
        "Unk2700_BGKMAAINPCO"
    ] = betterproto.message_field(13)
    difficulty_id: int = betterproto.uint32_field(10)
