# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_NNMDBDNIMHN_ServerRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_KPNPJPPHOKA import *


@dataclass
class Unk2700_NNMDBDNIMHN_ServerRsp(betterproto.Message):
    """
    CmdId: 4538 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__i_f_n_l_j_d_c_j_j_e_d: "Unk2700_KPNPJPPHOKA" = betterproto.message_field(7)
    retcode: int = betterproto.int32_field(11)
    unk2700__m_a_p_j_l_i_d_a_c_p_n: int = betterproto.uint32_field(1)
