# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BJJOMPDLNAL.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Uint32Pair import *


@dataclass
class Unk2700_BJJOMPDLNAL(betterproto.Message):
    monster_list: List["Uint32Pair"] = betterproto.message_field(1)
    unk2700__n_i_l_l_a_b_g_a_a_l_o: bool = betterproto.bool_field(3)
    config_id: int = betterproto.uint32_field(7)
