# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_JIPMJPAKIKE.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2800_JIPMJPAKIKE(betterproto.Message):
    is_finished: bool = betterproto.bool_field(7)
    unk2800__m_m_p_e_l_b_b_n_f_o_d: int = betterproto.uint32_field(10)
    is_open: bool = betterproto.bool_field(5)
    unk2800__m_g_p_e_o_d_n_k_e_e_c: int = betterproto.uint32_field(6)
