# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_PPIBANCGGNI.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_MOFABPNGIKP import *


@dataclass
class Unk2700_PPIBANCGGNI(betterproto.Message):
    reason: "Unk2700_MOFABPNGIKP" = betterproto.enum_field(7)
