# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_ADIGEBEIJBA.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_ADIGEBEIJBA(betterproto.Message):
    is_trial: bool = betterproto.bool_field(8)
    avatar_guid: int = betterproto.uint64_field(11)
