# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_IECLGDFOMFJ.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2800_PHPHMILPOLC import *


@dataclass
class Unk2800_IECLGDFOMFJ(betterproto.Message):
    """
    CmdId: 8513 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(14)
    unk2800__k_o_m_i_p_k_k_k_o_b_e: List[
        "Unk2800_PHPHMILPOLC"
    ] = betterproto.message_field(3)
    activity_id: int = betterproto.uint32_field(10)
