# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BMBAIACNLDF.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk2700_BMBAIACNLDF(betterproto.Enum):
    Unk2700_BMBAIACNLDF_Unk2700_KOGCCKHAIBJ = 0
    Unk2700_BMBAIACNLDF_Unk2700_OHHELAGBFFO = 1
    Unk2700_BMBAIACNLDF_Unk2700_BIGKGGIMNCD = 2
