# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_JLHKOLGFAMI.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_JLHKOLGFAMI(betterproto.Message):
    level_id: int = betterproto.uint32_field(10)
    score: int = betterproto.uint32_field(7)
    unk2700__h_k_f_e_b_b_c_m_b_h_l: int = betterproto.uint32_field(5)
    unk2700__f_h_e_h_g_d_a_b_a_l_e: int = betterproto.uint32_field(2)
