# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_OOKIPFHPJMG.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2800_OOKIPFHPJMG(betterproto.Message):
    """
    CmdId: 21054 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_success: bool = betterproto.bool_field(8)
