# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_JOEPIGNPDGH.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk2700_JOEPIGNPDGH(betterproto.Enum):
    Unk2700_JOEPIGNPDGH_Unk2700_GIGONJIGKBM = 0
    Unk2700_JOEPIGNPDGH_Unk2700_AEKNMJMKIPN = 1
    Unk2700_JOEPIGNPDGH_Unk2700_LKCIHNNHIFO = 2
    Unk2700_JOEPIGNPDGH_Unk2700_EPAPGLMBAEB = 3
