# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IOLMLCCBAKP.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_BGKMAAINPCO import *


@dataclass
class Unk2700_IOLMLCCBAKP(betterproto.Message):
    unk2700__g_m_a_e_h_k_m_d_i_g_g: List[
        "Unk2700_BGKMAAINPCO"
    ] = betterproto.message_field(10)
    is_open: bool = betterproto.bool_field(9)
    level_id: int = betterproto.uint32_field(14)
    best_score: int = betterproto.uint32_field(5)
