# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_MBKLJLMLIKF.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2800_MBKLJLMLIKF(betterproto.Message):
    stage_id: int = betterproto.uint32_field(13)
    is_open: bool = betterproto.bool_field(14)
    best_score: int = betterproto.uint32_field(4)
