# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IMMPPANFEPP.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_IMMPPANFEPP(betterproto.Message):
    guid: int = betterproto.uint32_field(11)
    unk2700__m_a_a_b_p_j_m_p_i_l_d: int = betterproto.uint32_field(6)
