# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_GHONKKEGHGL.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_LHPELFJPPOD import *


@dataclass
class Unk2700_GHONKKEGHGL(betterproto.Message):
    is_open: bool = betterproto.bool_field(8)
    challenge_info_list: List["Unk2700_LHPELFJPPOD"] = betterproto.message_field(9)
    stage_id: int = betterproto.uint32_field(15)
