# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_APOBKAEHMEL.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


@dataclass
class Unk2700_APOBKAEHMEL(betterproto.Message):
    """
    CmdId: 8216 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__e_e_n_o_c_h_n_i_a_j_l: List["ItemParam"] = betterproto.message_field(1)
