# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_MHPCNKJGEJN.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_MHPCNKJGEJN(betterproto.Message):
    unk3000__c_n_g_d_f_a_g_e_a_c_d: int = betterproto.uint32_field(3)
