# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_KKEDIMOKCGD.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_EEPNCOAEKBM import *


@dataclass
class Unk2700_KKEDIMOKCGD(betterproto.Message):
    """
    CmdId: 8218 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__n_h_b_d_a_f_b_h_n_m_h: bool = betterproto.bool_field(9)
    unk2700__k_e_a_g_h_c_i_i_g_g_n: "Unk2700_EEPNCOAEKBM" = betterproto.enum_field(10)
