# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BCPHPHGOKGN.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_BCPHPHGOKGN(betterproto.Message):
    """
    CmdId: 8227 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    level_id: int = betterproto.uint32_field(6)
