# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_AGIDJODJNEA.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk2700_AGIDJODJNEA(betterproto.Enum):
    Unk2700_AGIDJODJNEA_Unk2700_OAEGNAOPMFB = 0
    Unk2700_AGIDJODJNEA_Unk2700_DLDNOOGCFNB = 1
    Unk2700_AGIDJODJNEA_Unk2700_PONLJLLPNPI = 2
    Unk2700_AGIDJODJNEA_Unk2700_POHNGFOIPAH = 3
