# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_CHLNIDHHGLE.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_MOFABPNGIKP import *


@dataclass
class Unk2700_CHLNIDHHGLE(betterproto.Message):
    score: int = betterproto.uint32_field(8)
    reason: "Unk2700_MOFABPNGIKP" = betterproto.enum_field(14)
    hit_count: int = betterproto.uint32_field(10)
    owner_uid: int = betterproto.uint32_field(6)
