# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_LDJLMCAHHEN.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_HJLFNKLPFBH import *


@dataclass
class Unk2700_LDJLMCAHHEN(betterproto.Message):
    """
    CmdId: 8748 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__o_h_e_c_o_o_h_p_n_h_g: List[
        "Unk2700_HJLFNKLPFBH"
    ] = betterproto.message_field(6)
