# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_OHDDPIFAPPD.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Unk2700_OHDDPIFAPPD(betterproto.Message):
    """
    CmdId: 8125 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_new: bool = betterproto.bool_field(10)
    unk2700__g_j_o_f_n_j_g_e_d_d_e: int = betterproto.uint32_field(3)
    retcode: int = betterproto.int32_field(4)
    unk2700__b_p_n_c_e_c_a_f_p_d_k: int = betterproto.uint32_field(6)
    quest_id: int = betterproto.uint32_field(15)
    affix_list: List[int] = betterproto.uint32_field(2)
