# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_CCEOEOHLAPK.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class Unk2700_CCEOEOHLAPK(betterproto.Message):
    is_hint_valid: bool = betterproto.bool_field(3)
    hint_center_pos: "Vector" = betterproto.message_field(8)
    group_id: int = betterproto.uint32_field(6)
    config_id: int = betterproto.uint32_field(9)
