# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_MKLLNAHEJJC_ServerRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_CCEOEOHLAPK import *


@dataclass
class Unk2700_MKLLNAHEJJC_ServerRsp(betterproto.Message):
    """
    CmdId: 4287 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__c_o_i_e_l_i_g_e_a_c_l: "Unk2700_CCEOEOHLAPK" = betterproto.message_field(9)
