# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_JDMPECKFGIG_ServerNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_JDMPECKFGIG_ServerNotify(betterproto.Message):
    """
    CmdId: 4639 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_enter_edit_mode: bool = betterproto.bool_field(15)
