# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BBLJNCKPKPN.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_BBLJNCKPKPN(betterproto.Message):
    """
    CmdId: 8192 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    level_id: int = betterproto.uint32_field(8)
    stage_id: int = betterproto.uint32_field(7)
