# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BIEMCDLIFOD.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Vector import *


@dataclass
class Unk2700_BIEMCDLIFOD(betterproto.Message):
    guid: int = betterproto.uint32_field(11)
    spawn_pos: "Vector" = betterproto.message_field(14)
    included_furniture_index_list: List[int] = betterproto.int32_field(12)
