# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IMGLPJNBHCH.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_IMGLPJNBHCH(betterproto.Message):
    unk2700__i_i_e_i_p_i_n_h_l_b_n: int = betterproto.uint32_field(5)
    unk2700__a_i_k_k_j_g_o_l_l_h_k: int = betterproto.uint32_field(13)
