# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_KHLHFFHGEHA.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2800_FGFMMFAKDEL import *


@dataclass
class Unk2800_KHLHFFHGEHA(betterproto.Message):
    """
    CmdId: 21834 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_success: bool = betterproto.bool_field(4)
    unk2800__i_c_n_c_e_k_i_j_n_j_a: bool = betterproto.bool_field(12)
    unk2800__e_g_j_d_b_b_g_n_m_f_i: List[
        "Unk2800_FGFMMFAKDEL"
    ] = betterproto.message_field(9)
    level_id: int = betterproto.uint32_field(5)
