# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BLHIGLFDHFA_ServerNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_BLHIGLFDHFA_ServerNotify(betterproto.Message):
    """
    CmdId: 4654 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    trigger_entity_id: int = betterproto.uint32_field(10)
    cur_score: int = betterproto.uint32_field(9)
    add_score: int = betterproto.uint32_field(7)
    gallery_id: int = betterproto.uint32_field(5)
