# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_GIFGEDBCPFC_ServerRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_GIFGEDBCPFC_ServerRsp(betterproto.Message):
    """
    CmdId: 417 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(1)
    unk2700__k_h_d_d_i_j_n_o_i_c_k: int = betterproto.uint64_field(14)
    parent_quest_id: int = betterproto.uint32_field(10)
