# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_PHPHMILPOLC.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2800_FDLKPKFOIIK import *


@dataclass
class Unk2800_PHPHMILPOLC(betterproto.Message):
    state: "Unk2800_FDLKPKFOIIK" = betterproto.enum_field(10)
    unk2800__c_l_o_c_m_p_f_b_g_m_d: int = betterproto.uint32_field(4)
