# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_JCBJHCFEONO.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_NOGODJOJDGF import *


@dataclass
class Unk2700_JCBJHCFEONO(betterproto.Message):
    unk2700__a_i_m_b_f_n_o_k_k_h_e: List[
        "Unk2700_NOGODJOJDGF"
    ] = betterproto.message_field(8)
    timestamp: int = betterproto.uint32_field(3)
