# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_FCJOEKKHPLB.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Unk2700_FCJOEKKHPLB(betterproto.Message):
    unk2700__a_m_j_k_j_d_f_k_o_h_f: int = betterproto.uint32_field(2)
    unk2700__j_f_b_l_e_p_o_m_g_l_c: int = betterproto.uint32_field(3)
    unk2700__n_d_j_k_p_h_l_i_a_l_k: int = betterproto.uint32_field(1)
    unk2700__h_k_k_p_k_b_e_k_c_m_e: int = betterproto.uint32_field(6)
    unk2700__a_d_p_p_e_o_e_l_m_b_p: List[int] = betterproto.uint32_field(4)
    unk2700__m_l_c_e_o_f_a_m_b_f_m: int = betterproto.uint32_field(7)
