# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_NAEHEDLGLKA.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_NAEHEDLGLKA(betterproto.Message):
    """
    CmdId: 8257 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
