# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_LLGDCAKMCKL.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_DMPIJLBHEAE import *


@dataclass
class Unk2700_LLGDCAKMCKL(betterproto.Message):
    challenge_info_list: List["Unk2700_DMPIJLBHEAE"] = betterproto.message_field(9)
    is_open: bool = betterproto.bool_field(10)
    stage_id: int = betterproto.uint32_field(2)
