# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_HGFFGMCODNC.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class Unk2700_HGFFGMCODNC(betterproto.Message):
    group_id: int = betterproto.uint32_field(4)
    gadget_id: int = betterproto.uint32_field(7)
    pos: "Vector" = betterproto.message_field(8)
