# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_PHGGAEDHLBN.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Unk2700_PHGGAEDHLBN(betterproto.Message):
    unk2700__a_n_h_j_a_f_d_e_a_c_f: List[int] = betterproto.uint32_field(1)
    unk2700__i_b_d_c_f_a_m_b_g_o_k: bool = betterproto.bool_field(14)
    unk2700__k_e_n_g_e_g_j_g_a_e_l: int = betterproto.uint32_field(6)
    unk2700__d_o_i_m_m_b_j_d_a_l_b: int = betterproto.uint32_field(4)
    unk2700__f_k_l_b_c_n_l_b_b_n_m: bool = betterproto.bool_field(3)
    unk2700__i_f_n_f_c_n_n_b_p_i_b: int = betterproto.uint32_field(10)
    unk2700__p_b_b_p_g_f_m_n_m_n_j: int = betterproto.uint32_field(9)
