# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_OKEKCGDGPDA.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_OKEKCGDGPDA(betterproto.Message):
    """
    CmdId: 8396 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    gallery_id: int = betterproto.uint32_field(4)
