# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_NOCLNCCJEGK.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk2700_NOCLNCCJEGK(betterproto.Enum):
    Unk2700_NOCLNCCJEGK_NONE = 0
    Unk2700_NOCLNCCJEGK_Unk2700_ODIJEIGEGED = 1
