# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IDGCNKONBBJ.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_IDGCNKONBBJ(betterproto.Message):
    """
    CmdId: 8793 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(4)
