# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_LNMFIHNFKOO.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


@dataclass
class Unk2700_LNMFIHNFKOO(betterproto.Message):
    """
    CmdId: 8572 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    uid: int = betterproto.uint32_field(12)
    item_list: List["ItemParam"] = betterproto.message_field(11)
