# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_JCPNICABMAF.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2800_IMLDGLIMODE import *


@dataclass
class Unk2800_JCPNICABMAF(betterproto.Message):
    """
    CmdId: 5504 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    coin: int = betterproto.uint32_field(10)
    stage: "Unk2800_IMLDGLIMODE" = betterproto.enum_field(8)
    kill_monster_count: int = betterproto.uint32_field(4)
    progress: int = betterproto.uint32_field(15)
