# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_DGLIANMBMPA.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_DGLIANMBMPA(betterproto.Message):
    """
    CmdId: 8342 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__f_h_n_e_c_p_g_f_p_b_k: int = betterproto.uint32_field(9)
    unk2700__o_a_k_e_b_j_p_b_n_m_a: int = betterproto.uint32_field(2)
    is_new_record: bool = betterproto.bool_field(7)
    is_success: bool = betterproto.bool_field(3)
    gallery_id: int = betterproto.uint32_field(13)
    remain_time: int = betterproto.uint32_field(4)
    score: int = betterproto.uint32_field(11)
    unk2700__f_c_o_m_h_l_j_g_f_l_k: int = betterproto.uint32_field(15)
