# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_ALFEKGABMAA.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_ALFEKGABMAA(betterproto.Message):
    """
    CmdId: 8022 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
