# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_OFIHDGFMDGB.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2800_OFIHDGFMDGB(betterproto.Message):
    """
    CmdId: 171 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    giving_id: int = betterproto.uint32_field(4)
