# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_GLLIEOABOML.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_GLLIEOABOML(betterproto.Message):
    """
    CmdId: 8057 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    card_id: int = betterproto.uint32_field(8)
    level_id: int = betterproto.uint32_field(5)
    unk2700__p_h_g_m_k_g_e_m_c_f_f: bool = betterproto.bool_field(10)
