# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_HBLAGOMHKPL_ClientRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_HBLAGOMHKPL_ClientRsp(betterproto.Message):
    """
    CmdId: 137 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(12)
