# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_DFOHGHKAIBO.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_DFOHGHKAIBO(betterproto.Message):
    """
    CmdId: 8442 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    quest_id: int = betterproto.uint32_field(3)
