# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_HGMCNJOPDAA.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk2700_HGMCNJOPDAA(betterproto.Enum):
    Unk2700_HGMCNJOPDAA_NONE = 0
    Unk2700_HGMCNJOPDAA_Unk2700_COJANCPMOAI = 1
