# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_DCKKCAJCNKP_ServerRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_IGJLOMCPLLE import *


@dataclass
class Unk2700_DCKKCAJCNKP_ServerRsp(betterproto.Message):
    """
    CmdId: 6207 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    room_id: int = betterproto.uint32_field(14)
    unk2700__m_p_n_o_b_k_b_m_d_f_g: List[
        "Unk2700_IGJLOMCPLLE"
    ] = betterproto.message_field(9)
    retcode: int = betterproto.int32_field(12)
