# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_HEMFKLPNNOM.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk2700_HEMFKLPNNOM(betterproto.Enum):
    Unk2700_HEMFKLPNNOM_Unk2700_ODJKANKMPPJ = 0
    Unk2700_HEMFKLPNNOM_Unk2700_EFGLHEIODFN = 1
    Unk2700_HEMFKLPNNOM_Unk2700_JPBBBCFGHAK = 2
    Unk2700_HEMFKLPNNOM_Unk2700_IDCMGHBHBFH = 3
    Unk2700_HEMFKLPNNOM_Unk2700_ODDBNNDFMBO = 4
    Unk2700_HEMFKLPNNOM_Unk2700_AGIDMOGJOBD = 5
