# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_HKBAEOMCFOD.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2800_HKBAEOMCFOD(betterproto.Message):
    """
    CmdId: 145 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    giving_id: int = betterproto.uint32_field(10)
    retcode: int = betterproto.int32_field(6)
