# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_LELADCCDNJH.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_LELADCCDNJH(betterproto.Message):
    unk2700__f_a_c_f_k_j_k_i_b_b_o: int = betterproto.uint32_field(1)
    id: int = betterproto.uint32_field(2)
    is_finished: bool = betterproto.bool_field(7)
    unk2700__m_j_d_c_f_o_n_l_g_k_n: bool = betterproto.bool_field(9)
    unk2700__a_k_a_a_h_e_l_a_g_h_j: bool = betterproto.bool_field(10)
