# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_KFPEIHHCCLA.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_KFPEIHHCCLA(betterproto.Message):
    """
    CmdId: 8978 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(2)
    id: int = betterproto.uint32_field(15)
