# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IGJLOMCPLLE.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class Unk2700_IGJLOMCPLLE(betterproto.Message):
    block_id: int = betterproto.uint32_field(8)
    rot: "Vector" = betterproto.message_field(12)
    guid: int = betterproto.uint32_field(4)
    pos: "Vector" = betterproto.message_field(1)
