# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_NCMPMILICGJ.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_NCMPMILICGJ(betterproto.Message):
    """
    CmdId: 8407 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__i_g_m_h_n_d_n_g_n_p_g: int = betterproto.uint32_field(3)
    unk2700__k_i_a_h_j_k_g_o_l_g_o: int = betterproto.uint32_field(7)
    avatar_id: int = betterproto.uint32_field(11)
