# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_GLIILNDIPLK_ServerNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_GLIILNDIPLK_ServerNotify(betterproto.Message):
    """
    CmdId: 6341 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__l_a_l_i_e_a_b_d_f_f_i: bool = betterproto.bool_field(12)
    unk2700__d_c_l_h_f_i_n_j_e_o_d: bool = betterproto.bool_field(8)
    unk2700__g_m_i_c_f_a_d_l_a_m_c: bool = betterproto.bool_field(15)
