# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_BIFNFOGBPNM.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_BIFNFOGBPNM(betterproto.Message):
    is_open: bool = betterproto.bool_field(5)
    route_id: int = betterproto.uint32_field(9)
    unk2700__m_m_n_i_l_g_l_d_h_h_d: bool = betterproto.bool_field(15)
