# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_PCBGAIAJPHH.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_PCBGAIAJPHH(betterproto.Message):
    """
    CmdId: 8758 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    level_id: int = betterproto.uint32_field(7)
