# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_NHEOHBNFHJD.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2800_IOBHBFFAONO import *


@dataclass
class Unk2800_NHEOHBNFHJD(betterproto.Message):
    """
    CmdId: 8870 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    settle_info: "Unk2800_IOBHBFFAONO" = betterproto.message_field(11)
    stage_id: int = betterproto.uint32_field(7)
    is_new_record: bool = betterproto.bool_field(2)
    gallery_id: int = betterproto.uint32_field(1)
