# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_MFAIPHGDPBL.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_MFAIPHGDPBL(betterproto.Message):
    """
    CmdId: 8345 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__l_k_b_h_l_h_i_h_j_g_l: int = betterproto.uint32_field(1)
