# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2200_DEHCEKCILAB_ClientNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2200_DEHCEKCILAB_ClientNotify(betterproto.Message):
    """CmdId: 88 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true"""

    pass
