# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_HHAMNOIDBPJ.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_HHAMNOIDBPJ(betterproto.Message):
    unk2700__j_f_d_n_a_o_a_a_f_m_m: float = betterproto.float_field(9)
