# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_EKDHFFHMNCD.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_EKDHFFHMNCD(betterproto.Message):
    index: int = betterproto.uint32_field(2)
    unk2700__f_a_l_g_e_c_b_m_i_h_d: int = betterproto.uint64_field(14)
    unk2700__p_b_a_f_c_l_c_i_a_b_f: int = betterproto.uint32_field(12)
