# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_DGDJKHJNLGO.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_PGFLJBBEBKG import *


@dataclass
class Unk2700_DGDJKHJNLGO(betterproto.Message):
    uid: int = betterproto.uint32_field(1)
    unk2700__o_e_f_l_h_a_p_a_m_f_h: List[int] = betterproto.uint64_field(2)
    unk2700__o_j_n_b_a_o_c_j_b_c_h: List[int] = betterproto.uint64_field(3)
    unk2700__g_d_d_g_e_k_h_o_l_g_l: List[
        "Unk2700_PGFLJBBEBKG"
    ] = betterproto.message_field(4)
