# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_KLJLJGJOBDI.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_NCNPNMFFONG import *


@dataclass
class Unk2700_KLJLJGJOBDI(betterproto.Message):
    unk2700__c_d_d_o_n_j_j_m_f_c_i: int = betterproto.uint32_field(8)
    reason: "Unk2700_NCNPNMFFONG" = betterproto.enum_field(7)
    final_score: int = betterproto.uint32_field(13)
    unk2700__f_f_c_c_l_g_i_f_g_i_p: int = betterproto.uint32_field(15)
