# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_IMLDGLIMODE.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk2800_IMLDGLIMODE(betterproto.Enum):
    Unk2800_IMLDGLIMODE_NONE = 0
    Unk2800_IMLDGLIMODE_Unk2800_FIPMFJALDJM = 1
    Unk2800_IMLDGLIMODE_Unk2800_OFNLGLLMMED = 2
