# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_CHEDEMEDPPM.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2800_CHEDEMEDPPM(betterproto.Message):
    """
    CmdId: 5565 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    point_id: int = betterproto.uint32_field(7)
    coin: int = betterproto.uint32_field(15)
    unk2800__e_o_f_o_e_c_j_j_m_l_j: int = betterproto.uint32_field(3)
    unk2800__b_a_e_e_d_e_a_a_d_i_a: int = betterproto.uint32_field(13)
