# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_MCJIOOELGHG_ServerNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_JDPMOMKAPIF import *


@dataclass
class Unk2700_MCJIOOELGHG_ServerNotify(betterproto.Message):
    """
    CmdId: 6033 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__k_b_m_k_g_n_g_f_g_f_o: List[
        "Unk2700_JDPMOMKAPIF"
    ] = betterproto.message_field(6)
