# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_OFDBHGHAJBD_ServerNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_MIBBHAEMAGI import *


@dataclass
class Unk2700_OFDBHGHAJBD_ServerNotify(betterproto.Message):
    """
    CmdId: 6223 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__j_i_f_a_a_p_c_j_o_h_k: "Unk2700_MIBBHAEMAGI" = betterproto.message_field(
        12
    )
