# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_GPPKNKGDCHJ.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


@dataclass
class Unk2700_GPPKNKGDCHJ(betterproto.Message):
    unk2700__m_n_p_g_j_o_a_h_i_n_c: List["ItemParam"] = betterproto.message_field(2)
    uid: int = betterproto.uint32_field(6)
    unk2700__l_b_i_k_f_n_b_n_e_b_c: List["ItemParam"] = betterproto.message_field(9)
