# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_LLBCBPADBNO.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_DIEGJDEIDKO import *


@dataclass
class Unk2700_LLBCBPADBNO(betterproto.Message):
    """
    CmdId: 8154 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    explore_info: "Unk2700_DIEGJDEIDKO" = betterproto.message_field(12)
    battle_info: "Unk2700_DIEGJDEIDKO" = betterproto.message_field(4)
