# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_MMFIJILOCOP_ClientReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_IMMPPANFEPP import *


@dataclass
class Unk2700_MMFIJILOCOP_ClientReq(betterproto.Message):
    """
    CmdId: 4486 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__j_j_b_k_b_k_p_e_i_b_c: "Unk2700_IMMPPANFEPP" = betterproto.message_field(1)
