# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_NDDBFNNHLFE.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_DJKEGIEIKHG import *


@dataclass
class Unk2700_NDDBFNNHLFE(betterproto.Message):
    """
    CmdId: 8340 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    settle_info: "Unk2700_DJKEGIEIKHG" = betterproto.message_field(13)
    gallery_id: int = betterproto.uint32_field(5)
