# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_PILILDPMNNA.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Unk2700_PILILDPMNNA(betterproto.Message):
    difficulty: int = betterproto.uint32_field(7)
    unk2700__e_g_b_d_d_l_o_b_c_d_l: List[int] = betterproto.uint32_field(4)
    unk2700__m_m_f_h_b_h_n_k_l_d_g: bool = betterproto.bool_field(9)
    stage_id: int = betterproto.uint32_field(12)
    unk2700__p_p_e_b_o_k_b_c_p_l_e: int = betterproto.uint32_field(3)
