# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IAAPADOAMIA.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .ItemParam import *


@dataclass
class Unk2700_IAAPADOAMIA(betterproto.Message):
    """
    CmdId: 8414 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__h_c_k_a_m_f_p_g_m_j_n: int = betterproto.uint32_field(14)
    unk2700__c_h_h_j_b_p_d_p_i_c_i: int = betterproto.uint32_field(7)
    quest_id: int = betterproto.uint32_field(11)
    item_list: List["ItemParam"] = betterproto.message_field(10)
    unk2700__a_g_f_n_j_h_a_m_d_b_d: bool = betterproto.bool_field(9)
    unk2700__a_j_k_d_p_j_o_k_b_e_d: List[int] = betterproto.uint32_field(6)
    unk2700__o_e_d_d_p_d_j_e_e_p_c: int = betterproto.uint32_field(3)
