# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_MDPHLPEGFCG_ClientReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_MDPHLPEGFCG_ClientReq(betterproto.Message):
    """
    CmdId: 4020 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
