# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_GPOIPAHPHJE.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_GPOIPAHPHJE(betterproto.Message):
    """
    CmdId: 8967 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    stage_id: int = betterproto.uint32_field(14)
    challenge_type: int = betterproto.uint32_field(13)
