# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_KLPINMKOEPE.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk2700_IGJLOMCPLLE import *


@dataclass
class Unk2700_KLPINMKOEPE(betterproto.Message):
    room_id: int = betterproto.uint32_field(15)
    unk2700__i_c_m_k_k_o_m_l_h_i_h: List[
        "Unk2700_IGJLOMCPLLE"
    ] = betterproto.message_field(4)
