# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IGPIIHEDJLJ_ServerRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto

from .Unk2700_KBBDJNLFAKD import *
from .Unk2700_NLFDMMFNMIO import *


@dataclass
class Unk2700_IGPIIHEDJLJ_ServerRsp(betterproto.Message):
    """
    CmdId: 6218 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__e_j_h_n_b_d_l_l_l_f_o: "Unk2700_NLFDMMFNMIO" = betterproto.message_field(
        14
    )
    unk2700__l_g_b_o_d_a_b_i_k_l_l: "Unk2700_KBBDJNLFAKD" = betterproto.enum_field(2)
    retcode: int = betterproto.int32_field(10)
    unk2700__d_d_g_n_p_j_l_h_k_k_h: Dict[int, int] = betterproto.map_field(
        6, betterproto.TYPE_UINT32, betterproto.TYPE_UINT32
    )
