# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_MPPAHFFHIPI_ServerNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_MPPAHFFHIPI_ServerNotify(betterproto.Message):
    """
    CmdId: 4187 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    match_id: int = betterproto.uint32_field(9)
