# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_EDDNHJPJBBF.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_EDDNHJPJBBF(betterproto.Message):
    """
    CmdId: 8733 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_id: int = betterproto.uint32_field(7)
