# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_NPOBPFNDJKK.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk2700_NPOBPFNDJKK(betterproto.Enum):
    Unk2700_NPOBPFNDJKK_Unk2700_PGICIHIAMBF = 0
    Unk2700_NPOBPFNDJKK_Unk2700_OALJEIJHGKL = 1
    Unk2700_NPOBPFNDJKK_Unk2700_JDIGCAMIBIA = 2
    Unk2700_NPOBPFNDJKK_Unk2700_KBGKJADDAAF = 3
    Unk2700_NPOBPFNDJKK_Unk2700_MNPNGKHMFNA = 4
    Unk2700_NPOBPFNDJKK_Unk2700_NBCDOEINJLJ = 5
    Unk2700_NPOBPFNDJKK_Unk2700_PHLJKMGKCBM = 6
