# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2800_LGIKLPBOJOI.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Unk2800_LGIKLPBOJOI(betterproto.Message):
    """
    CmdId: 8145 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2800__a_e_k_p_b_k_a_a_h_f_l: List[int] = betterproto.uint32_field(14)
    activity_id: int = betterproto.uint32_field(7)
