# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_AMKLCEFNNCC.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_AMKLCEFNNCC(betterproto.Message):
    is_trial: bool = betterproto.bool_field(6)
    avatar_id: int = betterproto.uint64_field(8)
