# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_LBJKLAGNDEJ_ClientReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_LBJKLAGNDEJ_ClientReq(betterproto.Message):
    """
    CmdId: 4759 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    group_id: int = betterproto.uint32_field(2)
