# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk2700_IJFEPCBOLDF.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk2700_IJFEPCBOLDF(betterproto.Message):
    """
    CmdId: 8756 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_new_record: bool = betterproto.bool_field(9)
    unk2700__m_m_n_i_l_g_l_d_h_h_d: bool = betterproto.bool_field(3)
    level_id: int = betterproto.uint32_field(15)
    score: int = betterproto.uint32_field(8)
