# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_HIJKNFBBCFC.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_HIJKNFBBCFC(betterproto.Message):
    """
    CmdId: 23948 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk3000__p_a_f_i_g_d_f_h_g_n_a: int = betterproto.uint32_field(6)
    param: int = betterproto.uint32_field(11)
    retcode: int = betterproto.int32_field(12)
