# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_IBNIGBFIEEF.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_IBNIGBFIEEF(betterproto.Message):
    """
    CmdId: 1735 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(4)
