# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_BPKIOJEIJAF.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk3000_ICLKJJNGOHN import *


@dataclass
class Unk3000_BPKIOJEIJAF(betterproto.Message):
    unk2700__p_h_k_h_i_p_l_d_o_o_a: List[
        "Unk3000_ICLKJJNGOHN"
    ] = betterproto.message_field(9)
