# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_DCHMAMFIFOF.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_DCHMAMFIFOF(betterproto.Message):
    unk3000__p_a_f_i_g_d_f_h_g_n_a: int = betterproto.uint32_field(1)
    finish_time: int = betterproto.uint32_field(4)
    param: int = betterproto.uint32_field(14)
