# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_OMCBMAHOLHB.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_OMCBMAHOLHB(betterproto.Message):
    buff_id: int = betterproto.uint32_field(6)
    unk3000__k_d_o_l_d_n_m_n_h_g_l: int = betterproto.uint64_field(9)
    unk3000__o_k_i_d_n_a_a_k_o_j_c: int = betterproto.uint64_field(4)
