# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_ACNMEFGKHKO.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_ACNMEFGKHKO(betterproto.Message):
    """
    CmdId: 4622 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(13)
    unk3000__l_o_f_n_f_m_j_f_g_n_b: int = betterproto.uint32_field(1)
    unk3000__d_e_d_h_c_i_k_c_a_g_h: int = betterproto.uint32_field(3)
    unk3000__h_c_a_j_d_i_b_h_k_d_g: int = betterproto.uint32_field(2)
