# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_DLCDJPKNGBD.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_DLCDJPKNGBD(betterproto.Message):
    """
    CmdId: 185 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk3000__f_g_i_j_k_f_a_n_k_e_i: bool = betterproto.bool_field(8)
    unk3000__l_h_i_i_n_b_o_c_m_f_n: int = betterproto.uint32_field(14)
    unk3000__h_m_l_g_h_b_e_k_c_o_f: int = betterproto.uint32_field(9)
    unk3000__e_m_j_d_l_a_n_p_p_n_f: int = betterproto.uint32_field(1)
