# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_AMGHKNBNNPD.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Vector import *


@dataclass
class Unk3000_AMGHKNBNNPD(betterproto.Message):
    unk3000__o_f_f_b_b_h_i_k_d_i_n: float = betterproto.float_field(1)
    animator_state_id_list: List[int] = betterproto.uint32_field(2)
    entity_id: int = betterproto.uint32_field(3)
    need_set_is_in_air: bool = betterproto.bool_field(13)
    speed: float = betterproto.float_field(12)
    unk3000__p_j_p_f_i_p_o_l_n_a_h: float = betterproto.float_field(8)
    check_animator_state_on_exit_only: bool = betterproto.bool_field(11)
    override_collider: str = betterproto.string_field(14)
    target_pos: "Vector" = betterproto.message_field(10)
