# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_GNOPDGELABH.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_GNOPDGELABH(betterproto.Message):
    unk3000__k_n_o_b_d_d_h_i_o_n_h: float = betterproto.float_field(1)
    unk3000__n_d_b_j_c_j_e_i_e_e_o: float = betterproto.float_field(2)
    unk3000__c_g_b_h_k_p_e_g_b_o_d: float = betterproto.float_field(3)
