# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_PPDLLPNMJMK.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_PPDLLPNMJMK(betterproto.Message):
    """
    CmdId: 500 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk3000__c_f_d_m_l_g_k_n_l_k_l: int = betterproto.uint32_field(4)
    unk3000__c_i_o_l_e_g_e_h_d_a_c: int = betterproto.uint32_field(9)
