# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_KJNIKBPKAED.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_KJNIKBPKAED(betterproto.Message):
    """
    CmdId: 461 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(5)
    unk3000__c_f_d_m_l_g_k_n_l_k_l: int = betterproto.uint32_field(14)
    unk3000__c_i_o_l_e_g_e_h_d_a_c: int = betterproto.uint32_field(13)
