# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_EDGJEBLODLF.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_EDGJEBLODLF(betterproto.Message):
    """
    CmdId: 416 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk3000__c_f_d_m_l_g_k_n_l_k_l: int = betterproto.uint32_field(2)
    unk3000__c_i_o_l_e_g_e_h_d_a_c: int = betterproto.uint32_field(13)
    unk3000__f_d_g_f_a_h_a_o_e_p_p: int = betterproto.uint32_field(5)
    retcode: int = betterproto.int32_field(8)
