# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_CMEPCFFDIGL.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk3000_GDKMIBFADKD import *


@dataclass
class Unk3000_CMEPCFFDIGL(betterproto.Message):
    level: int = betterproto.int32_field(10)
    unk3000__m_k_i_j_e_i_k_f_i_j_p: List[
        "Unk3000_GDKMIBFADKD"
    ] = betterproto.message_field(6)
