# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_LHEMAMBKEKI.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_LHEMAMBKEKI(betterproto.Message):
    """
    CmdId: 6107 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(7)
