# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_LNCOEOMFKAO.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_LNCOEOMFKAO(betterproto.Message):
    unk3000__j_c_g_k_n_m_j_f_p_g_c: int = betterproto.uint32_field(1)
    unk3000__d_g_d_i_b_e_k_b_b_l_g: int = betterproto.uint32_field(2)
