# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_IPAKLDNKDAO.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_IPAKLDNKDAO(betterproto.Message):
    """
    CmdId: 6275 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk3000__f_j_i_j_o_i_m_j_m_p_f: int = betterproto.uint32_field(8)
