# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_KEJDIJAEMKD.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_KEJDIJAEMKD(betterproto.Message):
    score: int = betterproto.uint32_field(6)
    unk3000__m_k_f_i_p_l_f_h_j_n_e: int = betterproto.uint32_field(4)
    unk3000__f_e_l_j_k_c_a_a_j_m_j: int = betterproto.uint32_field(10)
    unk3000__j_k_h_k_n_k_n_b_f_d_c: int = betterproto.uint32_field(9)
