# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_CPCMICDDBCH.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_CPCMICDDBCH(betterproto.Message):
    """
    CmdId: 20011 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk3000__m_k_f_i_p_l_f_h_j_n_e: int = betterproto.uint32_field(10)
    level_id: int = betterproto.uint32_field(15)
