# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_MFCAIADEPGJ.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Vector import *


class Unk3000_MFCAIADEPGJUnk3000_PNOAFGLCLPG(betterproto.Enum):
    Unk3000_PNOAFGLCLPG_STATUS_FAIL = 0
    Unk3000_PNOAFGLCLPG_STATUS_SUCC = 1
    Unk3000_PNOAFGLCLPG_STATUS_PARTIAL = 2


@dataclass
class Unk3000_MFCAIADEPGJ(betterproto.Message):
    """
    CmdId: 6198 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    query_status: "Unk3000_MFCAIADEPGJUnk3000_PNOAFGLCLPG" = betterproto.enum_field(7)
    index: List[int] = betterproto.int64_field(3)
    corners: List["Vector"] = betterproto.message_field(14)
    level: List[int] = betterproto.int32_field(1)
    retcode: int = betterproto.int32_field(8)
    query_id: int = betterproto.int32_field(9)
