# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_IKBGMGECDPG.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk3000_OMCBMAHOLHB import *


@dataclass
class Unk3000_IKBGMGECDPG(betterproto.Message):
    score: int = betterproto.uint32_field(5)
    unk2700__i_n_i_b_k_f_p_m_c_f_o: List[
        "Unk3000_OMCBMAHOLHB"
    ] = betterproto.message_field(12)
