# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_NJNPNJDFEOL.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_NJNPNJDFEOL(betterproto.Message):
    """
    CmdId: 6112 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
