# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_ILLNKBDNGKP.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk3000_DCHMAMFIFOF import *
from .Unk3000_HGBNOCJBDEK import *


@dataclass
class Unk3000_ILLNKBDNGKP(betterproto.Message):
    unk2700__p_h_k_h_i_p_l_d_o_o_a: List[
        "Unk3000_HGBNOCJBDEK"
    ] = betterproto.message_field(5)
    unk3000__a_i_e_n_c_m_l_m_c_b_e: List[
        "Unk3000_DCHMAMFIFOF"
    ] = betterproto.message_field(7)
