# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_EOLNDBMGCBP.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_EOLNDBMGCBP(betterproto.Message):
    """
    CmdId: 4473 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pass
