# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_OFMFFECMKLE.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk3000_FLOEPMMABMH import *


@dataclass
class Unk3000_OFMFFECMKLE(betterproto.Message):
    unk2700__f_i_k_h_c_f_m_e_o_a_j: List[
        "Unk3000_FLOEPMMABMH"
    ] = betterproto.message_field(11)
