# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_GDKMIBFADKD.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class Unk3000_GDKMIBFADKD(betterproto.Message):
    index: int = betterproto.int64_field(8)
    area: int = betterproto.int32_field(5)
    unk3000__a_o_e_g_l_p_p_f_i_f_d: "Vector" = betterproto.message_field(1)
