# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_GNLFOLGMEPN.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_GNLFOLGMEPN(betterproto.Message):
    """
    CmdId: 21208 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(5)
