# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_BGPMEPKCLPA.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Unk3000_CMEPCFFDIGL import *


@dataclass
class Unk3000_BGPMEPKCLPA(betterproto.Message):
    unk3000__m_k_i_j_e_i_k_f_i_j_p: List[
        "Unk3000_CMEPCFFDIGL"
    ] = betterproto.message_field(3)
