# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_PJLAPMPPIAG.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Unk2700_MOFABPNGIKP import *


@dataclass
class Unk3000_PJLAPMPPIAG(betterproto.Message):
    """
    CmdId: 20681 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    is_new_record: bool = betterproto.bool_field(4)
    gallery_id: int = betterproto.uint32_field(6)
    score: int = betterproto.uint32_field(5)
    reason: "Unk2700_MOFABPNGIKP" = betterproto.enum_field(2)
    unk3000__o_g_f_o_a_o_c_c_g_n_k: int = betterproto.uint32_field(13)
    remain_time: int = betterproto.uint32_field(10)
    unk3000__h_k_m_k_h_p_m_i_i_p_f: int = betterproto.uint32_field(1)
    unk3000__g_d_f_h_j_b_o_c_o_n_o: int = betterproto.uint32_field(8)
    is_success: bool = betterproto.bool_field(7)
    level_id: int = betterproto.uint32_field(11)
