# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_PKHPBOIDLEA.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Unk3000_PKHPBOIDLEA(betterproto.Enum):
    Unk3000_PKHPBOIDLEA_Unk3000_KANMGBLJEHC = 0
    Unk3000_PKHPBOIDLEA_Unk3000_ICFILKDKFNL = 1
    Unk3000_PKHPBOIDLEA_Unk3000_FBFKPBGLMAD = 2
    Unk3000_PKHPBOIDLEA_Unk3000_KEOIEIKLFDN = 3
