# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_BMLKKNEINNF.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .MailData import *


@dataclass
class Unk3000_BMLKKNEINNF(betterproto.Message):
    """
    CmdId: 1481 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk3000__h_j_k_c_l_h_g_m_b_f_c: str = betterproto.string_field(9)
    mail_list: List["MailData"] = betterproto.message_field(5)
    unk3000__o_j_i_k_n_b_e_g_a_k_l: int = betterproto.uint32_field(11)
    unk3000__d_k_l_g_o_i_e_p_e_c_b: int = betterproto.uint32_field(4)
    unk2700__o_p_e_h_l_d_a_g_i_c_f: bool = betterproto.bool_field(7)
    retcode: int = betterproto.int32_field(14)
