# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Unk3000_MNBPHBIHKKI.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Unk3000_MNBPHBIHKKI(betterproto.Message):
    progress: int = betterproto.uint32_field(15)
    unk3000__m_o_n_n_e_p_n_g_n_c_a: int = betterproto.uint32_field(14)
