# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UnlockCoopChapterReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class UnlockCoopChapterReq(betterproto.Message):
    """
    CmdId: 1970 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    chapter_id: int = betterproto.uint32_field(3)
