# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UnlockNameCardNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class UnlockNameCardNotify(betterproto.Message):
    """
    CmdId: 4006 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    name_card_id: int = betterproto.uint32_field(8)
