# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UpdatePS4BlockListRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class UpdatePS4BlockListRsp(betterproto.Message):
    """
    CmdId: 4041 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(7)
