# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UpdatePlayerShowNameCardListRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class UpdatePlayerShowNameCardListRsp(betterproto.Message):
    """
    CmdId: 4019 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(13)
    show_name_card_id_list: List[int] = betterproto.uint32_field(12)
