# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UseMiracleRingReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


class UseMiracleRingReqMiracleRingOpType(betterproto.Enum):
    MIRACLE_RING_OP_TYPE_NONE = 0
    MIRACLE_RING_OP_TYPE_PLACE = 1
    MIRACLE_RING_OP_TYPE_RETRACT = 2


@dataclass
class UseMiracleRingReq(betterproto.Message):
    """
    CmdId: 5226 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    miracle_ring_op_type: int = betterproto.uint32_field(13)
    pos: "Vector" = betterproto.message_field(8)
    rot: "Vector" = betterproto.message_field(7)
