# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UseMiracleRingRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class UseMiracleRingRsp(betterproto.Message):
    """
    CmdId: 5218 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(11)
    miracle_ring_op_type: int = betterproto.uint32_field(7)
