# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UseWidgetCreateGadgetReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .Vector import *


@dataclass
class UseWidgetCreateGadgetReq(betterproto.Message):
    """
    CmdId: 4293 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    pos: "Vector" = betterproto.message_field(15)
    rot: "Vector" = betterproto.message_field(12)
    material_id: int = betterproto.uint32_field(4)
