# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: UseWidgetCreateGadgetRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class UseWidgetCreateGadgetRsp(betterproto.Message):
    """
    CmdId: 4290 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(15)
    material_id: int = betterproto.uint32_field(12)
