# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: VectorPlane.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class VectorPlane(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)
