# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: VehicleInteractType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class VehicleInteractType(betterproto.Enum):
    VEHICLE_INTERACT_TYPE_NONE = 0
    VEHICLE_INTERACT_TYPE_IN = 1
    VEHICLE_INTERACT_TYPE_OUT = 2
