# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: VehicleInteractRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .VehicleInteractType import *
from .VehicleMember import *


@dataclass
class VehicleInteractRsp(betterproto.Message):
    """
    CmdId: 804 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    interact_type: "VehicleInteractType" = betterproto.enum_field(15)
    member: "VehicleMember" = betterproto.message_field(3)
    entity_id: int = betterproto.uint32_field(2)
    retcode: int = betterproto.int32_field(1)
