# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: VehicleLocationInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .Vector import *


@dataclass
class VehicleLocationInfo(betterproto.Message):
    rot: "Vector" = betterproto.message_field(14)
    entity_id: int = betterproto.uint32_field(15)
    cur_hp: float = betterproto.float_field(11)
    owner_uid: int = betterproto.uint32_field(5)
    pos: "Vector" = betterproto.message_field(1)
    uid_list: List[int] = betterproto.uint32_field(3)
    gadget_id: int = betterproto.uint32_field(13)
    max_hp: float = betterproto.float_field(6)
