# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: VehicleMember.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class VehicleMember(betterproto.Message):
    uid: int = betterproto.uint32_field(1)
    avatar_guid: int = betterproto.uint64_field(2)
    pos: int = betterproto.uint32_field(3)
