# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WatcherEventTypeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class WatcherEventTypeNotify(betterproto.Message):
    """
    CmdId: 2235 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    param_list: List[int] = betterproto.uint32_field(14)
    add_progress: int = betterproto.uint32_field(15)
    watcher_trigger_type: int = betterproto.uint32_field(11)
