# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WatcherEventNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class WatcherEventNotify(betterproto.Message):
    """
    CmdId: 2212 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    add_progress: int = betterproto.uint32_field(6)
    watcher_id: int = betterproto.uint32_field(9)
