# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WearEquipReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class WearEquipReq(betterproto.Message):
    """
    CmdId: 697 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    equip_guid: int = betterproto.uint64_field(7)
    avatar_guid: int = betterproto.uint64_field(5)
