# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WeatherInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class WeatherInfo(betterproto.Message):
    weather_area_id: int = betterproto.uint32_field(1)
