# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WidgetCameraInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class WidgetCameraInfo(betterproto.Message):
    target_entity_id: int = betterproto.uint32_field(4)
