# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WidgetGadgetDataNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .WidgetGadgetData import *


@dataclass
class WidgetGadgetDataNotify(betterproto.Message):
    """
    CmdId: 4266 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    widget_gadget_data: "WidgetGadgetData" = betterproto.message_field(12)
