# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WidgetCreatorOpType.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class WidgetCreatorOpType(betterproto.Enum):
    WIDGET_CREATOR_OP_TYPE_NONE = 0
    WIDGET_CREATOR_OP_TYPE_RETRACT = 1
    WIDGET_CREATOR_OP_TYPE_RETRACT_AND_CREATE = 2
