# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WidgetSlotOp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class WidgetSlotOp(betterproto.Enum):
    WIDGET_SLOT_OP_ATTACH = 0
    WIDGET_SLOT_OP_DETACH = 1
