# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WidgetReportRsp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class WidgetReportRsp(betterproto.Message):
    """
    CmdId: 4292 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    retcode: int = betterproto.int32_field(14)
    material_id: int = betterproto.uint32_field(4)
