# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WidgetReportReq.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class WidgetReportReq(betterproto.Message):
    """
    CmdId: 4291 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    unk2700__m_f_e_h_m_l_b_n_n_a_g: bool = betterproto.bool_field(5)
    is_client_collect: bool = betterproto.bool_field(14)
    is_clear_hint: bool = betterproto.bool_field(13)
    material_id: int = betterproto.uint32_field(15)
