# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WidgetActiveChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .WidgetSlotData import *


@dataclass
class WidgetActiveChangeNotify(betterproto.Message):
    """
    CmdId: 4280 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    widget_data_list: List["WidgetSlotData"] = betterproto.message_field(5)
