# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WidgetThunderBirdFeatherInfo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class WidgetThunderBirdFeatherInfo(betterproto.Message):
    entity_id_list: List[int] = betterproto.uint32_field(4)
