# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WidgetCoolDownNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .WidgetCoolDownData import *


@dataclass
class WidgetCoolDownNotify(betterproto.Message):
    """
    CmdId: 4295 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    normal_cool_down_data_list: List["WidgetCoolDownData"] = betterproto.message_field(
        1
    )
    group_cool_down_data_list: List["WidgetCoolDownData"] = betterproto.message_field(
        12
    )
