# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WorktopOptionNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class WorktopOptionNotify(betterproto.Message):
    """
    CmdId: 835 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    gadget_entity_id: int = betterproto.uint32_field(11)
    option_list: List[int] = betterproto.uint32_field(8)
