# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WorldRoutineChangeNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .WorldRoutineInfo import *


@dataclass
class WorldRoutineChangeNotify(betterproto.Message):
    """
    CmdId: 3507 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    routine_info: "WorldRoutineInfo" = betterproto.message_field(3)
    routine_type: int = betterproto.uint32_field(11)
