# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WorldPlayerRTTNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .PlayerRTTInfo import *


@dataclass
class WorldPlayerRTTNotify(betterproto.Message):
    """CmdId: 22 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true"""

    player_rtt_list: List["PlayerRTTInfo"] = betterproto.message_field(1)
