# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WorldOwnerDailyTaskNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .DailyTaskInfo import *


@dataclass
class WorldOwnerDailyTaskNotify(betterproto.Message):
    """
    CmdId: 102 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    filter_city_id: int = betterproto.uint32_field(2)
    task_list: List["DailyTaskInfo"] = betterproto.message_field(1)
