# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WorldRoutineTypeCloseNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class WorldRoutineTypeCloseNotify(betterproto.Message):
    """
    CmdId: 3502 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    routine_type: int = betterproto.uint32_field(7)
