# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WorldOwnerBlossomScheduleInfoNotify.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .BlossomScheduleInfo import *


@dataclass
class WorldOwnerBlossomScheduleInfoNotify(betterproto.Message):
    """
    CmdId: 2707 EnetChannelId: 0 EnetIsReliable: false IsAllowClient: true
    """

    schedule_info: "BlossomScheduleInfo" = betterproto.message_field(3)
